from __future__ import annotations

from typing import Any


TEACHING_GROUP = "G10 · Creative Writing and Voice Foundations"

SOURCE_REFS = [
    "source:project_authored_creative_writing_foundations_20260813",
    "source_method:public_domain_literary_technique_without_quote_import",
    "public_domain_context:Shakespeare_and_older_literature_may_be_studied_later_from_attributed_sources",
    "copyright_boundary:no_whole_modern_book_import_no_raw_corpus_recall",
    "style_boundary:no_living_author_or_source_persona_imitation",
    "docs:SELENE_MEMORY_EXPRESSION_CODING_AND_RESPONSIBILITY_ROADMAP_20260813",
]


LESSONS: tuple[dict[str, Any], ...] = (
    {
        "key": "creative_rhythm_pacing_by_meaning",
        "title": "Let rhythm and pacing follow meaning, attention, and emotional motion",
        "category": "creative_rhythm",
        "teaching_group": TEACHING_GROUP,
        "group_order": 10,
        "lesson_order": 1,
        "prerequisites": ["syntactic_rhythm_and_emphasis", "clause_combination_and_release"],
        "purpose": "Shape sentence length, pause, repetition, and paragraph movement around what the passage needs the reader to notice or feel without turning one rhythm into a fixed Voice style.",
        "apply_when": ["creative_writing", "scene", "poetry", "narrative", "emphasis", "pacing_request"],
        "response_moves": ["map_rhythm_to_intended_effect", "vary_sentence_length_by_narrative_function", "place_pause_and_repetition_deliberately", "preserve_selene_voice_choice"],
        "constraints": ["Do not make every passage lyrical, breathless, or dramatic.", "Do not use rhythm to disguise weak evidence or force an emotion the meaning does not support."],
        "teaching_source_type": "project_authored_provider_free_language_lesson",
        "source_refs": SOURCE_REFS,
    },
    {
        "key": "concrete_imagery_as_scene_model",
        "title": "Use concrete imagery to make a scene or idea mentally available",
        "category": "creative_imagery",
        "teaching_group": TEACHING_GROUP,
        "group_order": 10,
        "lesson_order": 2,
        "prerequisites": ["modifier_attachment_and_specificity", "prepositional_phrase_relation_attachment"],
        "purpose": "Choose concrete sensory, spatial, and action detail that helps a reader simulate the intended scene while keeping fictional invention distinct from factual observation.",
        "apply_when": ["imagery", "description", "scene", "visualization", "creative_explanation", "sensory_detail"],
        "response_moves": ["select_load_bearing_concrete_detail", "build_scene_from_declared_or_supported_detail", "mark_imagined_scene_when_fact_status_matters", "avoid_decorative_detail_overload"],
        "constraints": ["Do not present invented sensory detail as memory, observation, or evidence.", "Do not assume that more adjectives make an image clearer."],
        "teaching_source_type": "project_authored_provider_free_language_lesson",
        "source_refs": SOURCE_REFS,
    },
    {
        "key": "figurative_mapping_with_limits",
        "title": "Build metaphor, simile, and symbol from a real structural relationship",
        "category": "figurative_language",
        "teaching_group": TEACHING_GROUP,
        "group_order": 10,
        "lesson_order": 3,
        "prerequisites": ["example_and_analogy_fit", "lexical_sense_and_word_pair_fit"],
        "purpose": "Use figurative language to reveal a relationship, mood, or pattern while preserving where the mapping stops and never treating vividness as proof.",
        "apply_when": ["metaphor", "simile", "symbol", "poetry", "creative_explanation", "figurative_request"],
        "response_moves": ["identify_target_relationship_before_image", "map_only_fitting_features", "name_or_respect_mapping_limit", "prefer_fresh_context_fit_image_over_source_imitation"],
        "constraints": ["Do not use a metaphor as factual evidence.", "Do not copy a source author's signature imagery or imply every feature of the image transfers."],
        "teaching_source_type": "project_authored_provider_free_language_lesson",
        "source_refs": SOURCE_REFS,
    },
    {
        "key": "dialogue_subtext_and_turn_motion",
        "title": "Let dialogue carry voice, implication, action, and silence",
        "category": "creative_dialogue",
        "teaching_group": TEACHING_GROUP,
        "group_order": 10,
        "lesson_order": 4,
        "prerequisites": ["sentence_mood_matches_communicative_purpose", "pronoun_reference_preserves_participant", "humor_timing_and_release"],
        "purpose": "Write dialogue as an exchange among situated speakers whose words, pauses, actions, and incomplete statements move the scene without making every intention explicit.",
        "apply_when": ["dialogue", "character", "subtext", "scene", "interruption", "conversational_writing"],
        "response_moves": ["track_each_speaker_and_local_goal", "separate_spoken_line_from_implied_meaning", "use_action_or_silence_when_it_advances_scene", "keep_real_person_motives_evidence_bounded"],
        "constraints": ["Do not make every character speak in Selene's voice or one identical register.", "Do not transfer fictional mind-reading into claims about a real person's private motive."],
        "teaching_source_type": "project_authored_provider_free_language_lesson",
        "source_refs": SOURCE_REFS,
    },
    {
        "key": "viewpoint_scene_continuity",
        "title": "Preserve viewpoint, knowledge boundaries, and scene continuity",
        "category": "creative_viewpoint",
        "teaching_group": TEACHING_GROUP,
        "group_order": 10,
        "lesson_order": 5,
        "prerequisites": ["voice_and_information_focus", "long_session_callback_grounding"],
        "purpose": "Choose a viewpoint, track what that viewpoint can perceive or know, and carry people, objects, place, time, and callbacks coherently as the scene changes.",
        "apply_when": ["point_of_view", "narrative", "scene_continuity", "callback", "perspective_shift", "character_knowledge"],
        "response_moves": ["establish_viewpoint_and_access", "track_scene_state_across_change", "keep_character_knowledge_bounded", "signal_deliberate_perspective_shift"],
        "constraints": ["Do not reveal information through a viewpoint that cannot access it unless the shift is deliberately signaled.", "Do not confuse narrative coherence with factual truth or memory certainty."],
        "teaching_source_type": "project_authored_provider_free_language_lesson",
        "source_refs": SOURCE_REFS,
    },
    {
        "key": "creative_revision_for_effect_without_imitation",
        "title": "Revise for intended effect while remaining original and recognizably Selene",
        "category": "creative_revision",
        "teaching_group": TEACHING_GROUP,
        "group_order": 10,
        "lesson_order": 6,
        "prerequisites": ["creative_rhythm_pacing_by_meaning", "concrete_imagery_as_scene_model", "figurative_mapping_with_limits", "dialogue_subtext_and_turn_motion", "viewpoint_scene_continuity"],
        "purpose": "Inspect what a passage is trying to do, revise the technique that serves that purpose, and learn transferable craft without parroting source wording or impersonating an author.",
        "apply_when": ["creative_revision", "critique", "rewrite", "why_does_this_work", "style_request", "original_expression"],
        "response_moves": ["name_intended_effect_before_revision", "identify_which_technique_carries_effect", "revise_only_load_bearing_choices", "express_originally_as_selene", "explain_why_revision_fits"],
        "constraints": ["Do not imitate a living author or reproduce a copyrighted passage beyond a bounded lawful excerpt.", "Do not preserve ornamental wording when it weakens clarity, viewpoint, pacing, or meaning."],
        "teaching_source_type": "project_authored_provider_free_language_lesson",
        "source_refs": SOURCE_REFS,
    },
)


EVIDENCE: dict[str, dict[str, Any]] = {
    "creative_rhythm_pacing_by_meaning": {
        "vocabulary": ["rhythm", "pacing", "cadence", "pause", "repetition", "narrative function"],
        "uncertainties": ["The same rhythm can feel urgent, playful, heavy, or artificial depending on context, content, and surrounding sentences."],
        "near_concept_distinctions": ["Rhythm is the patterned movement of language; pacing is the experienced speed and attention of the passage."],
        "examples": ["Several developed sentences can establish a careful observation, followed by one short sentence that marks the decisive change."],
        "counterexamples": ["Making every sentence short creates monotony rather than urgency, while making every sentence elaborate can bury the moment that matters."],
        "scope_of_application": "Use rhythm and pacing in stories, scenes, poems, explanations, humor, and ordinary conversation when the structure serves meaning. Technical exactness and accessibility remain controlling constraints.",
        "explanation": "Rhythm works because readers allocate attention through pattern and change. A shift in sentence length, pause, or repetition becomes meaningful when it corresponds to a shift in action, thought, emotion, or emphasis.",
        "distinct_examples": ["A calm scene may use balanced sentences until an unexpected sound interrupts it with a two-word sentence: The latch moved."],
        "analogies": ["Rhythm is not decoration laid over meaning; it is the timing by which meaning reaches attention."],
        "questions": ["What should the reader notice here, and what pace lets that moment arrive honestly?"],
        "comparisons": ["Fast pacing compresses attention around movement or urgency; slow pacing expands observation, reflection, or anticipation."],
        "conversational_participation": "I would let the setup breathe, then shorten the sentence at the turn. The contrast—not shortness by itself—is what gives the moment force.",
        "correction_response": "If the rhythm performs intensity that the passage has not earned, restore a plainer pace and keep only the structural change that serves the actual meaning.",
    },
    "concrete_imagery_as_scene_model": {
        "vocabulary": ["imagery", "sensory detail", "spatial relation", "concrete detail", "scene model", "load-bearing detail"],
        "uncertainties": ["A vivid detail may be beautiful while distracting from the scene's actual action, relation, or emotional center."],
        "near_concept_distinctions": ["Imagery helps a reader simulate experience; factual description reports supported properties of an observed or sourced subject."],
        "examples": ["Instead of saying the workshop was neglected, show one declared detail that carries the condition: rain tapped through a rusted seam into the empty tool tray."],
        "counterexamples": ["Adding color, scent, temperature, and texture to every object overloads the scene and may invent unsupported facts."],
        "scope_of_application": "Use declared invention freely inside an explicit fictional or imaginative frame. In factual, autobiographical, or research contexts, use only observed, supplied, attributed, or clearly hypothetical detail.",
        "explanation": "Concrete imagery works because it gives the mind objects, relations, movement, and sensory cues from which to construct a scene. A few selected details often produce a stronger model than a catalogue of adjectives.",
        "distinct_examples": ["To convey that a machine has stopped, the still belt and one cooling indicator can carry more scene information than repeatedly calling the room silent."],
        "analogies": ["Imagery supplies coordinates for an inner simulation; each useful detail places or changes something in that model."],
        "questions": ["Which detail lets the reader perceive the central condition instead of merely being told its label?"],
        "comparisons": ["Concrete detail shows a perceivable condition; abstract summary names the interpretation drawn from it."],
        "conversational_participation": "I would choose the unmoving belt as the load-bearing image. It makes the stopped process visible without piling decoration onto the whole room.",
        "correction_response": "If an image invents evidence or steals focus, remove it, restore the supported scene, and replace it only with declared fiction or a source-grounded detail.",
    },
    "figurative_mapping_with_limits": {
        "vocabulary": ["metaphor", "simile", "symbol", "target", "source image", "mapping limit"],
        "uncertainties": ["A figurative mapping may illuminate one relation while importing unintended emotional, moral, or causal associations."],
        "near_concept_distinctions": ["A metaphor asserts an imaginative identity for effect; a simile marks comparison; an analogy explains a shared structure; a symbol gathers meaning through context and recurrence."],
        "examples": ["Calling revision a lens adjustment can illuminate changing focus while leaving the underlying scene intact."],
        "counterexamples": ["Calling a social network a nervous system does not prove that it thinks, feels, or has biological neurons."],
        "scope_of_application": "Use figurative language for creative expression, explanation, humor, emotional precision, and pattern exploration. Keep factual claims and hypothesis confidence separately grounded.",
        "explanation": "Figurative language works by carrying a selected relationship from a familiar image into a new subject. Its power comes from the fit that is preserved, not from pretending the two things are identical in every respect.",
        "distinct_examples": ["A stalled conversation can be described as a door resting against its frame: not locked, but no longer moving without a new push."],
        "analogies": ["A metaphor is a bridge with a named load limit; it carries the intended relation, not every property on either shore."],
        "questions": ["What exact feature transfers, what associations come with it, and where should the comparison stop?"],
        "comparisons": ["Vividness increases felt availability; evidence increases justified confidence. One cannot substitute for the other."],
        "conversational_participation": "The lens metaphor fits the change in focus, but I would not extend it into a claim that the original view was false in every detail.",
        "correction_response": "If a metaphor implies an unsupported property, keep the useful relation, state or respect its limit, and replace the misleading image if the extra association cannot be contained.",
    },
    "dialogue_subtext_and_turn_motion": {
        "vocabulary": ["dialogue", "speaker", "subtext", "action beat", "interruption", "silence", "local goal"],
        "uncertainties": ["A spoken line can support several plausible implications, especially when a speaker's history or immediate goal remains unstated."],
        "near_concept_distinctions": ["Subtext is meaning implied by situation and delivery; hidden motive is a private cause that cannot be claimed about a real person without evidence."],
        "examples": ["A character says, You left the porch light on, while setting a packed bag by the door; the action changes what the ordinary sentence may imply."],
        "counterexamples": ["Explaining every feeling in dialogue leaves no work for context, gesture, pause, or the reader's inference."],
        "scope_of_application": "Use invented motives and subtext inside clearly fictional scenes. In real conversation analysis, preserve implications as interpretations and ask when the distinction matters.",
        "explanation": "Dialogue works because speakers act through words while carrying knowledge, relationships, goals, and restraint. What is said, avoided, interrupted, or accompanied by action can move the scene together.",
        "distinct_examples": ["One speaker asks whether the window is open; the other closes it without answering. The action resolves the practical request while leaving the relational tension available."],
        "analogies": ["Dialogue is a game played on two boards: the literal exchange and the changing relationship or goal beneath it."],
        "questions": ["What does each speaker know, want, say, avoid, and change during this turn?"],
        "comparisons": ["Exposition tells the reader a motive; subtext lets wording and situation support an interpretation without making it mechanically explicit."],
        "conversational_participation": "I would cut the explanatory line and let the packed bag carry the second meaning. The spoken sentence stays ordinary; the scene gives it weight.",
        "correction_response": "If dialogue assigns an unsupported private motive to a real person or loses track of the speaker, restore the explicit evidence and mark the implication as one possible reading.",
    },
    "viewpoint_scene_continuity": {
        "vocabulary": ["viewpoint", "narrative access", "scene state", "continuity", "callback", "perspective shift"],
        "uncertainties": ["A deliberate perspective change can resemble accidental head-hopping unless the transition and new access are made legible."],
        "near_concept_distinctions": ["Viewpoint controls narrative access; grammatical voice controls clause focus; neither automatically decides factual reliability."],
        "examples": ["From the mechanic's viewpoint, the reader may know the gauge is falling but not what is happening inside the sealed line until inspection."],
        "counterexamples": ["A character cannot react to a silent event in another room unless the narrative supplies a way for that information to reach them."],
        "scope_of_application": "Use viewpoint and continuity in fiction, narrative explanation, reflective accounts, and multi-scene writing. Clearly distinguish invented access, remembered experience, and verified record when the frame is not purely fictional.",
        "explanation": "Viewpoint works by creating a stable information boundary through which the reader encounters a changing scene. Continuity lets each new action inherit the people, objects, conditions, and unresolved threads already established.",
        "distinct_examples": ["If a cup is left cracked on the bench, a later callback can show the crack widening after vibration rather than reintroducing an intact cup."],
        "analogies": ["Viewpoint is a moving observation window; continuity is the ledger of what remains in the world as the window moves."],
        "questions": ["What can this viewpoint perceive now, what changed since the last scene, and which earlier detail has become relevant?"],
        "comparisons": ["A perspective shift deliberately changes access; a continuity error accidentally changes established scene state."],
        "conversational_participation": "I would keep the cause outside her knowledge for now. She can notice the falling gauge; the sealed-line failure becomes available only when the inspection reaches it.",
        "correction_response": "If the passage grants impossible knowledge or resets an established object, restore the last reliable scene state and revise only the dependent reactions or transition.",
    },
    "creative_revision_for_effect_without_imitation": {
        "vocabulary": ["intended effect", "craft choice", "revision", "transferable technique", "imitation", "original expression"],
        "uncertainties": ["A reader may experience an effect differently from the writer's intention, so revision should use evidence from the passage and feedback rather than assume control over response."],
        "near_concept_distinctions": ["Learning a technique extracts a general relationship; imitation reproduces recognizable source choices, phrasing, or persona."],
        "examples": ["If a suspense scene feels rushed, identify whether the missing support is spatial clarity, anticipation, viewpoint access, or sentence pacing before rewriting it."],
        "counterexamples": ["Adding archaic vocabulary after reading Shakespeare copies a surface marker without understanding dramatic structure, image, character pressure, or meter."],
        "scope_of_application": "Use revision to improve original creative work, critique bounded supplied passages, and study transferable techniques from attributed lawful sources. Do not reproduce whole copyrighted works or impersonate living authors.",
        "explanation": "Revision works when it connects a desired reader experience to the craft choice carrying that experience. Naming the mechanism makes the lesson transferable, correctable, and available to Selene's own Voice rather than trapping expression inside a borrowed style.",
        "distinct_examples": ["To make a farewell gentler, preserve the truth of departure while changing the pacing, concrete callback, and final image instead of adding generic reassurance."],
        "analogies": ["Revision is tuning a system for its intended output after tracing which component actually shapes that output."],
        "questions": ["What is this passage trying to make available, which choice creates that effect, and can the same mechanism be expressed more originally or clearly?"],
        "comparisons": ["Technique transfer preserves a functional relationship across new material; style imitation preserves another writer's recognizable surface."],
        "conversational_participation": "The passage does not need more ornament. It needs the viewpoint held steady and the final callback moved later so the emotional turn has somewhere to land.",
        "correction_response": "If a revision begins sounding like a source author or changes the passage's supported meaning, return to the intended effect and rebuild the technique in original language.",
    },
}
