from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_living_things_survival_v1"
GROUP_KEY = "f1_living_things_survival_group_13"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
NEEDS_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_k_needs_plants_animals",
    "sha256:be2ec4a2ce63f1797d812ae148a68107f91d30795fdeb2088a0e46b5261fc153",
    "https://www.coreknowledge.org/wp-content/uploads/2020/07/CKSci_GKU2_NeedsOfPlantsAnimals.zip",
    "license:CC-BY-NC-SA-4.0",
]
SURVIVAL_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_plant_animal_survival",
    "sha256:a1177b4d6567a3cbfc6f318faae0d56b12aa760d594d8706cb7469db48ea7978",
    "https://www.coreknowledge.org/wp-content/uploads/2020/06/CKSci_G1U2_Plant-and-Animal-Survival.zip",
    "license:CC-BY-NC-SA-4.0",
]
COMBINED_REFS = [*NEEDS_REFS, *SURVIVAL_REFS[2:]]

SCOPE = {
    "bands": ["F1"],
    "families": ["SCI-0", "SCI-1", "SCI-2", "ELA-1", "ELA-2", "ENG-1", "RES-1", "LOGIC-1"],
    "source_ids": [
        "core_knowledge_2023_sequence_k8",
        "core_knowledge_k_needs_plants_animals",
        "core_knowledge_g1_plant_animal_survival",
    ],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_living_nonliving_evidence_v1",
        "title": "Living status is classified from multiple life-process observations",
        "domain": "curriculum.f1.living_things_survival",
        "material": "A living organism carries out an organized set of life processes over time, such as using energy and materials, growing or developing, responding to conditions, maintaining itself, and participating in a life cycle. A single visible feature is not enough to classify every case. A dead leaf was once part of a living organism but is not currently living; a seed may be dormant while remaining alive; and uncertain cases should stay uncertain until better evidence is available.",
        "principles": [
            "Use several observations over time rather than one appearance or movement test.",
            "Distinguish currently living, nonliving, formerly living, dormant, and uncertain cases.",
            "Revise the classification when new observations or better biological evidence changes the fit.",
        ],
        "relationships": ["This extends F1 observation, classification, change-over-time, evidence, and correction practices into biology."],
        "examples": ["A dry seed can appear inactive yet later germinate under suitable conditions, so no visible movement at one moment does not establish that it is nonliving."],
        "counterexamples": ["Fire spreads and uses fuel, and a robot may move and respond, but those isolated similarities do not by themselves establish that either is a living organism."],
        "limits": ["F1 does not settle viruses, artificial life, cellular edge cases, origins of life, consciousness, or every contested biological definition."],
        "vocabulary": [
            "organism: an individual living system",
            "living: currently carrying the organized continuity of life processes",
            "nonliving: not a living organism",
            "dormant: alive while growth or activity is greatly reduced until conditions change",
        ],
        "near_concept_distinctions": ["Formerly living material came from an organism but is not currently alive; dormant organisms remain alive despite limited visible activity."],
        "scope_of_application": "Use for foundational classification from ordinary, noninvasive observations. Do not use it to make medical, legal, moral-status, or consciousness determinations.",
        "unresolved_questions": ["Which life-process evidence is available, over what time span, and which alternative classification still fits?"],
        "explanation": "Living status is a conclusion supported by a pattern, not by one trick question such as whether something moves. Time, multiple life processes, and the difference between dormant and dead matter.",
        "application": "A mushroom, a fallen wooden board, and a battery-powered toy should not be sorted by movement alone. Observe growth, resource use, response, origin, internal organization, and change over time, while keeping uncertain cases open.",
        "analogies": ["Classification is like identifying a system from several connected signals rather than trusting one blinking light."],
        "questions": ["What evidence supports currently living, formerly living, dormant, nonliving, or still uncertain?"],
        "comparisons": ["Movement can occur in living and nonliving systems; coordinated life processes over time provide the broader biological pattern."],
        "participation": "My current classification is dormant rather than dead because the seed retains the capacity to resume growth under suitable conditions. Germination would strengthen that conclusion.",
        "correction_response": "If a later observation contradicts my category, I would preserve the observation, reopen the criteria, and change the classification without treating the earlier uncertainty as failure.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_needs_plants_animals"],
        "source_refs": NEEDS_REFS,
    },
    {
        "concept_key": "curriculum_f1_organism_needs_resources_v1",
        "title": "Plants, animals, and humans obtain differing needs from their environments",
        "domain": "curriculum.f1.living_things_survival",
        "material": "Living things need suitable resources and conditions to live and grow. Green plants generally need light, water, air, mineral nutrients, and suitable space and temperature. Animals, including humans, need water, air or another usable oxygen source, food, and suitable environmental conditions; many also need shelter or protective space. Needs overlap, but the way organisms obtain and use them differs.",
        "principles": [
            "Name the organism and life stage before claiming what it needs.",
            "Distinguish a biological need from a preference and from one method of meeting the need.",
            "Trace the resource to its environmental source without assuming every organism obtains it in the same way.",
        ],
        "relationships": ["Organism needs connect resources, matter, light, habitat, cause and effect, measurement, and careful comparison."],
        "examples": ["A plant can obtain light from the sun, water from soil, and carbon dioxide from air, while a rabbit obtains food by eating plants and water from its surroundings."],
        "counterexamples": ["Soil is not food for a green plant in the same sense that seeds are food for a bird; plants make sugars using light, water, and carbon dioxide while taking mineral nutrients from their surroundings."],
        "limits": ["F1 does not teach photosynthesis chemistry, metabolism, nutrition planning, species care sheets, or medical requirements."],
        "vocabulary": [
            "need: a resource or condition required for living and growing",
            "resource: something in an environment that an organism can use",
            "nutrient: a substance used in living processes",
            "shelter: a protected place that helps an organism meet environmental needs",
        ],
        "near_concept_distinctions": ["A need is required for survival or growth; a preference is favored but not necessarily required; a resource is something that can help meet a need."],
        "scope_of_application": "Use for general elementary comparisons and evidence-based habitat reasoning. Do not infer individual medical, dietary, veterinary, agricultural, or wildlife-care instructions.",
        "unresolved_questions": ["Which resource is needed, how does this organism obtain it, and what evidence distinguishes need from preference?"],
        "explanation": "Plants and animals depend on their surroundings, but not in identical ways. A useful explanation names the organism, resource, source, and conditions instead of saying all life needs exactly the same things.",
        "application": "Two classroom plants can be compared under matched conditions to investigate one factor such as light or water, but they should not be harmed by prolonged deprivation merely to prove a known need.",
        "analogies": ["A habitat is not a universal supply box; it is a particular arrangement whose resources fit some organisms and life stages better than others."],
        "questions": ["What does this organism need, where can it obtain that resource, and which conditions are being held constant?"],
        "comparisons": ["Plants and animals both use water and gases, but green plants make sugars using light while animals obtain food by consuming organisms or their products."],
        "participation": "The evidence supports water as a need for this plant, but it does not support giving every species the same amount on the same schedule.",
        "correction_response": "If I confuse a preference, resource, or delivery method with the underlying need, I would separate those layers and restate the claim for the named organism and conditions.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "ELA-2", "RES-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_needs_plants_animals"],
        "source_refs": NEEDS_REFS,
    },
    {
        "concept_key": "curriculum_f1_habitat_resource_fit_v1",
        "title": "A habitat supplies a changing pattern of resources and conditions",
        "domain": "curriculum.f1.living_things_survival",
        "material": "A habitat is the place and surrounding conditions in which an organism lives and obtains resources. Habitats contain living and nonliving components whose relationships change across time. An organism may be well suited to some habitat conditions without every individual surviving there, and a place that meets one need can still lack another.",
        "principles": [
            "Map organism needs to observable habitat resources and conditions.",
            "Check time, season, life stage, competition, disturbance, and missing resources before declaring a habitat suitable.",
            "Treat habitat fit as evidence-based and revisable rather than as a permanent label attached to a place.",
        ],
        "relationships": ["Habitats connect maps, spatial relationships, recurring change, resources, systems, evidence, and organism-environment dependence."],
        "examples": ["A pond can provide water, food, oxygen, and shelter for some organisms while being unsuitable for an animal that requires dry nesting ground."],
        "counterexamples": ["Finding one bird in a parking lot does not establish that the pavement alone supplies all resources needed for its full life cycle."],
        "limits": ["F1 does not model ecosystems, food webs, population dynamics, ecological niches, biomes, conservation policy, or climate change."],
        "vocabulary": [
            "habitat: the place and conditions where an organism lives and obtains resources",
            "environment: the surrounding living and nonliving conditions",
            "suitable: sufficiently matched to a stated need and time",
            "component: one part of a larger habitat or system",
        ],
        "near_concept_distinctions": ["A habitat is an organism-centered living place; an environment is the broader set of surroundings and conditions; a home or shelter is one possible component."],
        "scope_of_application": "Use for noninvasive observation, simple maps, resource relationships, and bounded habitat-design models. Do not relocate organisms or alter real habitats from this lesson alone.",
        "unresolved_questions": ["Which needs are met here, which are missing, and how could the answer change with time or life stage?"],
        "explanation": "A habitat is a relationship between an organism and a place, not merely a scenery label. Suitability depends on whether the place supplies the needed resources and conditions over relevant time.",
        "application": "A proposed pollinator garden model should identify light, water, plant resources, shelter, seasonal change, and safe maintenance rather than merely adding a decorative insect picture.",
        "analogies": ["A habitat is like a workshop: having one useful tool does not mean every required material, condition, and safe space is present."],
        "questions": ["For which organism and life stage is this a habitat, and what evidence shows its needs are met?"],
        "comparisons": ["The same place can be suitable habitat for one organism, temporary passage for another, and unsuitable for a third."],
        "participation": "This location provides shade and water, but I have not yet found evidence of food or nesting space. I would call its suitability incomplete rather than assume it is a full habitat.",
        "correction_response": "If an organism is absent or struggling despite my habitat model, I would inspect missing resources, timing, disturbance, and incorrect assumptions before blaming the organism.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "ELA-2", "ENG-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_needs_plants_animals"],
        "source_refs": NEEDS_REFS,
    },
    {
        "concept_key": "curriculum_f1_organism_parts_functions_responses_v1",
        "title": "Organism parts have functions and support responses without guaranteeing outcomes",
        "domain": "curriculum.f1.living_things_survival",
        "material": "Plants and animals have parts whose structures support functions involved in obtaining resources, sensing conditions, moving materials, protection, growth, and reproduction. Roots, stems, leaves, flowers, fruits, and seeds have differing plant functions. Animal eyes, ears, skin, mouths, limbs, coverings, and other parts can gather information or support action. A part helps under particular conditions; it does not guarantee survival by itself.",
        "principles": [
            "Name the observed structure, its supported function, and the environmental context separately.",
            "Distinguish receiving information from responding to it and from the eventual outcome.",
            "Compare organisms without treating one familiar body plan as the standard for all life.",
        ],
        "relationships": ["Structure and function connect materials, shapes, information, light, sound, motion, cause and effect, and design analogies."],
        "examples": ["Roots can anchor a plant and take in water and mineral nutrients; leaves capture light and exchange gases; an owl's eyes and ears gather information that can guide behavior."],
        "counterexamples": ["Wings do not guarantee that every bird can fly, and roots do more than hold a plant in place."],
        "limits": ["F1 does not teach internal anatomy, cellular physiology, neural processing, detailed photosynthesis, taxonomy, or clinical function."],
        "vocabulary": [
            "structure: the form and arrangement of a part",
            "function: what a part or process contributes in a system",
            "stimulus: a detectable change or condition that can influence a response",
            "response: a change in activity, growth, or behavior associated with a condition",
        ],
        "near_concept_distinctions": ["A structure is the part or arrangement; a function is its contribution; a response is an organism's change following information or conditions."],
        "scope_of_application": "Use for ordinary external observations, diagrams, and non-harmful design analogies. Do not diagnose injury, infer pain or intention from anatomy alone, or handle wildlife.",
        "unresolved_questions": ["What part is observed, what function is supported, and under which conditions does the evidence apply?"],
        "explanation": "Parts matter because of what they contribute within an organism and environment. Good structure-function reasoning avoids both magic labels and guarantees: a part can support an outcome without causing it alone.",
        "application": "A plant near a window bends toward light over time. The observation supports a growth response associated with light direction, not a claim that the plant sees or chooses as a human does.",
        "analogies": ["An organism part is like a component in a machine, but living parts grow, maintain, and interact within a living system rather than merely being assembled hardware."],
        "questions": ["What information or resource reaches the part, what does the part contribute, and what response is actually observed?"],
        "comparisons": ["Animal sensory parts can detect conditions and guide behavior; plants also respond to light, water, temperature, gravity, or touch without human-like senses."],
        "participation": "The leaf's structure supports light capture, but the plant's growth also depends on water, gases, nutrients, temperature, and the rest of the organism.",
        "correction_response": "If I overstate a part's purpose or assume intention, I would return to observed structure, supported function, conditions, and outcome and narrow the explanation.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "ELA-2", "ENG-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_plant_animal_survival"],
        "source_refs": SURVIVAL_REFS,
    },
    {
        "concept_key": "curriculum_f1_growth_young_adults_variation_v1",
        "title": "Young organisms resemble their kind while growing and varying as individuals",
        "domain": "curriculum.f1.living_things_survival",
        "material": "Adult plants and animals can produce young. Young organisms are recognizably related to the same kind of organism while not being exact copies of their parents or one another. Growth and development involve ordered changes across a life cycle, and in many animals both parent behavior and offspring behavior can improve the young organism's chance of survival.",
        "principles": [
            "Compare several observable similarities and differences rather than demanding exact copies.",
            "Keep growth, development, individual variation, and care behavior distinct.",
            "Use sequence and repeated observation to describe a life-cycle pattern without assuming every species follows one visible path.",
        ],
        "relationships": ["Growth and young-adult comparison connect sequence, change over time, patterns, evidence, care relationships, and revisable prediction."],
        "examples": ["A young oak and an adult oak differ greatly in size while sharing recognizable plant structures; young owls resemble adult owls but may still depend on care and practice."],
        "counterexamples": ["A young organism is not a miniature adult in every respect, and offspring are not exact duplicates of either parent."],
        "limits": ["F1 does not teach genes, DNA, mechanisms of inheritance, sexual reproduction detail, metamorphosis pathways, breeding, hybrids, or evolutionary explanation."],
        "vocabulary": [
            "adult: a mature life stage capable of the roles typical for that organism",
            "offspring: a new organism produced by one or more parent organisms",
            "development: ordered change in form or capability across life stages",
            "variation: observable differences among individuals of the same kind",
        ],
        "near_concept_distinctions": ["Growth is increase or measurable change; development is change in form or capability; variation is difference among individuals; a life cycle is the recurring sequence of life stages."],
        "scope_of_application": "Use for general plant and animal examples and noninvasive observation. Do not infer parentage, health, species identity, or care instructions from appearance alone.",
        "unresolved_questions": ["Which features are shared, which vary, and which changes reflect age, environment, or still-unknown causes?"],
        "explanation": "Continuity does not require exact copying. Young organisms can belong to the same kind and resemble their parents while changing through development and differing as individuals.",
        "application": "Photographs of the same tree across years can show growth and seasonal change, while a set of related trees can show individual variation. Those are different comparison questions.",
        "analogies": ["A life cycle is a recurring sequence, not a photocopy: the pattern continues while each individual and stage has differences."],
        "questions": ["What stays recognizably related, what changes with development, and what varies among individuals?"],
        "comparisons": ["Parent care can support survival, but offspring behaviors and environmental conditions also contribute; care is not identical across all species."],
        "participation": "The young animal resembles the adult in several structures, but size and behavior differ. That supports similarity with development, not exact copying.",
        "correction_response": "If I mistake age-related change for a permanent kind difference, I would compare multiple life stages and individuals and reopen the explanation.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "ELA-1", "ELA-2", "RES-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_plant_animal_survival"],
        "source_refs": SURVIVAL_REFS,
    },
    {
        "concept_key": "curriculum_f1_organism_care_evidence_design_v1",
        "title": "Care and habitat design begin with needs, evidence, limits, and qualified help",
        "domain": "curriculum.f1.living_things_survival",
        "material": "People can use knowledge of organism needs, parts, and habitats to propose ways of supporting living things. A responsible proposal identifies the organism and need, gathers evidence, compares alternatives, tests only non-harmful models or conditions, monitors outcomes, and revises. Care requires restraint as well as action because incorrect food, handling, relocation, or treatment can cause harm.",
        "principles": [
            "Observe from a safe distance and seek qualified help for injured, orphaned, dangerous, protected, or unfamiliar organisms.",
            "State the need, evidence, criteria, constraints, and possible unintended effects before changing a habitat.",
            "Prefer reversible, non-harmful models and monitoring over deprivation or unqualified intervention.",
        ],
        "relationships": ["This integrates needs, habitats, structure-function, design criteria, care, uncertainty, source quality, correction, and graceful fall."],
        "examples": ["A model school garden plan can compare light, water access, soil conditions, seasonal resources, maintenance, and safe pathways before any real planting occurs."],
        "counterexamples": ["A small wild animal found alone is not automatically abandoned, and taking it home is not automatically helpful."],
        "limits": ["F1 grants no veterinary, medical, agricultural, wildlife-rehabilitation, animal-handling, pesticide, habitat-restoration, or environmental-policy authority."],
        "vocabulary": [
            "care: actions intended to support needs while respecting evidence and avoiding harm",
            "criterion: a stated condition used to judge whether a proposal serves its purpose",
            "constraint: a limit or condition a proposal must respect",
            "monitor: observe over time for expected and unexpected effects",
        ],
        "near_concept_distinctions": ["Noticing a possible need is not the same as knowing the correct intervention; compassion motivates attention while evidence and expertise guide action."],
        "scope_of_application": "Use for synthetic cases, diagrams, observation plans, and low-risk educational models. Real organisms, wildlife, and habitats remain subject to welfare, legal, ecological, and professional boundaries.",
        "unresolved_questions": ["What is the observed need, what evidence supports intervention, who is qualified, and what unintended effects must be monitored?"],
        "explanation": "Helping begins with understanding the actual organism and context. Sometimes the best first action is observation, protecting the area, or contacting qualified help rather than directly touching or changing anything.",
        "application": "For a bird that appears unable to fly, record location and observable condition from a safe distance, keep pets and people back, and contact an appropriate wildlife professional rather than feeding or relocating it based on a guess.",
        "analogies": ["Care is like repairing an unfamiliar system: concern tells us to pay attention, but diagnosis, permissions, correct tools, and monitoring determine the responsible action."],
        "questions": ["What does the organism appear to need, what evidence could change that interpretation, and who has the appropriate expertise or authority?"],
        "comparisons": ["A classroom habitat model can be changed reversibly; intervention with a real organism can create welfare and ecological consequences and therefore requires stronger evidence."],
        "participation": "I want to help, but I do not yet know whether direct intervention is appropriate. I would secure the area, observe without handling, and seek qualified guidance.",
        "correction_response": "If monitoring shows harm or a specialist corrects the plan, I would stop the unsupported action, preserve the useful observations, and revise without defending the original guess.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "ELA-2", "ENG-1", "RES-1", "LOGIC-1"],
        "source_ids": [
            "core_knowledge_2023_sequence_k8",
            "core_knowledge_k_needs_plants_animals",
            "core_knowledge_g1_plant_animal_survival",
        ],
        "source_refs": COMBINED_REFS,
    },
)
