from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_weather_sky_cycles_v1"
GROUP_KEY = "f1_weather_sky_cycles_group_14"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
WEATHER_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_k_weather_patterns",
    "sha256:f32efcbd2434254fe4da9135335a7115128e3e59a14b8dc2cf112fe0dbe04750",
    "https://www.coreknowledge.org/wp-content/uploads/2020/07/CKSci_GKU4_Weather-Patterns_TG.pdf",
    "license:CC-BY-NC-SA-4.0",
]
SKY_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_sun_moon_stars",
    "sha256:065b5d26b21b9c3c534f3a3da7d7bd5cda3b65423f704f4900d7ea7a58207620",
    "https://www.coreknowledge.org/wp-content/uploads/2020/07/CKSci_G1U1_Sun-Moon-and-Stars.zip",
    "license:CC-BY-NC-SA-4.0",
]
COMBINED_REFS = [*WEATHER_REFS, *SKY_REFS[2:]]

SCOPE = {
    "bands": ["F1"],
    "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-2", "ELA-1", "ELA-2", "RES-1", "LOGIC-1"],
    "source_ids": [
        "core_knowledge_2023_sequence_k8",
        "core_knowledge_k_weather_patterns",
        "core_knowledge_g1_sun_moon_stars",
    ],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_weather_conditions_climate_distinction_v1",
        "title": "Weather describes atmospheric conditions at a named place and time",
        "domain": "curriculum.f1.weather_sky_cycles",
        "material": "Weather describes conditions in the air and sky at a particular place and time, including temperature, wind, cloud cover, and precipitation. It can change within hours or days. Climate describes longer-term patterns across many observations and belongs to later detailed study. Words such as nice, gloomy, or bad may describe a person's experience, but they are not weather measurements.",
        "principles": [
            "Name the place, time, and observed condition before making a weather claim.",
            "Separate measurement from a person's comfort, plans, or mood.",
            "Do not infer a long-term climate pattern from one day or a short run of weather.",
        ],
        "relationships": ["Weather observation extends F1 measurement, comparison, classification, evidence, time, and place reasoning."],
        "examples": ["At 3 p.m. near the school, the thermometer reads 18 degrees Celsius, the sky is cloudy, and light rain is falling."],
        "counterexamples": ["Calling a rainy day terrible does not measure the rain, and one unusually cold morning does not establish the region's climate."],
        "limits": ["F1 does not teach climate statistics, climate change, atmospheric chemistry, pressure systems, or operational meteorology."],
        "vocabulary": [
            "weather: atmospheric conditions at a particular place and time",
            "temperature: a measure related to how hot or cold something is",
            "precipitation: water that falls from clouds, such as rain, snow, sleet, or hail",
            "climate: longer-term patterns of weather for a region",
        ],
        "near_concept_distinctions": ["Weather concerns comparatively short-term conditions; climate concerns patterns supported by many observations over much longer periods."],
        "scope_of_application": "Use for ordinary weather description and for separating observations from reactions. Treat climate conclusions and safety decisions as outside this foundational lesson.",
        "unresolved_questions": ["What place and time does the report describe, and which parts are measured, observed, or interpreted?"],
        "explanation": "Weather is a time-and-place description, not a verdict about whether the day is good. A useful report names observable conditions and keeps long-term climate claims separate.",
        "application": "If two people disagree about whether the day is pleasant, they can still agree on a measured temperature, steady rain, and strong wind while keeping their preferences distinct.",
        "analogies": ["A weather observation is a snapshot; climate is a pattern assembled from a much longer album of observations."],
        "questions": ["Which condition was observed, where, when, and with what evidence?"],
        "comparisons": ["Cloudy is an observable sky condition; gloomy is an interpretation that may differ between observers."],
        "participation": "It is cool and raining here now. Whether that feels refreshing or unpleasant depends on the person and purpose, so I would not hide the observation inside the preference.",
        "correction_response": "If I turn one event into a climate claim or a mood word into a measurement, I would restore the place, time, evidence, and timescale and narrow the conclusion.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "ELA-1", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_weather_patterns"],
        "source_refs": WEATHER_REFS,
    },
    {
        "concept_key": "curriculum_f1_weather_measurement_records_v1",
        "title": "Weather records combine named observations with consistent measures",
        "domain": "curriculum.f1.weather_sky_cycles",
        "material": "A weather record can combine temperature, wind direction or relative strength, cloud cover, and the kind and amount of precipitation. Repeated observations are most comparable when location, time, units, instruments, and categories are recorded consistently. Measurements are evidence about conditions; they are not complete explanations of why the conditions occurred.",
        "principles": [
            "Record location, time, unit, instrument, and observation category when they affect comparison.",
            "Use the same method across observations when looking for change or a recurring pattern.",
            "Preserve uncertainty, missing entries, and instrument limits instead of filling them with invented values.",
        ],
        "relationships": ["Weather records connect tables, units, repeated measurement, comparison, graphs, patterns, and source provenance."],
        "examples": ["Recording air temperature at the same shaded location each morning makes the week easier to compare than moving the thermometer between sun and shade."],
        "counterexamples": ["A warmer reading in direct sunlight and a cooler reading in shade do not by themselves prove that the entire town warmed and cooled by that amount."],
        "limits": ["F1 uses ordinary observations and relative comparisons; calibration, radar, pressure, humidity, numerical forecasting, and instrument certification remain later topics."],
        "vocabulary": [
            "observation: information noticed or measured under stated conditions",
            "record: a preserved observation with enough context to interpret it",
            "instrument: a tool used to observe or measure",
            "cloud cover: how much of the visible sky is covered by clouds",
        ],
        "near_concept_distinctions": ["An observation is one piece of evidence; a record preserves it; a pattern is a relationship supported across multiple records."],
        "scope_of_application": "Use for simple local weather logs and comparisons. Do not treat a classroom instrument or incomplete record as an official warning system.",
        "unresolved_questions": ["Were the observations made in comparable conditions, and what measurement uncertainty or missing context remains?"],
        "explanation": "Weather data become useful when each value keeps its context. A number without its unit, place, time, or method can look precise while being difficult to compare correctly.",
        "application": "To compare morning temperatures across five days, keep the observation time and shaded location consistent, record the unit, and mark a missed day as missing rather than guessing it.",
        "analogies": ["A measurement without context is like a labeled point without axes: it exists, but its relationship to the rest is unclear."],
        "questions": ["What was measured, with which unit and tool, where and when, and what might limit the comparison?"],
        "comparisons": ["A thermometer reading measures temperature; a rain gauge measures collected precipitation; neither alone describes every part of the weather."],
        "participation": "The temperature rose across these matched morning observations, but Wednesday is missing. I can describe the recorded trend without inventing the absent value.",
        "correction_response": "If two records used different locations, times, units, or methods, I would identify the mismatch and avoid claiming that their difference is entirely weather change.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-2", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_weather_patterns"],
        "source_refs": WEATHER_REFS,
    },
    {
        "concept_key": "curriculum_f1_seasonal_patterns_regions_hemispheres_v1",
        "title": "Seasonal patterns recur while differing by region and hemisphere",
        "domain": "curriculum.f1.weather_sky_cycles",
        "material": "A season is a recurring part of the year associated with patterns in daylight and often in weather and living systems. Seasonal patterns differ by place: the same named season does not guarantee the same temperature or precipitation everywhere. The Northern and Southern Hemispheres experience opposite seasonal timing, so a month alone does not name one universal season for Earth.",
        "principles": [
            "Name the location and hemisphere before generalizing a seasonal pattern.",
            "Use many observations across years to support what is typical, while allowing unusual events.",
            "Distinguish a recurring seasonal tendency from a guaranteed daily condition.",
        ],
        "relationships": ["Seasons connect recurring patterns, calendars, daylight, geography, living-system change, evidence, and bounded prediction."],
        "examples": ["December is usually associated with winter in North Carolina and summer in much of Australia, although local conditions vary within both places."],
        "counterexamples": ["A warm winter afternoon does not make the season summer, and summer does not guarantee that every day is hot or dry."],
        "limits": ["F1 does not fully explain axial tilt, Earth orbit, regional climate systems, monsoons, polar cycles, or climate change; distance from the Sun must not be substituted as a false simple cause of the seasons."],
        "vocabulary": [
            "season: a recurring portion of the year associated with patterns in daylight and environmental conditions",
            "hemisphere: one half of Earth, commonly described as north or south of the equator",
            "typical: common in a stated set of observations without being guaranteed",
            "recurring: happening again in a recognizable pattern",
        ],
        "near_concept_distinctions": ["A season is a recurring annual interval; seasonal weather is what is typical during it; today's weather is one event within it."],
        "scope_of_application": "Use for elementary place-aware comparisons of daylight and seasonal observations. Hold causal orbital explanations for later source-backed teaching.",
        "unresolved_questions": ["Which location, hemisphere, years, and observations support this seasonal statement?"],
        "explanation": "Seasons are recurring patterns, not identical weather packages delivered everywhere. Location and hemisphere matter, and typical conditions still allow exceptions.",
        "application": "A travel comparison for January should not assume that clothing suitable for North Carolina also fits Argentina; check the place, hemisphere, and current forecast.",
        "analogies": ["A season is like a recurring chapter in an annual cycle: the chapter returns, but each edition can contain different daily details."],
        "questions": ["Where is this seasonal claim meant to apply, and is it a tendency or a guarantee?"],
        "comparisons": ["Seasonal timing is opposite between hemispheres, while local weather variation can occur within the same hemisphere and season."],
        "participation": "January suggests winter for this Northern Hemisphere location, but that gives only a seasonal expectation. I would use current local evidence for today's conditions.",
        "correction_response": "If I universalize one region's seasons or treat a typical pattern as certain, I would name the location and timescale and revise the claim.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-2", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_weather_patterns", "core_knowledge_g1_sun_moon_stars"],
        "source_refs": COMBINED_REFS,
    },
    {
        "concept_key": "curriculum_f1_earth_rotation_day_night_v1",
        "title": "Earth's rotation produces the local cycle of day and night",
        "domain": "curriculum.f1.weather_sky_cycles",
        "material": "The Sun lights one side of Earth at a time. Earth rotates, so a location turns toward the Sun and later away from it, producing a repeating local cycle of daylight and darkness over about twenty-four hours. From the ground, the Sun appears to cross the sky, but apparent motion describes what an observer sees and is not the same as claiming that the Sun circles Earth each day.",
        "principles": [
            "Keep the observer's apparent view separate from the physical model used to explain it.",
            "Use a globe-and-light model to represent illumination and rotation while naming what the model leaves out.",
            "Recognize that day at one location can coincide with night elsewhere on Earth.",
        ],
        "relationships": ["Day and night connect light, shadows, rotation, models, viewpoint, time zones, recurring patterns, and correction."],
        "examples": ["As a marked point on a rotating globe turns into the lamp's light it models sunrise and day; as it turns away it models sunset and night."],
        "counterexamples": ["The Sun's apparent daily path does not establish that the Sun physically travels around a stationary Earth once each day."],
        "limits": ["The model is not to scale and F1 does not calculate angular speed, orbital motion, time zones, seasons, eclipses, or relativity."],
        "vocabulary": [
            "rotate: to turn around an axis",
            "axis: an imagined line around which an object rotates",
            "daylight: the interval when a location receives sunlight",
            "apparent motion: movement as it seems from an observer's viewpoint",
        ],
        "near_concept_distinctions": ["Rotation is turning around an axis; revolution is travel around another body; apparent daily motion is the sky pattern seen from Earth's rotating surface."],
        "scope_of_application": "Use for a foundational Earth-Sun model of local day and night. Do not extend the model into unsupported orbital or navigation calculations.",
        "unresolved_questions": ["What does the observer see, and what motion does the explanatory model assign to Earth?"],
        "explanation": "Day and night follow from which part of rotating Earth faces the Sun. Our rotating viewpoint makes the Sun seem to move across the sky even though that appearance is not the whole physical explanation.",
        "application": "If it is noon in one location, a globe model can show why another location on the opposite side of Earth may be in darkness without imagining that the Sun switched off.",
        "analogies": ["Standing on a rotating platform can make a fixed room seem to sweep past; viewpoint changes what motion appears to belong to."],
        "questions": ["Which side is illuminated, how is Earth rotating, and which motion is observed rather than physically assigned?"],
        "comparisons": ["Earth's rotation explains the daily light-dark cycle; Earth's revolution around the Sun is a different motion taught more fully later."],
        "participation": "The Sun appears to rise and cross our sky, while the day-night model explains that recurring view through Earth's rotation. I would keep both the observation and the explanation explicit.",
        "correction_response": "If I confuse apparent motion with the explanatory motion, I would name the observer's viewpoint, rotate the model, and revise the claim.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-2", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_sun_moon_stars"],
        "source_refs": SKY_REFS,
    },
    {
        "concept_key": "curriculum_f1_sun_moon_star_observable_patterns_v1",
        "title": "Sun, Moon, and star observations reveal recurring apparent patterns",
        "domain": "curriculum.f1.weather_sky_cycles",
        "material": "From Earth, the Sun, Moon, stars, and familiar star patterns appear in recurring positions and paths over time. The visible portion of the Moon changes in a repeating sequence of phases; the Moon is not changing its physical shape. A constellation is an apparent pattern identified from Earth's viewpoint, not proof that its stars are close together in space. Safe sky observation never requires looking directly at the Sun or through magnifying optics.",
        "principles": [
            "Record date, time, location, direction, and viewing conditions when comparing sky observations.",
            "Distinguish an object's appearance from a claim that its physical shape or arrangement changed.",
            "Never look directly at the Sun or use binoculars, telescopes, lenses, or cameras to improvise solar viewing.",
        ],
        "relationships": ["Sky patterns connect observation, direction, time, shape, light, viewpoint, sequences, models, and safe evidence gathering."],
        "examples": ["Moon observations made on clear evenings across several weeks can show a repeating phase sequence even when clouds create gaps in the record."],
        "counterexamples": ["A crescent Moon is not a Moon that has physically lost most of its sphere, and two stars forming a line in the sky need not be neighbors in three-dimensional space."],
        "limits": ["F1 does not teach phase geometry in full, star distances, stellar evolution, orbital calculations, telescope operation, eclipses, astrology, astrophysics, or cosmology."],
        "vocabulary": [
            "phase: a recurring appearance of the Moon's illuminated portion from Earth",
            "constellation: a named apparent pattern of stars seen from Earth",
            "position: a location described relative to a reference",
            "visible: able to be seen under the present conditions",
        ],
        "near_concept_distinctions": ["A phase is a change in visible illumination, not a change in the Moon's physical shape; a constellation is an apparent pattern, not necessarily a physical cluster."],
        "scope_of_application": "Use for unaided, indirect, or professionally prepared safe observations and elementary pattern records. Do not provide improvised solar-viewing instructions.",
        "unresolved_questions": ["Is the observed difference due to a recurring sky pattern, viewpoint, time, cloud cover, or missing observations?"],
        "explanation": "Repeated sky observations reveal order within apparent change. Good explanations preserve viewpoint and time, and they do not turn an appearance into an unsupported claim about physical shape or distance.",
        "application": "A missing Moon entry on a cloudy night should remain missing; nearby dated observations may support a bounded phase prediction without pretending the Moon was directly seen.",
        "analogies": ["A lit ball can show different bright shapes as viewpoint changes even though the ball itself remains whole."],
        "questions": ["What was visible, from where and when, and are we describing appearance or physical structure?"],
        "comparisons": ["Moon phases concern changing visible illumination; constellations concern apparent positional patterns among stars."],
        "participation": "The Moon appears crescent-shaped tonight, but I would say its visible illuminated portion changed rather than claim that the Moon itself became a crescent object.",
        "correction_response": "If I mistake appearance for physical change or ignore a safety boundary, I would stop the proposed observation, restore the viewpoint distinction, and use a safe source or method.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-2", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_sun_moon_stars"],
        "source_refs": SKY_REFS,
    },
    {
        "concept_key": "curriculum_f1_recurring_patterns_bounded_prediction_v1",
        "title": "Recurring evidence supports bounded predictions rather than guarantees",
        "domain": "curriculum.f1.weather_sky_cycles",
        "material": "Repeated observations can support predictions about what is likely or when a recurring event may occur. A prediction states the evidence, scope, uncertainty, and what could change it. Sky cycles are often highly regular, while weather forecasts remain probabilistic and can change as new measurements arrive. Severe-weather warnings and protective instructions must come from current qualified local authorities, not from this lesson alone.",
        "principles": [
            "Match prediction confidence to the regularity, quantity, quality, and relevance of the evidence.",
            "State what is predicted, for which place and time, and what new evidence would update it.",
            "For severe weather, defer operational decisions to current official warnings and local emergency guidance.",
        ],
        "relationships": ["Prediction integrates patterns, records, evidence quality, uncertainty, confidence separation, correction, and safe action."],
        "examples": ["A week of observations may support a tentative local weather pattern, while sunrise records across the year support a more regular daylight pattern; neither evidence set should be described more strongly than it warrants."],
        "counterexamples": ["Seeing rain after dark on three evenings does not establish that it always rains at night, and an old forecast is not a current warning."],
        "limits": ["This lesson does not issue forecasts, alerts, evacuation decisions, storm tracking, navigation, agricultural guidance, or safety-critical predictions."],
        "vocabulary": [
            "prediction: a source-bounded statement about a future observation or outcome",
            "forecast: a prediction based on current observations and a model",
            "probability: a way to represent how likely an outcome is",
            "warning: an authoritative notice of a possible or present hazard requiring attention",
        ],
        "near_concept_distinctions": ["A pattern describes a relationship in observations; a prediction applies that relationship forward; a warning communicates hazard information and possible action."],
        "scope_of_application": "Use for elementary, non-safety-critical predictions and for explaining why confidence differs. Current hazards require official local sources and human judgment.",
        "unresolved_questions": ["How regular is the pattern, what evidence could break it, and does the situation require a current authoritative source?"],
        "explanation": "Patterns make prediction possible, but they do not erase uncertainty. The responsible answer says how far the evidence reaches and reopens when new observations no longer fit.",
        "application": "If a weather forecast changes after new radar data arrive, updating the answer is a strength of evidence-based prediction rather than a failure to remain consistent.",
        "analogies": ["A prediction is a bridge built only as far as the evidence supports; stronger recurring structure allows a longer span, but no label makes weak evidence stronger."],
        "questions": ["What recurring evidence supports this prediction, how confident should it be, and what would change it?"],
        "comparisons": ["A forecast estimates future conditions; an observation records present or past conditions; an official warning adds current hazard authority that a lesson does not possess."],
        "participation": "The records support a likely pattern, not a guarantee. For a severe-weather decision I would check the current official local warning rather than extrapolate from this lesson.",
        "correction_response": "If new evidence disagrees with the prediction, I would preserve the earlier basis, update the model or scope, and revise the answer without treating revision as personal failure.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-2", "ELA-1", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_weather_patterns", "core_knowledge_g1_sun_moon_stars"],
        "source_refs": COMBINED_REFS,
    },
)
