from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_equal_groups_data_money_v1"
GROUP_KEY = "f1_equal_groups_data_money_group_5"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
EQUAL_GROUP_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g2_math_unit8",
    "sha256:029b3123304c1c15676d647fe584700b9171a4c6f62d2070e5aed92f7deb3fd4",
    "https://www.coreknowledge.org/wp-content/uploads/2023/08/CKMath_G2U8_EqualGroups_Unit_Materials_W2.zip",
]
DATA_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g2_math_unit1",
    "sha256:eae00a4777672b66368780c4ba753c09eff5a18a29afd9bf5cbd55ed915457f7",
    "https://www.coreknowledge.org/wp-content/uploads/2023/08/CKMath_G2U1_AddingSubtractingAndWorkingWithData_Unit_Material_W2.zip",
]
MONEY_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g2_math_unit6",
    "sha256:b74bb1b3b181badb75bd43cd624362b9c8862a6979189e7654cabc9f6d57de19",
    "https://www.coreknowledge.org/wp-content/uploads/2023/08/CKMath_G2U6_GeometryTimeAndMoney_Unit_Materials_W2.zip",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["MATH-1", "MATH-2", "ELA-1", "LOGIC-1", "LIFE-1"],
    "source_ids": [
        "core_knowledge_2023_sequence_k8",
        "core_knowledge_g2_math_unit1",
        "core_knowledge_g2_math_unit6",
        "core_knowledge_g2_math_unit8",
    ],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_equal_groups_repeated_addition_v1",
        "title": "Equal groups connect repeated addition to multiplication",
        "domain": "curriculum.f1.equal_groups",
        "material": "Equal groups contain the same number of items in each group. Their total can be reconstructed by adding the equal group size once for every group, providing a conceptual foundation for multiplication.",
        "principles": [
            "Both the number of groups and the number in each group are needed to determine the total.",
            "Repeated addition represents equal groups only when the addends are equal.",
            "Multiplication later provides a compact representation of this equal-groups relationship rather than changing the quantity.",
        ],
        "relationships": ["Equal groups build on counting, addition, equality, and part-whole reasoning and lead toward multiplication and division."],
        "examples": ["Four groups containing three counters each have a total represented by 3 + 3 + 3 + 3 = 12."],
        "counterexamples": ["Groups of 2, 3, and 4 are three groups, but they are not three equal groups and cannot be represented by one repeated equal addend without changing the situation."],
        "limits": ["This lesson establishes the relationship among groups, group size, and total; it does not establish multiplication-fact fluency or every kind of multiplicative comparison."],
        "vocabulary": [
            "equal groups: groups containing the same quantity in each group",
            "group size: the number of items in one group",
            "repeated addition: adding the same quantity more than once",
            "total: the complete quantity across all groups",
        ],
        "near_concept_distinctions": ["Equal groups concern equal group size; an equal total alone does not show that two arrangements use the same grouping."],
        "scope_of_application": "Use when a bounded collection is explicitly arranged into equally sized groups. Name the number of groups, group size, and total rather than inferring a grouping from the total alone.",
        "unresolved_questions": ["Are both the group count and group size known, and are the groups actually equal?"],
        "explanation": "The repeated-addition form works because each group contributes the same amount. Counting how many equal contributions there are preserves both the arrangement and the total, which is why this becomes a foundation for multiplication.",
        "application": "Five storage bins each containing two labeled parts hold ten parts in all, represented as 2 + 2 + 2 + 2 + 2.",
        "analogy": ["Equal groups are like identical rows in a table: each row contributes the same number of entries to the total."],
        "questions": ["How many groups are there, how many are in each group, and how does the repeated addition reconstruct the total?"],
        "comparisons": ["Ordinary addition can combine unequal quantities; equal-group multiplication begins from repeated equal quantities."],
        "participation": "There are four equal groups of three, so I can reconstruct the total as four copies of three: 3 + 3 + 3 + 3 = 12.",
        "correction_response": "If the groups are unequal or I reverse what the numbers describe, I would relabel the group count and group size, recount, and rebuild the addition from the actual arrangement.",
        "families": ["MATH-1", "MATH-2", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g2_math_unit8"],
        "source_refs": EQUAL_GROUP_REFS,
    },
    {
        "concept_key": "curriculum_f1_equal_sharing_grouping_v1",
        "title": "Equal sharing and grouping ask different unknowns",
        "domain": "curriculum.f1.equal_groups",
        "material": "A total can be divided into a stated number of equal groups to find the size of each share, or arranged into groups of a stated size to find how many groups can be made. These are related but different questions.",
        "principles": [
            "Equal sharing fixes the total and number of groups while asking how many belong in each group.",
            "Equal grouping fixes the total and group size while asking how many groups can be formed.",
            "A remainder or leftover must stay visible when the total cannot be partitioned exactly under the stated condition.",
        ],
        "relationships": ["Sharing and grouping connect equal shares, subtraction, repeated addition, and later division notation."],
        "examples": ["Twelve objects shared equally among three groups gives four per group; twelve objects placed in groups of four gives three groups."],
        "counterexamples": ["Giving one group an extra item may distribute every object, but it does not satisfy an equal-sharing question."],
        "limits": ["This is an informal whole-number foundation. Fractional shares, formal division notation, and division algorithms belong to later lessons."],
        "vocabulary": [
            "equal sharing: distributing a total among a known number of equally sized groups",
            "equal grouping: forming groups of a known size from a total",
            "leftover: an item not included in the required equal grouping",
            "unknown: the quantity the question asks us to determine",
        ],
        "near_concept_distinctions": ["Finding the size of each group and finding the number of groups can produce related numbers, but they answer different unknowns."],
        "scope_of_application": "Use for bounded whole-item collections and explicitly equal groups. Preserve leftovers and do not silently split indivisible items or assume fractional sharing.",
        "unresolved_questions": ["Is the unknown the number in each group or the number of groups, and may the items be divided?"],
        "explanation": "Both situations reverse an equal-groups total, but the missing relationship differs. Naming what is fixed and what is unknown prevents the same numbers from hiding two different questions.",
        "application": "With eighteen test cases, assigning them equally to three reviewers asks for cases per reviewer; assigning three cases per reviewer asks how many reviewers receive a group.",
        "analogy": ["It is the difference between choosing the number of shelves and finding books per shelf, versus choosing books per shelf and finding how many shelves are needed."],
        "questions": ["What is fixed, what is unknown, and would anything remain outside the equal groups?"],
        "comparisons": ["Sharing asks for group size; grouping asks for group count."],
        "participation": "The total is twelve and there are three equal shares, so the unknown is the size of each share: four. If the problem instead requires groups of three, the unknown becomes the number of groups: four.",
        "correction_response": "If I answer the wrong unknown or hide a leftover, I would restate what is fixed, construct the equal groups, and report the remainder explicitly.",
        "families": ["MATH-1", "MATH-2", "LOGIC-1", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g2_math_unit8"],
        "source_refs": EQUAL_GROUP_REFS,
    },
    {
        "concept_key": "curriculum_f1_odd_even_pairing_v1",
        "title": "Odd and even describe whether whole items pair without a leftover",
        "domain": "curriculum.f1.number_patterns",
        "material": "A whole number is even when its items can be separated into two equal groups or paired in groups of two with none left over. It is odd when one item remains under that pairing.",
        "principles": [
            "Pairing supplies a reconstructable reason for an elementary odd-or-even classification.",
            "Rearranging the same number of items does not change whether all items can be paired.",
            "Adding two changes parity while adding an even number preserves parity.",
        ],
        "relationships": ["Odd and even connect counting by twos, equal groups, addition patterns, arrays, and later divisibility."],
        "examples": ["Eight is even because four pairs use all eight items; nine is odd because four pairs leave one item."],
        "counterexamples": ["An uneven-looking arrangement is not evidence that its quantity is odd; the items may still pair with none left over."],
        "limits": ["This definition concerns whole numbers. Everyday uses of odd and even may carry unrelated meanings."],
        "vocabulary": [
            "pair: a group of two",
            "even number: a whole number that forms pairs with no leftover",
            "odd number: a whole number that leaves one item after all possible pairs are formed",
            "parity: the property of being odd or even",
        ],
        "near_concept_distinctions": ["Odd describes a number relationship here, not something unusual; even describes pairing, not visual symmetry."],
        "scope_of_application": "Use for whole-number quantities. Demonstrate the classification through pairing, two equal groups, or another equivalent whole-number representation.",
        "unresolved_questions": ["Does every item have a partner, or does exactly one remain?"],
        "explanation": "Pairs consume items two at a time. If pairing reaches zero, the quantity is even; if one remains, it is odd. That is why changing the arrangement cannot change parity while adding one item does.",
        "application": "A system with fourteen identical connectors can allocate them in pairs with none left, so the connector count is even even if the connectors are scattered visually.",
        "analogy": ["It resembles checking whether everyone can be assigned one partner without leaving one participant unmatched."],
        "questions": ["Can the whole collection be paired completely, and what remains after pairing?"],
        "comparisons": ["An even collection forms complete pairs; an odd collection has one unpaired item."],
        "participation": "The arrangement looks irregular, but there are ten items. They form five complete pairs, so the quantity is even.",
        "correction_response": "If I classify from appearance or a mistaken count, I would count again, form explicit pairs, and revise the parity from the remainder.",
        "families": ["MATH-1", "MATH-2", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g2_math_unit8"],
        "source_refs": EQUAL_GROUP_REFS,
    },
    {
        "concept_key": "curriculum_f1_rectangular_arrays_v1",
        "title": "Rectangular arrays expose equal rows, columns, and one total",
        "domain": "curriculum.f1.number_patterns",
        "material": "A rectangular array arranges items into equal rows and equal columns. The total can be reconstructed by repeated addition across either rows or columns, while rotating the array changes orientation but not quantity.",
        "principles": [
            "Every row in a rectangular array has the same number of items, and every column does too.",
            "Adding by rows and adding by columns must produce the same total for one complete array.",
            "Rows and columns describe the arrangement; the total counts each item exactly once.",
        ],
        "relationships": ["Arrays connect equal groups, repeated addition, multiplication, geometry, area, tables, and coordinate organization."],
        "examples": ["Three rows of five have the same total as five columns of three: fifteen items."],
        "counterexamples": ["A ragged arrangement with unequal row lengths is not a complete rectangular array unless missing positions are represented explicitly."],
        "limits": ["An array shows a grouping structure but does not by itself establish the physical size, value, or meaning of its items."],
        "vocabulary": [
            "array: an organized arrangement of items",
            "row: a horizontal line of items under the stated orientation",
            "column: a vertical line of items under the stated orientation",
            "rectangular array: an array with equal-length rows and equal-length columns",
        ],
        "near_concept_distinctions": ["Rows and columns may exchange labels when an array rotates, but the counted items and total remain invariant."],
        "scope_of_application": "Use for complete, explicitly oriented rectangular arrangements. State the orientation when row and column language matters and keep missing positions visible.",
        "unresolved_questions": ["Is the arrangement complete and rectangular, and which orientation defines rows and columns?"],
        "explanation": "A rectangle organizes the same items along two directions. Counting equal rows or equal columns follows different groupings through the same collection, so both paths must preserve the total.",
        "application": "A dashboard grid with four rows and three tiles per row contains twelve tiles; rotating the display gives three rows of four without adding or removing a tile.",
        "analogy": ["It is like reading a table across records or down fields: the paths differ while the same cells remain."],
        "questions": ["How many rows, how many items per row, and does the column count confirm the same total?"],
        "comparisons": ["Rows group the array in one direction; columns group the same array in the perpendicular direction."],
        "participation": "I see four rows of three, which gives 3 + 3 + 3 + 3 = 12. The three columns of four confirm the same twelve items.",
        "correction_response": "If I omit a position, double-count an item, or confuse the orientation, I would trace each row and column and recompute the one preserved total.",
        "families": ["MATH-1", "MATH-2", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g2_math_unit8"],
        "source_refs": EQUAL_GROUP_REFS,
    },
    {
        "concept_key": "curriculum_f1_categorical_graph_representation_v1",
        "title": "Picture and bar graphs encode categorical counts",
        "domain": "curriculum.f1.data_literacy",
        "material": "Picture graphs and bar graphs represent how many observations belong to defined categories. Titles, category labels, baselines, units, symbols, and scales determine how the representation maps back to the data.",
        "principles": [
            "A graph needs labels that identify the subject, categories, and represented quantity.",
            "Equal visual units must represent equal quantities under the stated key or scale.",
            "The graph should preserve the underlying category counts even when the visual form changes.",
        ],
        "relationships": ["Graph construction connects categorical data, counting, comparison, addition, subtraction, visual-spatial reference, and source interpretation."],
        "examples": ["A bar graph can represent counts of four file types with one equally sized interval for each file."],
        "counterexamples": ["Bars beginning at different unstated baselines or pictures with inconsistent meanings can visually exaggerate a difference instead of faithfully representing the counts."],
        "limits": ["A graph is a selective representation of supplied data. It does not prove the data were collected fairly, establish a cause, or show omitted categories."],
        "vocabulary": [
            "categorical data: observations organized by named groups or qualities",
            "picture graph: a graph using repeated pictures or symbols to represent quantities",
            "bar graph: a graph using bar lengths or heights to represent quantities",
            "scale: the quantity represented by a unit of visual distance or one symbol",
        ],
        "near_concept_distinctions": ["The visual mark represents a count under a key or scale; it is not itself one of the counted objects."],
        "scope_of_application": "Use for bounded categorical counts with explicit labels and a consistent key or scale. Inspect provenance and collection method before extending a conclusion beyond the represented data.",
        "unresolved_questions": ["What does each mark represent, which categories were included, and where did the counts come from?"],
        "explanation": "A graph is useful because position, repeated symbols, or bar length preserves numerical relationships in a visible form. The labels and scale are required because they tell us how to translate the picture back into quantities.",
        "application": "The same counts of issue types can appear as repeated icons or bars. If both use a clear one-unit key, they should reconstruct the same totals for every category.",
        "analogy": ["A graph's scale is like a map legend: without it, distance or symbol size cannot be translated reliably."],
        "questions": ["What quantity does one symbol or interval represent, and can every displayed count be reconstructed?"],
        "comparisons": ["A picture graph uses repeated symbols; a bar graph uses measured visual length. Both can represent the same categorical counts."],
        "participation": "The bar is longer, but I will read its value from the shared baseline and scale rather than judge the area by appearance alone.",
        "correction_response": "If I misread the key, baseline, label, or scale, I would translate every mark through the stated representation rule and recompute the category counts.",
        "families": ["MATH-1", "MATH-2", "ELA-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g2_math_unit1"],
        "source_refs": DATA_REFS,
    },
    {
        "concept_key": "curriculum_f1_graph_interpretation_answerability_v1",
        "title": "A graph answers only questions its data represent",
        "domain": "curriculum.f1.data_literacy",
        "material": "Interpreting a graph means reconstructing values and supported comparisons from its labels, key, scale, and marks, then distinguishing those answers from questions the represented data cannot decide.",
        "principles": [
            "Read the title, labels, key, and scale before comparing categories.",
            "Counts can support totals, differences, ordering, and bounded comparisons when the required categories are present.",
            "A preference count does not by itself explain why the preference exists or predict a different population.",
        ],
        "relationships": ["Graph interpretation connects representation, addition, subtraction, comparison, questions, evidence scope, and observation-versus-interpretation."],
        "examples": ["If one bar represents twelve reports and another represents eight, the graph supports that the first category has four more represented reports."],
        "counterexamples": ["A graph of favorite seasons cannot answer which season has safer weather unless safety data were also collected and represented."],
        "limits": ["Accuracy is bounded by the source data, sampling, category definitions, scale, and any omitted or missing observations."],
        "vocabulary": [
            "interpret: derive bounded meaning from a representation and its rules",
            "supported question: a question answerable from the represented variables and observations",
            "difference: how much one represented quantity exceeds or falls below another",
            "omitted data: relevant observations not present in the representation",
        ],
        "near_concept_distinctions": ["A graph can display an association or count difference without supplying a causal explanation."],
        "scope_of_application": "Use for questions whose required categories, quantities, and comparison basis appear in the graph. Ask for another source or dataset when the graph lacks the needed variable.",
        "unresolved_questions": ["Does the graph contain the variable and population required by the question?"],
        "explanation": "The representation constrains the answer because it contains particular variables and counts. Calculations may combine or compare those values, but they cannot manufacture an unmeasured cause or a missing population.",
        "application": "A bug-category chart can show which recorded category is largest and how many more cases it contains, but it cannot show which bug is hardest to fix without effort data.",
        "analogy": ["It is like answering from a table: you may calculate from present columns, but a missing column does not become available because the question asks for it."],
        "questions": ["Which values answer this question directly, and which requested information is absent?"],
        "comparisons": ["Reading a value reconstructs represented data; explaining its cause requires additional evidence."],
        "participation": "The graph supports that category A has four more observations than category B. It does not show why that difference occurred, so I would keep the causal question open.",
        "correction_response": "If I infer beyond the displayed variables or use the wrong scale, I would return to the labels and represented values, narrow the claim, and identify the missing evidence.",
        "families": ["MATH-1", "MATH-2", "ELA-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g2_math_unit1"],
        "source_refs": DATA_REFS,
    },
    {
        "concept_key": "curriculum_f1_monetary_units_value_v1",
        "title": "A monetary item count is different from monetary value",
        "domain": "curriculum.f1.money_math",
        "material": "Coins and notes are physical monetary items assigned values in a currency system. A collection's monetary value depends on the denomination and quantity of each item, not merely on how many items are present.",
        "principles": [
            "Name the currency and denomination before calculating value.",
            "Count equal denominations by their assigned unit value, then combine subtotals in a common unit.",
            "A collection with more coins can have less value than a collection with fewer higher-denomination coins.",
        ],
        "relationships": ["Money contexts apply counting, place value, equal groups, addition, subtraction, representation, and unit conversion."],
        "examples": ["In U.S. currency, five dimes represent fifty cents while ten pennies represent ten cents, so fewer coins can represent more value."],
        "counterexamples": ["Counting seven mixed coins and reporting a value of seven cents ignores their denominations."],
        "limits": ["Coin names, designs, and assigned values are currency-, jurisdiction-, and time-specific. This lesson is arithmetic knowledge, not financial, legal, or purchasing advice."],
        "vocabulary": [
            "currency: a recognized system of monetary units",
            "denomination: the assigned monetary value of one kind of coin or note",
            "item count: how many physical monetary items are present",
            "monetary value: the amount represented in a named currency unit",
        ],
        "near_concept_distinctions": ["Coin count measures physical items; monetary value combines each item's denomination under a currency system."],
        "scope_of_application": "Use for arithmetic with explicitly identified currency units and denominations. Verify current or unfamiliar currency facts from an attributed source before relying on them.",
        "unresolved_questions": ["Which currency and denominations are present, and are their values current for the stated context?"],
        "explanation": "Currency gives different item types different unit values. That is why physical quantity and represented value can move in opposite directions: value is the sum of denominations, not a count of objects alone.",
        "application": "A register containing three ten-unit notes has greater stated value than a pile of twenty one-unit coins even though the pile contains more physical items.",
        "analogy": ["It resembles storage units: three gigabytes are not smaller than twenty megabytes merely because three is a smaller item count."],
        "questions": ["What does each item represent, which common unit will we use, and what is the subtotal for each denomination?"],
        "comparisons": ["Item count answers how many coins or notes; value answers how much currency those denominations represent."],
        "participation": "This collection has more coins, but most are lower denomination. I will total each denomination in cents before comparing value.",
        "correction_response": "If I confuse item count with value or mix currency units, I would identify each denomination, convert to one named unit, and recompute the total.",
        "families": ["MATH-1", "MATH-2", "ELA-1", "LIFE-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g2_math_unit6"],
        "source_refs": MONEY_REFS,
    },
    {
        "concept_key": "curriculum_f1_equivalent_monetary_compositions_v1",
        "title": "Different monetary compositions can represent the same total value",
        "domain": "curriculum.f1.money_math",
        "material": "A fixed monetary total can be composed from different combinations of denominations. Two collections are equivalent in value when their denomination subtotals sum to the same amount in one common currency unit.",
        "principles": [
            "Translate every denomination into one common unit before testing equivalence.",
            "Changing the composition does not change the total when the amount removed equals the amount added.",
            "Addition finds a combined value, subtraction finds a difference or missing value, and both should preserve the named currency unit.",
        ],
        "relationships": ["Equivalent monetary composition connects equality, inverse operations, place value, grouping, substitution, and later algebraic equivalence."],
        "examples": ["In U.S. currency, two dimes and one nickel equal twenty-five cents, the same value as one quarter, despite different item counts."],
        "counterexamples": ["Replacing one ten-cent item with one five-cent item changes the total unless another five cents is added."],
        "limits": ["Equal mathematical value does not mean two forms are equally convenient, accepted, available, historically stable, or suitable for a transaction."],
        "vocabulary": [
            "composition: a set of parts that forms a total",
            "equivalent value: the same represented amount despite a different form",
            "common unit: one shared unit used to compare or combine quantities",
            "substitution: replacing one composition with another that preserves a stated relationship",
        ],
        "near_concept_distinctions": ["Equal value does not require equal item count, identical denominations, or identical practical use."],
        "scope_of_application": "Use for bounded arithmetic in one identified currency with verified denominations. Keep mathematical equivalence separate from transactional, financial, or legal suitability.",
        "unresolved_questions": ["Do all items belong to the same currency system, and does the proposed exchange preserve the total in a common unit?"],
        "explanation": "The total depends on the sum of represented units, so the parts may change while the sum remains invariant. Converting to one unit makes that preserved relationship inspectable instead of relying on appearance or item count.",
        "application": "A budget line of thirty units can be represented as three tens, six fives, or another verified combination whose values sum to thirty; the composition changes while the total does not.",
        "analogy": ["It resembles writing one quantity as 30, 20 + 10, or 3 tens: different forms can preserve one value."],
        "questions": ["What is each subtotal in the common unit, and do the two sums match exactly?"],
        "comparisons": ["Equivalent compositions preserve total value; identical compositions preserve both value and the arrangement of denominations."],
        "participation": "The collections look different and contain different numbers of items, but both sum to twenty-five cents, so their monetary values are equivalent in this currency context.",
        "correction_response": "If I assume visual similarity or equal item count proves equivalence, I would convert every denomination to the common unit and compare the reconstructed sums.",
        "families": ["MATH-1", "MATH-2", "ELA-1", "LIFE-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g2_math_unit6"],
        "source_refs": MONEY_REFS,
    },
)
