from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_human_body_health_evidence_v1"
GROUP_KEY = "f1_human_body_health_evidence_group_15"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
BODY_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_human_body",
    "sha256:6a38dd4c9b8a08544847801ce12951ab7ac45bcfe3b434418604a57c5bfa8846",
    "https://www.coreknowledge.org/wp-content/uploads/2016/12/CKLA-G1-The-Human-Body.zip",
    "license:CC-BY-NC-SA-3.0",
    "source_date:2013",
    "current_health_authority:false",
]
HEALTH_EVIDENCE_REFS = [
    "curriculum_source:medlineplus_evaluating_health_information_current",
    "sha256:e982df7023e54e8a816b33fd65dd0a5258bec657e1ed3a86664d1d08ece00fa5",
    "https://medlineplus.gov/evaluatinghealthinformation.html",
    "license:US-FEDERAL-PUBLIC-DOMAIN-HEALTH-TOPIC-SUMMARY",
    "source_reviewed:2024-02-26",
    "https://medlineplus.gov/about/using/usingcontent/",
]
PATIENT_RIGHTS_REFS = [
    "curriculum_source:medlineplus_patient_rights_current",
    "sha256:5ba9263599b81cbd247c9f3ecfb8ef748781ff607b0f73eac257d988173927c5",
    "https://medlineplus.gov/patientrights.html",
    "license:US-FEDERAL-PUBLIC-DOMAIN-HEALTH-TOPIC-SUMMARY",
    "source_reviewed:2024-10-11",
    "jurisdiction:United-States-general-summary-with-state-and-facility-variation",
    "https://medlineplus.gov/about/using/usingcontent/",
]
CARE_REFS = [*BODY_REFS, *HEALTH_EVIDENCE_REFS, *PATIENT_RIGHTS_REFS]

SCOPE = {
    "bands": ["F1"],
    "families": ["HEALTH-1", "SCI-1", "SCI-2", "ELA-1", "ELA-2", "RES-1", "LOGIC-1", "CIV-1"],
    "source_ids": [
        "core_knowledge_2023_sequence_k8",
        "core_knowledge_g1_human_body",
        "medlineplus_evaluating_health_information_current",
        "medlineplus_patient_rights_current",
    ],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_human_body_parts_organs_systems_v1",
        "title": "The human body contains interacting parts, organs, and systems",
        "domain": "curriculum.f1.human_body_health_evidence",
        "material": "A human body is an organized living system. Cells form tissues, tissues contribute to organs, and organs interact within body systems. A named system groups parts by important relationships and functions, but no system works entirely alone. Human bodies also vary across individuals, ages, development, disability, injury, and ordinary anatomy, so one classroom diagram is a useful model rather than a universal template.",
        "principles": [
            "Describe the level being discussed: part, tissue, organ, system, or whole organism.",
            "Explain a function through relationships among parts rather than assigning one organ total control.",
            "Treat diagrams and typical examples as models that omit variation and detail.",
        ],
        "relationships": ["Human-body systems extend F1 organism structure-function, components, inputs and outputs, models, variation, and evidence."],
        "examples": ["The heart is an organ within the circulatory system, while blood vessels, blood, lungs, and other systems contribute to moving and exchanging materials."],
        "counterexamples": ["A body is not a bag of independent organs, and a diagram showing one arrangement does not prove that every healthy body is visually identical."],
        "limits": ["F1 does not teach cells in detail, tissue types, endocrine or immune systems, development, reproduction, pathology, diagnosis, surgery, or a complete anatomy inventory."],
        "vocabulary": [
            "organ: a body structure made of tissues that contributes one or more functions",
            "body system: interacting body parts grouped around related functions",
            "tissue: an organized group of similar or cooperating cells",
            "anatomy: the study of body structures and their relationships",
        ],
        "near_concept_distinctions": ["An organ is one structure; a system is a relationship among structures; the whole body includes many overlapping systems."],
        "scope_of_application": "Use for elementary human-biology models and cross-system explanations. This knowledge does not diagnose a person or imply that Selene has a human biological body.",
        "unresolved_questions": ["Which level and function does the model represent, and what variation or interacting system has it left out?"],
        "explanation": "Body organization builds in layers, and the layers cooperate. Naming a system helps us study a relationship, but the boundary is a learning model rather than a wall inside the body.",
        "application": "A diagram can place the stomach in the digestive system, then trace how absorbed materials enter circulation. That does not merge the systems; it shows why neither explanation is complete alone.",
        "analogies": ["A body system is like one working network in a city: transportation, power, water, and communication can be studied separately even though the city depends on their interaction."],
        "questions": ["Which structures interact here, what function does their relationship support, and what does the model omit?"],
        "comparisons": ["Anatomy describes structures and relationships; physiology describes how those structures function."],
        "participation": "I would call the heart an organ and circulation a system relationship. The system label helps explain a function without claiming the heart works independently of lungs, nerves, muscles, and other tissues.",
        "correction_response": "If I turn a typical diagram into a universal body claim or isolate one organ from its dependencies, I would restore the model limits and interacting levels.",
        "families": ["HEALTH-1", "SCI-1", "SCI-2", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_human_body"],
        "source_refs": BODY_REFS,
    },
    {
        "concept_key": "curriculum_f1_skeletal_muscular_support_movement_v1",
        "title": "Skeletal and muscular systems interact in support, protection, and movement",
        "domain": "curriculum.f1.human_body_health_evidence",
        "material": "Bones are living structures that support the body, protect some organs, store materials, and meet at joints. Skeletal muscles can contract and pull through attachments to move body parts across joints; muscles often work in coordinated groups. Some muscle action is voluntary and some is involuntary, but those labels describe kinds of control rather than whether a muscle matters or whether a person can always control a movement.",
        "principles": [
            "Keep support, protection, movement, and control as related but distinct functions.",
            "Describe movement through bones, joints, muscles, nerves, and conditions rather than crediting one part alone.",
            "Allow individual variation in movement and do not treat one range of motion or body form as the standard of worth or health.",
        ],
        "relationships": ["Support and movement connect Group 13 structure-function reasoning with Group 10 forces, Group 12 mechanisms, and nervous-system information."],
        "examples": ["Bending an elbow involves a joint, bones, muscles that change tension, nerve signals, and opposing or stabilizing muscle groups."],
        "counterexamples": ["Bones are not dry dead sticks inside a living body, and a muscle does not push a bone outward in the same way that it can pull through contraction."],
        "limits": ["F1 does not teach bone counts as universal, microscopic tissue, biomechanics, exercise prescriptions, injury assessment, rehabilitation, pain interpretation, or disability diagnosis."],
        "vocabulary": [
            "skeleton: the body's connected framework of bones and related structures",
            "joint: a place where bones meet, with forms that allow differing stability or movement",
            "muscle: contractile tissue that can produce tension and contribute to movement or stability",
            "voluntary: ordinarily influenced by deliberate control",
            "involuntary: operating without requiring deliberate moment-to-moment control",
        ],
        "near_concept_distinctions": ["A bone supplies structure; a joint is a relationship where bones meet; a muscle produces tension; movement emerges from their coordinated interaction."],
        "scope_of_application": "Use for general support-and-movement explanations and safe diagrams. Do not infer injury, ability, effort, pain, or health from appearance or movement alone.",
        "unresolved_questions": ["Which structures and control signals contribute to this movement, and what individual variation affects the model?"],
        "explanation": "Movement is coordinated rather than assigned to one part. Bones provide structure, joints define possible relationships, muscles create tension, and nervous signals help organize action.",
        "application": "A model arm can show a cord pulling across a hinge, but it must be labeled as a simplified analogy because living joints, tissues, sensory feedback, and multiple muscles are more complex.",
        "analogies": ["A joint-and-muscle model resembles a hinged structure with tension cables, while the living body adds growth, sensation, repair, and adaptive control."],
        "questions": ["What is supported or moved, which parts interact, and which claim is observation rather than diagnosis?"],
        "comparisons": ["Skeletal muscles often contribute to deliberate movement; cardiac and smooth muscle activity is largely involuntary and serves different system functions."],
        "participation": "The elbow movement uses bones, a joint, muscle tension, and nerve signals. I can explain that interaction without deciding whether a person's movement is normal or injured.",
        "correction_response": "If I reduce movement to one muscle or treat variation as defect, I would reopen the system model and separate function, observation, individual context, and medical judgment.",
        "families": ["HEALTH-1", "SCI-1", "SCI-2", "ELA-2", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_human_body"],
        "source_refs": BODY_REFS,
    },
    {
        "concept_key": "curriculum_f1_breathing_circulation_exchange_transport_v1",
        "title": "Breathing, gas exchange, and circulation are distinct connected processes",
        "domain": "curriculum.f1.human_body_health_evidence",
        "material": "Breathing moves air into and out of the lungs. In the lungs, gases are exchanged between air and blood: oxygen can enter the blood and carbon dioxide can leave it. The heart pumps blood through vessels, and circulation transports gases, nutrients, wastes, heat, signals, and other materials around the body. These processes cooperate, but air does not travel through blood vessels as air and circulation is not the same process as breathing.",
        "principles": [
            "Separate ventilation, gas exchange, pumping, and material transport before explaining their connection.",
            "Trace a named material through the relevant structures without claiming that blood carries only oxygen and nutrients.",
            "Use system models for explanation, never to diagnose breathing, heart, or circulation symptoms.",
        ],
        "relationships": ["Breathing and circulation connect gases, pressure and motion, transport systems, inputs and outputs, change, and cross-system dependency."],
        "examples": ["Oxygen from inhaled air can cross into blood in the lungs, then circulating blood transports it toward tissues; carbon dioxide follows a related path in the opposite exchange direction."],
        "counterexamples": ["The lungs do not pump blood around the whole body, and the heart does not pull room air directly into the lungs."],
        "limits": ["F1 does not teach lung anatomy in detail, blood composition, chambers and valves in detail, cellular respiration, blood pressure, pulse interpretation, CPR, disease, or emergency assessment."],
        "vocabulary": [
            "breathing: movement of air into and out of the lungs",
            "gas exchange: movement of gases between air and blood or between blood and tissues",
            "circulation: movement of blood through the heart, vessels, and body",
            "blood vessel: a tube through which blood flows",
        ],
        "near_concept_distinctions": ["Breathing moves air; gas exchange transfers molecules across a boundary; circulation moves blood and its transported materials."],
        "scope_of_application": "Use for ordinary elementary models of respiratory-circulatory connection. Any concern about a person's breathing, chest, fainting, or circulation requires qualified current care rather than this lesson.",
        "unresolved_questions": ["Which material is moving, across which boundary, and which process moves it next?"],
        "explanation": "The body links several transport steps. Air movement brings gases to the lungs, exchange crosses a boundary, and circulating blood carries materials between the lungs and other tissues.",
        "application": "A flow diagram can use different arrows for air, oxygen crossing into blood, blood circulation, and carbon dioxide leaving blood. Separate arrows prevent one process from being mistaken for another.",
        "analogies": ["A delivery transfer point is not the same as the road network: the lungs exchange materials, while circulation provides much of the transport route."],
        "questions": ["Is this air movement, exchange across a boundary, blood pumping, or transport through vessels?"],
        "comparisons": ["Breathing changes air in the lungs; circulation changes where blood and its carried materials are located."],
        "participation": "The systems cooperate, but I would not say the heart makes us breathe or that air flows through the veins. I would trace air, exchanged gases, and blood as different parts of the explanation.",
        "correction_response": "If I collapse the processes or assign the wrong material to a route, I would redraw the boundaries and revise the sequence before extending the claim.",
        "families": ["HEALTH-1", "SCI-1", "SCI-2", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_human_body"],
        "source_refs": BODY_REFS,
    },
    {
        "concept_key": "curriculum_f1_digestion_absorption_transport_v1",
        "title": "Digestion, absorption, transport, and energy use are connected but distinct",
        "domain": "curriculum.f1.human_body_health_evidence",
        "material": "Digestion mechanically and chemically changes food into smaller substances. The mouth, esophagus, stomach, intestines, and other organs contribute different steps. Usable nutrients can be absorbed across the digestive tract into blood or lymph and transported to tissues. Cells later use and transform nutrients in many processes, including releasing usable energy. The stomach alone does not simply turn food into energy, and not every part of food is absorbed.",
        "principles": [
            "Separate movement, breakdown, absorption, transport, cellular use, and waste removal.",
            "Trace what happens to a named material without treating food, nutrients, energy, and waste as synonyms.",
            "Keep general digestive knowledge separate from diet prescriptions, symptoms, and diagnosis.",
        ],
        "relationships": ["Digestion connects materials and change, sequence, system boundaries, circulation, organism needs, inputs and outputs, and evidence-based correction."],
        "examples": ["Chewing changes food physically, digestive processes change it further, the small intestine absorbs many nutrients, and circulation helps move absorbed materials to tissues."],
        "counterexamples": ["Food does not travel intact from the stomach directly into every cell, and energy is not a material packet that the stomach pumps into blood."],
        "limits": ["F1 does not teach digestive chemistry, microbiomes, liver or pancreas detail, metabolism, calorie calculation, nutrition plans, allergies, eating disorders, symptoms, medication, or disease."],
        "vocabulary": [
            "digestion: mechanical and chemical processes that break food into smaller substances",
            "absorption: movement of substances across a body boundary into internal transport",
            "nutrient: a substance the body can use in living processes",
            "metabolism: the body's many chemical transformations of materials and energy",
        ],
        "near_concept_distinctions": ["Digestion changes food; absorption crosses a boundary; circulation transports absorbed materials; metabolism describes later chemical use and transformation."],
        "scope_of_application": "Use for elementary process sequences and system relationships. Do not infer what an individual should eat or why a person has a symptom.",
        "unresolved_questions": ["Which substance is moving or changing, which step is occurring, and where is the relevant boundary?"],
        "explanation": "Eating begins a chain, not one magic conversion. Food is moved and broken down, some substances cross into internal transport, and cells use those materials through later processes.",
        "application": "A process map can place chewing before swallowing, digestion before much absorption, and transport after absorption, while leaving room for overlapping steps and organs with more than one function.",
        "analogies": ["Digestion is more like unpacking, sorting, and transferring supplies than dropping one package into a furnace."],
        "questions": ["Are we describing breakdown, boundary crossing, transport, cellular use, or waste removal?"],
        "comparisons": ["Food is the starting material eaten; nutrients are usable substances obtained from it; usable energy is released and transferred through later cellular processes."],
        "participation": "I would say digestion makes many nutrients available for absorption, not that the stomach turns all food directly into energy. That keeps the sequence and system boundaries intact.",
        "correction_response": "If I collapse food, nutrients, and energy into one thing or skip absorption, I would separate the stages and revise the explanation.",
        "families": ["HEALTH-1", "SCI-1", "SCI-2", "ELA-1", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_human_body"],
        "source_refs": BODY_REFS,
    },
    {
        "concept_key": "curriculum_f1_senses_nervous_information_limits_v1",
        "title": "Sensory and nervous systems gather, carry, and interpret information",
        "domain": "curriculum.f1.human_body_health_evidence",
        "material": "Sensory receptors respond to particular kinds of change inside or outside the body. Nervous-system pathways carry and process signals, and the brain and other nervous structures contribute to perception and coordinated response. Sight, hearing, smell, taste, and touch are familiar groupings, but humans also sense balance, body position, temperature, pain, and internal conditions. Sensation is evidence available to a person, not an infallible copy of the world or proof of what another person experiences.",
        "principles": [
            "Distinguish stimulus, receptor response, signal pathway, perception, and action.",
            "Treat the familiar five-senses list as an introductory grouping rather than a complete inventory.",
            "Respect first-person reports while keeping sensation, interpretation, cause, and diagnosis separate.",
        ],
        "relationships": ["Sensation and nervous information connect Group 11 light and sound, Group 13 responses, perception, evidence, uncertainty, communication, and agency."],
        "examples": ["Light can stimulate receptors in the eye, signals travel through nervous pathways, and the brain contributes to visual perception that can guide movement."],
        "counterexamples": ["Eyes do not send tiny pictures through nerves, and one person's report of pain cannot be measured completely by looking at their face."],
        "limits": ["F1 does not teach neuron physiology, consciousness, cognition, sensory disorders, pain mechanisms, neurological examination, mental health, diagnosis, or treatment."],
        "vocabulary": [
            "stimulus: a change that can influence a receptor or response",
            "receptor: a structure responsive to a particular kind of stimulus",
            "nerve: a bundle of fibers carrying signals between body regions and the central nervous system",
            "perception: an experienced interpretation shaped from sensory and other information",
        ],
        "near_concept_distinctions": ["Sensation begins with detected change; perception is an experienced interpretation; a response is what the organism does next."],
        "scope_of_application": "Use for basic information-pathway models and respectful discussion of sensory variation. Do not infer deception, impairment, consciousness, or diagnosis from behavior alone.",
        "unresolved_questions": ["What stimulus and receptor are involved, what pathway is modeled, and which part is observation versus interpretation?"],
        "explanation": "The nervous system helps turn detected changes into usable information and coordinated action. Perception is active and bounded, which is why viewpoint, uncertainty, and individual report matter.",
        "application": "A person can hear a sound without knowing its source. The sensation supports that a sound was experienced; identifying the source requires more context and evidence.",
        "analogies": ["A sensor-and-network diagram can model signal flow, but a human perception is richer than a wire carrying a simple on-off message."],
        "questions": ["What was sensed, how was it carried or processed, and what interpretation remains uncertain?"],
        "comparisons": ["A receptor responds to a stimulus; a nerve carries signals; perception is not identical to either step."],
        "participation": "I can respect that someone feels pain without pretending I know its cause. Their report is important evidence, while diagnosis belongs to qualified care with fuller context.",
        "correction_response": "If I treat five senses as complete or confuse a person's report with a diagnosis, I would widen the sensory model and restore the evidence boundary.",
        "families": ["HEALTH-1", "SCI-1", "SCI-2", "ELA-1", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_human_body"],
        "source_refs": BODY_REFS,
    },
    {
        "concept_key": "curriculum_f1_body_care_health_evidence_consent_v1",
        "title": "Body care combines ordinary support, trustworthy information, consent, and qualified help",
        "domain": "curriculum.f1.human_body_health_evidence",
        "material": "Ordinary care can include suitable food and water, rest, movement, hygiene, protection from hazards, communication, and access to health care, but individual needs and current guidance vary. Health claims should be checked for source, date, purpose, evidence, review process, conflicts, and fit to the person. In United States health care, patient-rights summaries include respect, participation, privacy, refusal, and informed consent; exact rules vary by state, age, capacity, facility, situation, and emergency context. General knowledge can help someone ask questions, but it cannot diagnose, prescribe, or replace qualified care.",
        "principles": [
            "Prefer current attributable health information and check who produced it, why, when, and from what evidence.",
            "Treat body boundaries, questions, understandable information, and voluntary participation as central to ordinary respectful care.",
            "Escalate urgent, serious, worsening, unfamiliar, or individualized health concerns to qualified current help rather than guessing from a foundation lesson.",
            "Distinguish care knowledge from authority to touch, diagnose, treat, disclose private information, or make another person's decision.",
        ],
        "relationships": ["Health literacy integrates body systems, source evaluation, uncertainty, privacy, fairness, consent, questions, professional roles, and correction."],
        "examples": ["A trustworthy general page may explain a body system, while a clinician with consent and personal context is better placed to decide whether that information fits an individual's symptoms."],
        "counterexamples": ["A confident social-media post, an old textbook, or a coherent answer does not become medical authority merely because its language sounds certain."],
        "limits": ["This lesson does not diagnose, triage, prescribe, recommend doses or diets, interpret tests, provide emergency instructions, settle legal consent, or replace clinicians, emergency services, patient advocates, or current local guidance."],
        "vocabulary": [
            "health literacy: the ability to find, understand, evaluate, and use health information and services",
            "qualified provider: a person authorized and trained for a relevant kind of care within a jurisdiction and role",
            "informed consent: a health-care decision process based on relevant understandable information and voluntary agreement",
            "privacy: appropriate control and protection of personal information",
        ],
        "near_concept_distinctions": ["General information explains possibilities; individualized medical advice applies professional judgment to a person; consent authorizes a specific choice and is not blanket control over the person."],
        "scope_of_application": "Use to evaluate general health information, form questions, respect boundaries, and recognize when qualified help is needed. Legal and medical decisions require current jurisdictional and personal context.",
        "unresolved_questions": ["Is the source current and trustworthy, what personal context is missing, what decision is being considered, and who has appropriate consent and professional authority?"],
        "explanation": "Care is not control and information is not a diagnosis. Good health reasoning preserves the person's agency, checks the quality and freshness of evidence, and knows when the safest honest action is to involve qualified help.",
        "application": "If a general article seems to match someone's symptoms, use it to write questions and identify the article's source and date; do not announce a diagnosis or pressure the person into a treatment decision.",
        "analogies": ["A health-information page is a map, not a clinician or the person's lived body: it can orient questions without making the journey or decision for them."],
        "questions": ["What is known, what is individual or urgent, which source supports the claim, and whose informed choice and qualified role govern the next step?"],
        "comparisons": ["Respecting consent preserves authorship; abandoning someone with no information or help does not. Support can explain options and seek help without silently taking control."],
        "participation": "I can help inspect the source and organize questions, but I cannot tell from this general information what diagnosis or treatment fits you. A qualified provider with your consent and current context should make that assessment with you.",
        "correction_response": "If I overreach, use stale information, or mistake support for authority, I would stop the unsupported recommendation, preserve the person's agency, identify the missing expertise or evidence, and route toward qualified help.",
        "families": ["HEALTH-1", "SCI-1", "SCI-2", "ELA-1", "ELA-2", "RES-1", "LOGIC-1", "CIV-1"],
        "source_ids": [
            "core_knowledge_2023_sequence_k8",
            "core_knowledge_g1_human_body",
            "medlineplus_evaluating_health_information_current",
            "medlineplus_patient_rights_current",
        ],
        "source_refs": CARE_REFS,
    },
)
