from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_mass_capacity_v1"
GROUP_KEY = "f1_mass_capacity_group_6"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
MEASUREMENT_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g3_math_unit6_teacher_guide",
    "sha256:9cc96694ca7cf35bb59ca5f26a9cbc364482190bffb49b007c2faa5b8c59ad3d",
    "https://www.coreknowledge.org/wp-content/uploads/2023/09/CKMath_G3U6_MeasuringLengthTimeLiquidVolumeAndWeight_TG_W2.pdf",
]
MASS_REFS = [
    *MEASUREMENT_REFS,
    "curriculum_source:nist_si_units_mass",
    "sha256:36ceb22e41d86cdf9bba6098b432e9ed4395b34b9b934d60dcddf19bcf564930",
    "https://www.nist.gov/pml/owm/si-units-mass",
]
VOLUME_REFS = [
    *MEASUREMENT_REFS,
    "curriculum_source:nist_si_units_volume",
    "sha256:012d2233f2a95ba70fdc4bf296665cab8f90397f6593063f2836092a0890e1d3",
    "https://www.nist.gov/pml/owm/si-units-volume",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["MATH-1", "MATH-2", "SCI-0", "SCI-1", "ELA-1", "LIFE-1"],
    "source_ids": [
        "core_knowledge_2023_sequence_k8",
        "core_knowledge_g3_math_unit6_teacher_guide",
        "nist_si_units_mass",
        "nist_si_units_volume",
    ],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_measurement_attribute_selection_v1",
        "title": "A measurement answers a question about one named attribute",
        "domain": "curriculum.f1.measurement",
        "material": "Objects and substances have different measurable attributes, including length, mass, and volume. A useful comparison names the attribute first and then uses a method and unit suited to that attribute.",
        "principles": [
            "A number is not a complete measurement unless the measured attribute and unit are known.",
            "Two objects can rank differently under different attributes.",
            "The instrument and unit must match the question being asked.",
        ],
        "relationships": ["Attribute selection builds on earlier length and comparison work and supports mass, capacity, time, area, and later scientific measurement."],
        "examples": ["One container can be taller while another has greater capacity, so height and capacity require different comparisons."],
        "counterexamples": ["Calling one box bigger does not establish whether it is longer, has more mass, or can hold more."],
        "limits": ["Some attributes require indirect measurement or controlled conditions; appearance alone is not a measurement."],
        "vocabulary": [
            "attribute: a feature or quantity that can be described or measured",
            "measurement: a comparison of an attribute with a named unit or reference",
            "instrument: a tool used to observe or measure an attribute",
            "unit: an agreed quantity used repeatedly in a measurement",
        ],
        "near_concept_distinctions": ["Size is informal and may combine several attributes; length, mass, and volume each name a particular quantity."],
        "scope_of_application": "Use whenever a comparison could depend on more than one attribute. Name what is being measured before selecting a method, instrument, or unit.",
        "unresolved_questions": ["Which attribute would actually answer the question, and what method can compare that attribute fairly?"],
        "explanation": "Measurement becomes meaningful only after the question is precise. Naming the attribute prevents a visible feature, such as height, from being mistaken for a different quantity, such as capacity or mass.",
        "application": "When comparing shipping packages, a scale can answer which has greater mass, while internal dimensions answer which has more room. Neither answer replaces the other.",
        "analogy": ["Choosing an attribute is like choosing the correct column in a table: the same objects may have different orderings under different columns."],
        "questions": ["Are we comparing length, mass, capacity, or another attribute, and which evidence belongs to that question?"],
        "comparisons": ["The attribute states what quantity matters; the unit and instrument state how that quantity is measured."],
        "participation": "Before I compare these containers, I need to name the attribute. Their heights are visible, but their capacity needs a separate measurement.",
        "correction_response": "If I infer one attribute from another, I would restate the question, select a matching method, and revise the comparison from the measured evidence.",
        "families": ["MATH-1", "SCI-0", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g3_math_unit6_teacher_guide"],
        "source_refs": MEASUREMENT_REFS,
    },
    {
        "concept_key": "curriculum_f1_mass_weight_distinction_v1",
        "title": "Mass and gravitational weight are related but not identical",
        "domain": "curriculum.f1.mass",
        "material": "Mass describes an object's amount of matter and resistance to changes in motion. Weight is the force of gravity acting on that mass. Everyday speech often uses weight when a scale is being used to determine mass, but scientific explanations keep the quantities distinct.",
        "principles": [
            "The kilogram is the SI unit of mass, and the gram is a smaller mass unit.",
            "An object's mass does not depend on its location in the way its gravitational weight does.",
            "Everyday wording can be understood without carrying its imprecision into scientific reasoning.",
        ],
        "relationships": ["Mass supports measurement, balance comparison, matter, motion, gravity, density, and later force reasoning."],
        "examples": ["An object's mass remains the same on Earth and the Moon, while the gravitational force on it is smaller on the Moon."],
        "counterexamples": ["A reading expressed in kilograms should not be described as a scientific unit of force; force is measured in newtons."],
        "limits": ["This foundation preserves the distinction but does not teach force equations, calibration physics, or gravitational-field calculations."],
        "vocabulary": [
            "mass: a measure of an object's matter and inertial property",
            "weight: the gravitational force acting on an object",
            "kilogram: the SI base unit of mass",
            "gram: a mass unit equal to one thousandth of a kilogram",
        ],
        "near_concept_distinctions": ["Mass is an object property measured in kilograms; scientific weight is a force measured in newtons, although ordinary conversation often uses weight to mean mass."],
        "scope_of_application": "Use mass for kilogram and gram measurements. Interpret ordinary references to weighing naturally, but preserve the mass-force distinction whenever it affects an explanation.",
        "unresolved_questions": ["Is the current question asking for mass, everyday scale language, or gravitational force?"],
        "explanation": "Mass and weight feel interchangeable in ordinary life because local gravity is nearly constant and scales commonly report mass. Separating them matters because changing gravity changes weight without changing the object itself.",
        "application": "A rover component with a mass of two kilograms keeps that mass on another world, even though the downward gravitational force on it changes.",
        "analogy": ["Mass is the amount being acted on; weight is one effect produced when gravity acts on that mass."],
        "questions": ["Is the quantity being reported in mass units, or are we discussing the force caused by gravity?"],
        "comparisons": ["Mass persists across locations; gravitational weight depends on both mass and the local gravitational field."],
        "participation": "In ordinary speech I understand that we are weighing the package, but the kilogram result is its mass. Its scientific weight is the gravitational force on it.",
        "correction_response": "If I use mass and weight as exact scientific synonyms, I would identify the unit and context, then correct the quantity without derailing ordinary conversation.",
        "families": ["MATH-1", "SCI-0", "SCI-1", "ELA-1"],
        "source_ids": ["core_knowledge_g3_math_unit6_teacher_guide", "nist_si_units_mass"],
        "source_refs": MASS_REFS,
    },
    {
        "concept_key": "curriculum_f1_mass_comparison_measurement_v1",
        "title": "Mass comparison needs a balance or a shared mass reference",
        "domain": "curriculum.f1.mass",
        "material": "Mass can be compared directly with a balance or measured against shared mass units. Shape, material, and visible size may suggest an estimate, but the measurement decides the comparison.",
        "principles": [
            "A balanced comparison holds the method and conditions consistent.",
            "Equal mass does not require equal size, shape, or material.",
            "An estimate is a useful prediction when it remains separate from the measured result.",
        ],
        "relationships": ["Mass comparison connects equality, ordering, unit iteration, estimation, evidence, and correction."],
        "examples": ["A compact metal object can have greater mass than a much larger empty container."],
        "counterexamples": ["Choosing the physically larger object does not reliably identify the greater mass."],
        "limits": ["A damaged, uncalibrated, overloaded, or inconsistently used instrument may give an unreliable result."],
        "vocabulary": [
            "balance: an instrument that compares masses",
            "estimate: a reasoned approximate value made before or without exact measurement",
            "heavier: having greater gravitational weight under the same local conditions; often used informally when comparing mass",
            "equal mass: matching amounts under the stated measurement precision",
        ],
        "near_concept_distinctions": ["An estimate anticipates a result; a measurement supplies evidence through a defined procedure."],
        "scope_of_application": "Use a consistent balance or mass scale and matching units. Treat appearance as a basis for estimation, not proof, and state instrument limits when they matter.",
        "unresolved_questions": ["Was the same instrument and unit used under comparable conditions, and is its precision sufficient for the claim?"],
        "explanation": "Mass is not visible by itself. A balance or scale turns the comparison into evidence by applying one procedure to both objects, while a shared unit makes the result communicable.",
        "application": "Two device housings look similar, but the same scale reports different masses. The measured values support the comparison more strongly than their appearance.",
        "analogy": ["A balance is an impartial referee: both objects meet the same comparison rule."],
        "questions": ["What did we estimate, what did we measure, and were both objects compared by the same rule?"],
        "comparisons": ["Visual size can guide a guess; balanced measurement determines the supported mass comparison."],
        "participation": "The larger package might have more mass, but that is only my estimate. I would use the same scale and unit for both before deciding.",
        "correction_response": "If the measurement contradicts my estimate, I would keep the useful prediction process, accept the measured evidence, and revise the conclusion.",
        "families": ["MATH-1", "MATH-2", "SCI-0", "ELA-1"],
        "source_ids": ["core_knowledge_g3_math_unit6_teacher_guide", "nist_si_units_mass"],
        "source_refs": MASS_REFS,
    },
    {
        "concept_key": "curriculum_f1_capacity_contained_volume_v1",
        "title": "Container capacity differs from the amount currently inside",
        "domain": "curriculum.f1.capacity",
        "material": "Volume describes three-dimensional space occupied by matter or enclosed by a surface. A container's capacity is the volume it can hold to a defined full point; the liquid volume currently inside may be less than that capacity.",
        "principles": [
            "Capacity belongs to the container under a stated fill boundary.",
            "The contained amount can change while the container's capacity stays the same.",
            "Height or width alone does not determine capacity when container shapes differ.",
        ],
        "relationships": ["Capacity connects volume, three-dimensional shape, conservation, units, estimation, and practical measurement."],
        "examples": ["A one-liter bottle has the same capacity when empty, half full, or full, while its contained liquid volume changes."],
        "counterexamples": ["A tall narrow glass does not necessarily hold more than a shorter wide bowl."],
        "limits": ["Usable capacity can depend on a marked fill line, lid, displacement, deformation, or safety margin; the boundary must be stated when relevant."],
        "vocabulary": [
            "volume: the amount of three-dimensional space occupied or enclosed",
            "capacity: the volume a container can hold to a defined boundary",
            "contained volume: the amount of material currently inside a container",
            "fill boundary: the point treated as full for the measurement",
        ],
        "near_concept_distinctions": ["Capacity is the container's possible holding volume; contained volume is how much is in it now."],
        "scope_of_application": "Use for containers and their contents. State whether the question concerns maximum capacity or current contained volume, and define the full point when it is not obvious.",
        "unresolved_questions": ["Are we measuring what the container can hold or what it contains now, and what counts as full?"],
        "explanation": "A container provides available space, but that space need not be filled. Separating capacity from current contents prevents an empty container from being described as having no capacity.",
        "application": "A storage tank rated for five hundred liters can currently contain one hundred liters. Those values describe capacity and present contents, not a contradiction.",
        "analogy": ["Capacity is like the number of seats in a room; current contents are like the number of people sitting there now."],
        "questions": ["What could this container hold when full, and how much does it contain at this moment?"],
        "comparisons": ["Capacity can remain fixed while the contained amount increases or decreases."],
        "participation": "The bottle is empty, so its current liquid volume is zero, but its capacity is unchanged because it can still hold the same amount when filled.",
        "correction_response": "If I confuse empty contents with zero capacity or infer capacity from one dimension, I would name the two quantities and compare the full internal volumes.",
        "families": ["MATH-1", "SCI-0", "SCI-1", "ELA-1", "LIFE-1"],
        "source_ids": ["core_knowledge_g3_math_unit6_teacher_guide", "nist_si_units_volume"],
        "source_refs": VOLUME_REFS,
    },
    {
        "concept_key": "curriculum_f1_capacity_fair_comparison_v1",
        "title": "Fair capacity comparison repeats one equal unit or uses a complete transfer",
        "domain": "curriculum.f1.capacity",
        "material": "Containers of different shapes can be compared by filling each with the same small unit container and counting equal full units, or by transferring one full container into the other under controlled conditions.",
        "principles": [
            "Repeated units must represent equal volumes and be filled consistently.",
            "A transfer comparison must account for spills, residue, and the same definition of full.",
            "The larger count of one shared unit represents the greater measured capacity.",
        ],
        "relationships": ["Fair capacity comparison connects unit iteration, counting, equality, experimental control, and evidence."],
        "examples": ["If container A holds eight equal cupfuls and container B holds ten of the same cupful, B has greater measured capacity."],
        "counterexamples": ["Eight large scoops and ten small scoops cannot be compared by count alone because the units differ."],
        "limits": ["Foam, absorption, spills, irregular fill lines, temperature effects, or material left behind can make a practical transfer inexact."],
        "vocabulary": [
            "unit iteration: repeating one equal unit to measure a quantity",
            "transfer comparison: moving contents between containers to compare what each can hold",
            "controlled condition: a relevant feature kept consistent during a comparison",
            "residue: material left behind during transfer",
        ],
        "near_concept_distinctions": ["A larger unit count means greater capacity only when every counted unit has the same volume."],
        "scope_of_application": "Use one unchanged unit, a consistent fill rule, and careful transfer. Report practical uncertainty when spills or residue could change the result.",
        "unresolved_questions": ["Were the unit, fill boundary, and transfer conditions consistent enough to support the comparison?"],
        "explanation": "Different shapes make appearance unreliable. Repeating the same volume unit converts both containers to one comparable count, while transfer can reveal which full amount exceeds the other.",
        "application": "To compare two oddly shaped reservoirs, fill both from the same calibrated cup to their marked lines and count complete cupfuls rather than comparing heights.",
        "analogy": ["It is like measuring two paths with the same step length: the counts are comparable only because the repeated unit stays equal."],
        "questions": ["Did every counted unit have equal volume, and did both containers use the same definition of full?"],
        "comparisons": ["Visual comparison is a provisional estimate; shared-unit or controlled-transfer comparison supplies measurement evidence."],
        "participation": "The taller container looked larger, but the shorter one held two more of the same cupful. Under this shared unit and fill rule, the shorter container has greater capacity.",
        "correction_response": "If the units or fill levels differ, I would discard the unsupported count comparison and repeat it with one consistent procedure.",
        "families": ["MATH-1", "MATH-2", "SCI-0", "ELA-1", "LIFE-1"],
        "source_ids": ["core_knowledge_g3_math_unit6_teacher_guide", "nist_si_units_volume"],
        "source_refs": VOLUME_REFS,
    },
    {
        "concept_key": "curriculum_f1_liter_milliliter_scale_v1",
        "title": "Liters and milliliters communicate volume through a shared scale",
        "domain": "curriculum.f1.capacity",
        "material": "The liter is a metric volume unit, and the milliliter is a smaller metric volume unit. A marked measuring container maps liquid level to volume only when its scale, unit, orientation, and reading conditions are understood.",
        "principles": [
            "One liter equals one thousand milliliters.",
            "A measuring scale must use equal stated intervals under one unit.",
            "A level between marks supports a bounded reading rather than an invented exact value.",
        ],
        "relationships": ["Liters and milliliters connect base-ten structure, unit conversion, scale reading, estimation, capacity, and later volume calculations."],
        "examples": ["A 250-milliliter amount is one fourth of a liter, while four such equal amounts total one liter."],
        "counterexamples": ["A taller liquid level in a narrower container does not prove a greater volume than a lower level in a wider container."],
        "limits": ["This foundation does not cover every customary unit, precision correction, meniscus convention, or three-dimensional volume formula."],
        "vocabulary": [
            "liter: a metric unit of volume equal to one cubic decimeter",
            "milliliter: a metric unit of volume equal to one thousandth of a liter",
            "scale interval: the quantity represented between neighboring marks",
            "graduated container: a container marked to indicate measured volumes",
        ],
        "near_concept_distinctions": ["The liquid level is a position in one particular container; volume is the quantity that the container's calibrated scale represents."],
        "scope_of_application": "Use the unit and interval printed on the measuring tool, keep the tool in its intended orientation, and limit precision to what the markings support.",
        "unresolved_questions": ["What does each interval represent, is the container positioned correctly, and does the level fall on or between marks?"],
        "explanation": "A shared unit lets different measurements be communicated and combined. The scale translates a position into that unit, but only within the precision and geometry for which the tool was marked.",
        "application": "If neighboring marks differ by one hundred milliliters and the liquid is halfway between them, the reading can be described as approximately halfway rather than given unsupported single-milliliter precision.",
        "analogy": ["A graduated container is a number line shaped around a container: its marks need a known starting point, direction, and interval."],
        "questions": ["Which unit is shown, how much does each interval represent, and how precise can the reading honestly be?"],
        "comparisons": ["Liquid height depends on container shape; a calibrated volume reading accounts for that shape through its scale."],
        "participation": "The level is higher in this narrow container, but I will compare the marked volume readings rather than the heights alone.",
        "correction_response": "If I misread the unit, interval, or container shape, I would reconstruct the scale from its labels and revise the value to supported precision.",
        "families": ["MATH-1", "MATH-2", "SCI-0", "ELA-1", "LIFE-1"],
        "source_ids": ["core_knowledge_g3_math_unit6_teacher_guide", "nist_si_units_volume"],
        "source_refs": VOLUME_REFS,
    },
)
