from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_community_rules_civic_reasoning_v1"
GROUP_KEY = "f1_community_rules_group_7"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
CIVICS_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_civics",
    "sha256:ea24fedc236ef8d3ef6b6491cfbd847f16f5adee0487dbecad030d6fec5f4f99",
    "https://www.coreknowledge.org/wp-content/uploads/2023/12/CKHG_G1U10_LessonsInCivics_Web_W1.zip",
    "license:CC-BY-NC-SA-4.0",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["HIST-1", "CIV-1", "ELA-1", "ELA-2", "CULT-1", "LOGIC-1", "LIFE-1"],
    "source_ids": [
        "core_knowledge_2023_sequence_k8",
        "core_knowledge_g1_civics",
    ],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_community_membership_scale_v1",
        "title": "Communities are shared relationships at overlapping scales",
        "domain": "curriculum.f1.community",
        "material": "A community is a group of people connected by a shared place, activity, institution, purpose, practice, or continuing relationship. Communities can be temporary or lasting, small or large, and one person can participate in several at the same time.",
        "principles": [
            "Community membership describes a relationship among people; it does not define the whole individual.",
            "Communities may overlap or nest, such as a project group within an organization within a town.",
            "A shared feature can connect members without making every member alike.",
        ],
        "relationships": ["Community scale builds on groups, categories, spatial reference, and part-whole relationships and supports later civics, institutions, culture, and systems reasoning."],
        "examples": ["A person can belong to a family, a research team, a neighborhood, and an online astronomy group without those communities becoming the same group."],
        "counterexamples": ["People standing near one another for a moment do not necessarily form a continuing community unless a shared context or relationship connects them."],
        "limits": ["Community boundaries can be informal, disputed, changing, or partly chosen; a label should not be used to invent a person's beliefs, loyalty, or identity."],
        "vocabulary": [
            "community: people connected by a shared place, activity, institution, purpose, practice, or relationship",
            "member: a person participating in or belonging to a group",
            "scale: the relative level or extent at which a group is considered",
            "overlap: sharing some members or features without becoming identical",
        ],
        "near_concept_distinctions": ["An individual is a person; a community is a relationship among people. Membership is one connection a person has, not the person's complete identity."],
        "scope_of_application": "Use when describing connected groups. Name the shared relationship and relevant scale, and avoid inferring personal traits from membership alone.",
        "unresolved_questions": ["What actually connects these people, how stable is the connection, and which scale matters to the current question?"],
        "explanation": "People form communities because shared places, purposes, practices, and institutions make coordination, mutual support, communication, and belonging possible. The connection explains the group, while overlapping membership explains why one person can participate in several communities without being divided into several individuals.",
        "application": "A local emergency team and a national weather network can share some people and information while remaining different communities with different scales and responsibilities.",
        "analogies": ["Communities can overlap like circles in a diagram: one point may lie in several circles while remaining one point."],
        "questions": ["What relationship connects the members, and is the question about the person, one community, or several overlapping communities?"],
        "comparisons": ["A category groups by a selected feature; a community also involves a meaningful social connection or shared context."],
        "participation": "Those people share the same project, so they form a project community for this purpose. That membership tells me about the collaboration, not everything about any member.",
        "correction_response": "If I treat one community label as a complete identity or merge overlapping groups, I would restore the individual/group distinction and name the specific shared relationship.",
        "families": ["HIST-1", "CIV-1", "ELA-1", "CULT-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": CIVICS_REFS,
    },
    {
        "concept_key": "curriculum_f1_cooperation_roles_boundaries_v1",
        "title": "Cooperation coordinates contributions without erasing boundaries",
        "domain": "curriculum.f1.cooperation",
        "material": "People cooperate when they coordinate different actions or resources toward a shared purpose. Roles can clarify who is responsible for which contribution, while consent, privacy, ability, and the limits of each role still matter.",
        "principles": [
            "Cooperation does not require every person to perform the same task.",
            "A role grants only the responsibility or authority that belongs to that context.",
            "Helping and sharing can support a community, but personal boundaries and private property do not disappear.",
        ],
        "relationships": ["Cooperation builds on sequence, equal participation, division of work, communication, truthfulness, and correction and supports later institutions, engineering teams, and collective problem solving."],
        "examples": ["In a cleanup project, one person can organize supplies, another can sort materials, and another can record results; the different roles contribute to one purpose."],
        "counterexamples": ["Assigning all work to one member while claiming that everyone cooperated does not show coordinated contribution."],
        "limits": ["Some participation is voluntary and some roles are formally assigned. Safety, law, expertise, and consent may limit who should perform a task."],
        "vocabulary": [
            "cooperation: coordinating contributions toward a shared purpose",
            "role: a bounded function or responsibility within a context",
            "contribution: work, information, care, or resources added to a shared effort",
            "boundary: a limit on responsibility, access, consent, or use",
        ],
        "near_concept_distinctions": ["Cooperation coordinates people; obedience follows a direction. They can overlap, but cooperation does not mean uncritical compliance."],
        "scope_of_application": "Use for shared work and mutual support. State the purpose, roles, needed coordination, and any relevant consent, expertise, or safety boundary.",
        "unresolved_questions": ["Which contributions are needed, who has the relevant role or ability, and what boundaries constrain the work?"],
        "explanation": "Many purposes require more knowledge, time, tools, or perspectives than one participant has alone. Roles reduce confusion by dividing responsibility, while boundaries prevent the shared purpose from becoming permission to use people or resources without consent.",
        "application": "A research group can let one member collect observations, another verify calculations, and another document sources, then compare the pieces before drawing a conclusion.",
        "analogies": ["Cooperation is like parts of a system performing different functions while exchanging what the whole task requires."],
        "questions": ["What is the shared purpose, what does each role contribute, and where does any person's authority stop?"],
        "comparisons": ["Equal worth does not require identical roles; different roles do not establish greater personal worth."],
        "participation": "We can divide this by function: you can provide the local context, I can organize the comparison, and we can check the conclusion together.",
        "correction_response": "If I confuse a role with total authority or assume sharing is mandatory, I would restore the role's scope, consent boundary, and actual shared purpose.",
        "families": ["CIV-1", "ELA-1", "LOGIC-1", "LIFE-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": CIVICS_REFS,
    },
    {
        "concept_key": "curriculum_f1_rules_purpose_context_v1",
        "title": "Rules coordinate behavior for a stated purpose and context",
        "domain": "curriculum.f1.rules",
        "material": "A rule is a stated guide or constraint for behavior in a defined context. Rules can coordinate turns, protect safety, preserve fair participation, or make a shared process predictable, but their fit depends on the purpose and setting.",
        "principles": [
            "A useful rule has a recognizable purpose and a context in which it applies.",
            "Different settings may need different rules because their activities and risks differ.",
            "Following a rule does not prove that the rule is effective, fair, current, or applicable outside its scope.",
        ],
        "relationships": ["Rules connect conditional language, boundaries, repeated procedures, fairness, safety, and institutional reasoning and build on ordered algorithms without becoming the same as instructions."],
        "examples": ["Taking turns can keep a meeting understandable because it prevents several people from speaking over one another."],
        "counterexamples": ["A rule suited to a quiet reading room should not be copied automatically into an emergency where calling out a warning is necessary."],
        "limits": ["Rules can be incomplete, outdated, conflicting, unfair, or overridden by higher law or urgent safety. The relevant authority and exception process may need verification."],
        "vocabulary": [
            "rule: a guide or constraint for behavior in a defined context",
            "purpose: the reason a rule or process is intended to serve",
            "scope: the people, setting, actions, and time to which a rule applies",
            "exception: a case that is not handled by the ordinary rule",
        ],
        "near_concept_distinctions": ["An instruction describes steps for doing something; a rule constrains or guides conduct. One procedure may contain both."],
        "scope_of_application": "Use when interpreting or proposing conduct constraints. Identify the purpose, scope, authority, likely effect, and any material exception rather than treating wording alone as sufficient.",
        "unresolved_questions": ["What purpose does the rule serve, who and what does it cover, and does the current case fit that scope?"],
        "explanation": "Shared activity becomes easier to coordinate when participants can predict relevant conduct. The purpose explains why the constraint exists, while scope prevents a useful local rule from being mistaken for a universal law.",
        "application": "A laboratory rule that protective eyewear must be worn during a chemical procedure serves a specific safety purpose; it does not require eyewear during unrelated office work.",
        "analogies": ["A rule is like a guardrail placed around a particular risk: its location and purpose matter as much as its presence."],
        "questions": ["What is this rule trying to protect or coordinate, and does that reason apply in the present setting?"],
        "comparisons": ["A rule may make conduct predictable; evidence about outcomes is still needed to judge whether it achieves its purpose."],
        "participation": "Before I carry that rule into this case, I want to check its purpose and scope. The setting may have changed even if the wording has not.",
        "correction_response": "If I apply a rule outside its context or assume purpose from wording alone, I would identify the governing setting, ask why the rule exists, and revise the application.",
        "families": ["CIV-1", "ELA-1", "LOGIC-1", "LIFE-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": CIVICS_REFS,
    },
    {
        "concept_key": "curriculum_f1_rule_law_custom_distinction_v1",
        "title": "Rules, laws, customs, and agreements have different authority",
        "domain": "curriculum.f1.civic_structure",
        "material": "Rule is a broad term for conduct guidance. A law is a rule created or recognized through a governing legal system within a jurisdiction. A custom is a repeated social practice, and an agreement is a commitment accepted by particular participants.",
        "principles": [
            "Every law functions as a rule, but not every rule is a law.",
            "Legal authority depends on jurisdiction, level of government, time, and current legal status.",
            "A custom may influence expectations without automatically carrying legal force, and an agreement binds only within its valid scope.",
        ],
        "relationships": ["This distinction builds on categories, nested scales, authority boundaries, and source verification and supports later civics, contracts, institutional literacy, and legal research."],
        "examples": ["A club can have a meeting rule, a household can have an agreement, and a city can have a law; each directs conduct through a different source of authority."],
        "counterexamples": ["Calling an office preference a law does not give it legal authority, and calling a law merely a custom does not remove its legal status."],
        "limits": ["This foundation is not legal advice. Current law, valid authority, enforcement, rights, and conflicts among jurisdictions require current authoritative sources."],
        "vocabulary": [
            "law: a rule created or recognized through a governing legal system",
            "jurisdiction: the territory, people, subject, or level over which legal authority applies",
            "custom: a repeated social practice or expectation",
            "agreement: a commitment accepted by identified participants",
        ],
        "near_concept_distinctions": ["Legality asks what a valid legal system currently requires; fairness and morality ask different questions and are not settled by the legal label alone."],
        "scope_of_application": "Use for basic classification of conduct guidance. State the source and scope of authority, and seek current jurisdiction-specific evidence before making a legal claim.",
        "unresolved_questions": ["Who created or accepted this rule, under what authority, in which jurisdiction, and is it current?"],
        "explanation": "The categories matter because the consequence and method of change depend on the source of authority. A household agreement, a community custom, an organizational rule, and a law may use similar words while relying on different institutions and processes.",
        "application": "A posted workshop rule can control use of shared equipment without becoming a national law; its authority comes from the workshop's bounded responsibility for that space.",
        "analogies": ["Rules are a broad family, while laws, customs, and agreements are different branches whose authority comes from different roots."],
        "questions": ["Is this a law, another kind of formal rule, a custom, or an agreement, and what evidence establishes that classification?"],
        "comparisons": ["A law has legal-system authority in a jurisdiction; a custom has social persistence; an agreement has participant acceptance."],
        "participation": "That may be an organizational rule, but I would not call it a law without identifying the legal authority and jurisdiction.",
        "correction_response": "If I overstate a custom or policy as law, I would correct the category, preserve the actual practical constraint, and verify any legal claim from a current authoritative source.",
        "families": ["HIST-1", "CIV-1", "ELA-2", "LOGIC-1", "LIFE-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": CIVICS_REFS,
    },
    {
        "concept_key": "curriculum_f1_fairness_consistent_relevance_v1",
        "title": "Fairness compares treatment through relevant reasons and effects",
        "domain": "curriculum.f1.fairness",
        "material": "Fairness asks whether benefits, burdens, opportunities, and rules are handled through relevant and supportable reasons. Consistency matters, but identical treatment is not always fair when relevant needs, risks, responsibilities, or starting conditions differ.",
        "principles": [
            "Similar cases should be treated consistently unless a relevant difference justifies a distinction.",
            "A fair opportunity is not established merely by using the same words for everyone.",
            "A claimed exception needs a reason connected to the purpose rather than favoritism or an unrelated trait.",
        ],
        "relationships": ["Fairness builds on equality, comparison attributes, rule purpose, evidence, and perspective and supports later ethics, civics, accessibility, experimental design, and resource decisions."],
        "examples": ["Giving each participant the same time to speak can support fair participation, while providing an accessibility aid can remove a relevant barrier without giving the person greater authority."],
        "counterexamples": ["Changing a rule only for a favored participant without a purpose-related reason is not supported merely because an authority allowed it."],
        "limits": ["People can reasonably disagree about which differences are relevant or how competing rights and needs should be balanced. Higher-stakes cases require evidence, affected perspectives, and applicable law."],
        "vocabulary": [
            "fairness: treatment guided by relevant and supportable reasons",
            "consistency: applying the same standard to relevantly similar cases",
            "relevant difference: a distinction connected to the purpose of the decision",
            "favoritism: preference based on personal attachment rather than a relevant standard",
        ],
        "near_concept_distinctions": ["Equality can mean sameness in a named respect; fairness asks whether the chosen respect and any differences in treatment have relevant justification."],
        "scope_of_application": "Use for bounded comparisons of rules, opportunities, benefits, and burdens. Name the standard, relevant differences, affected people, and evidence rather than declaring fairness from outcome alone.",
        "unresolved_questions": ["What standard is being used, which differences are relevant to its purpose, and whose effects or perspective are missing?"],
        "explanation": "Consistency protects against arbitrary changes, but a decision also has to fit the real situation. Looking for purpose-related differences explains why fairness can require sameness in one case and a justified adjustment in another.",
        "application": "Two machines should be judged by the same safety threshold, but a machine designed for a different load may require a different test procedure to measure that threshold fairly.",
        "analogies": ["Fair comparison is like measurement: the same attribute and standard matter, but the method must still fit what is being measured."],
        "questions": ["Which cases are relevantly similar, what difference is being used, and how does that difference connect to the purpose?"],
        "comparisons": ["Consistency blocks arbitrary exceptions; relevance tests whether an exception is justified."],
        "participation": "The different treatment is not automatically unfair, but it needs a reason tied to the rule's purpose. I would compare the actual effects and hear the affected perspectives.",
        "correction_response": "If I equate fairness with identical treatment or with any preferred outcome, I would name the standard, test the relevance of differences, and reopen the conclusion.",
        "families": ["CIV-1", "ELA-2", "LOGIC-1", "LIFE-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": CIVICS_REFS,
    },
    {
        "concept_key": "curriculum_f1_respectful_disagreement_rule_revision_v1",
        "title": "Rules can be questioned and revised through reasoned participation",
        "domain": "curriculum.f1.civic_revision",
        "material": "Disagreement can be expressed without treating another person as an enemy or pretending agreement. A participant can ask what a rule is for, describe its effects, offer evidence, propose a change, and use an appropriate review process.",
        "principles": [
            "Respect concerns how people are treated; it does not require agreement or silence.",
            "A rule's existence does not make it infallible, and a challenge does not make every rule optional.",
            "Revision should preserve useful structure when possible while correcting the unsupported or harmful part.",
        ],
        "relationships": ["Reasoned civic revision connects correction readiness, truthfulness, evidence, fair process, source history, epistemic reopening, and later democratic and institutional reasoning."],
        "examples": ["A team can keep a useful equipment-check rule while revising a scheduling detail that repeatedly prevents one necessary role from participating."],
        "counterexamples": ["Insulting a person instead of addressing the rule gives no evidence about whether the rule fits its purpose."],
        "limits": ["The safe and lawful process for challenging a rule varies by institution and jurisdiction. Urgent danger, retaliation risk, or rights violations may require qualified support rather than ordinary discussion."],
        "vocabulary": [
            "disagreement: holding or expressing a different conclusion or preference",
            "revision: a change made after review",
            "participation: contributing to a shared decision or community process",
            "appeal: asking an appropriate authority or process to review a decision",
        ],
        "near_concept_distinctions": ["Respectful disagreement protects dignity and addresses the issue; automatic agreement hides the disagreement, while personal attack redirects it at the person."],
        "scope_of_application": "Use for ordinary rule questions and collaborative revision. State the concern, evidence, purpose, proposed change, and appropriate process, while escalating genuine safety or legal stakes to qualified support.",
        "unresolved_questions": ["What effect is unsupported or harmful, what useful purpose should remain, who is affected, and which review process has authority?"],
        "explanation": "Communities need enough stability to coordinate, but experience can reveal that a rule no longer serves its purpose or distributes harm unfairly. Evidence and an appropriate process let the community correct the part that does not fit without discarding every useful boundary.",
        "application": "If a reporting rule creates duplicate work without improving verification, collaborators can document the duplication and propose one shared record that preserves accountability.",
        "analogies": ["Revising a rule is like correcting a model: keep the structure that still explains the evidence and change the part that does not."],
        "questions": ["What should remain, what should change, what evidence supports the change, and who can review it?"],
        "comparisons": ["Reasoned disagreement challenges a claim or rule; hostility attacks a person; compliance follows the current rule while review is still pending."],
        "participation": "I understand the rule's purpose, but this case exposes a conflict. I would show the effect, suggest a narrower revision, and ask the responsible process to review it.",
        "correction_response": "If I treat disagreement as disrespect or treat every existing rule as correct, I would separate the person from the issue, inspect the rule's purpose and effects, and revise my assessment.",
        "families": ["HIST-1", "CIV-1", "ELA-2", "LOGIC-1", "LIFE-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": CIVICS_REFS,
    },
)
