from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_pushes_pulls_forces_v1"
GROUP_KEY = "f1_pushes_pulls_forces_group_10"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
FORCE_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_k_pushes_pulls",
    "sha256:47b7e7063d9035871924e55276999c983ab7889d4bbfce6aff3dc764bdacdc92",
    "https://www.coreknowledge.org/wp-content/uploads/2020/06/CKSci_GKU1_Pushes-and-Pulls.zip",
    "license:CC-BY-NC-SA-4.0",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ELA-1", "ELA-2", "ENG-1", "RES-1", "LOGIC-1"],
    "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_pushes_pulls"],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_force_push_pull_interaction_v1",
        "title": "A force is a push or pull acting in an interaction",
        "domain": "curriculum.f1.pushes_pulls_forces",
        "material": "A force is a push or pull acting on an object through an interaction. A contact force acts while objects or materials touch; some forces, including gravity and magnetic force, can act without direct contact.",
        "principles": [
            "Name what exerts the force and what object the force acts on.",
            "A push or pull can exist even when its effect is small or no motion is visible.",
            "Touching is required for many everyday forces but not for every force.",
        ],
        "relationships": ["Force supplies one causal mechanism for the position, motion, speed, and stability relationships taught in Group 9."],
        "examples": ["A hand pushes a cart through contact; Earth gravitationally pulls a dropped ball without the hand or ground touching it during the fall."],
        "counterexamples": ["An object being at rest does not prove that no forces act; several forces can act with no visible change in motion."],
        "limits": ["This F1 concept does not yet calculate force, mass, acceleration, fields, or balanced-force vectors."],
        "vocabulary": [
            "force: a push or pull acting on an object through an interaction",
            "interaction: a relationship in which objects or systems affect one another",
            "contact force: a force transmitted through touching materials or objects",
            "noncontact force: a force that can act across a distance without direct touching",
        ],
        "near_concept_distinctions": ["Motion describes a change in position; force describes an interaction that can change motion or contribute to stability."],
        "scope_of_application": "Use to identify elementary forces and the interacting objects. Do not infer an invisible force merely because an object moved; support the interaction from observation or established knowledge.",
        "unresolved_questions": ["What is exerting the force, what receives it, and what evidence identifies the interaction?"],
        "explanation": "A push or pull is not only something a person does. It is an interaction in which one object or system acts on another. Some interactions require contact, while gravity and magnetism show that contact is not always necessary.",
        "application": "Wind pushes a sail because moving air interacts with its surface. The boat's motion is the effect to observe; the air-sail interaction is part of the causal explanation.",
        "analogies": ["Motion is the change shown on a map; force is one of the interactions that can alter the route or speed."],
        "questions": ["What is pushing or pulling what, and does that interaction require contact?"],
        "comparisons": ["A force is an interaction; motion is a state or change that may result from the combined interactions."],
        "participation": "The box moved after the hand contacted and pushed it. I would describe the hand-box interaction as the force and the box's changing position as the observed motion.",
        "correction_response": "If I equate visible motion with a single force or assume rest means no forces, I would separate the interaction from its net observed effect and name what remains unmeasured.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "ELA-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_pushes_pulls"],
        "source_refs": FORCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_force_strength_direction_v1",
        "title": "Pushes and pulls have strength and direction",
        "domain": "curriculum.f1.pushes_pulls_forces",
        "material": "A push or pull can be described by its strength and direction. Under suitably matched conditions, a stronger force can produce a larger change in an object's motion, while changing the force direction can change the direction of motion.",
        "principles": [
            "Describe direction relative to a stated reference rather than with an unanchored word such as forward.",
            "Compare stronger and weaker forces on the same kind of object under matched conditions.",
            "At this stage, investigate strength and direction separately before combining them into a more complete model.",
        ],
        "relationships": ["Force strength and direction extend fair comparison, reference frames, motion, speed, and cause-and-effect reasoning."],
        "examples": ["Using the same ball and surface, a stronger push may send the ball farther; pushing from another side changes its direction relative to the marked floor."],
        "counterexamples": ["A heavier object moving less far than a lighter object does not isolate force strength if the objects and conditions differ."],
        "limits": ["Everyday strong and weak are qualitative; precise magnitude, simultaneous vector components, mass dependence, and acceleration require later teaching."],
        "vocabulary": [
            "strength: the relative magnitude of a push or pull in a bounded comparison",
            "direction: the orientation in which a force acts relative to a reference",
            "effect: an observed change associated with a cause or interaction",
            "matched conditions: relevant circumstances kept sufficiently alike for comparison",
        ],
        "near_concept_distinctions": ["Force direction describes the interaction's orientation; motion direction describes how position is changing."],
        "scope_of_application": "Use for bounded qualitative comparisons with a shared object, surface, reference, and procedure. Do not generalize one result across different masses, shapes, or surfaces without further evidence.",
        "unresolved_questions": ["Did force strength change, force direction change, or did another condition account for the different motion?"],
        "explanation": "Pushes and pulls are not all alike. Their direction and relative strength help explain why the same object can start gently, move farther, or turn differently when the interaction changes.",
        "application": "A drawer pulled gently may open a little, while a stronger pull in the same direction may open it farther. A sideways force would not be the same comparison and could stress the guides instead.",
        "analogies": ["Strength and direction are like the length and orientation of an arrow, although precise force arrows belong to later modeling."],
        "questions": ["Which direction did the force act, how was strength compared, and what relevant condition stayed the same?"],
        "comparisons": ["Stronger and weaker compare magnitude; toward and away or left and right compare direction relative to a reference."],
        "participation": "With the same ball and surface, the stronger push produced the larger motion change in this trial. Direction was held the same, so it was not the changing factor.",
        "correction_response": "If I compare unmatched objects or combine strength and direction without controlling either, I would narrow the claim and redesign the comparison one variable at a time.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_pushes_pulls"],
        "source_refs": FORCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_force_changes_motion_v1",
        "title": "Forces can start, stop, speed up, slow, or turn motion",
        "domain": "curriculum.f1.pushes_pulls_forces",
        "material": "A force can change an object's motion by starting it from rest, stopping it, changing its speed, or changing its direction. The observed change depends on the interacting objects and the other forces and conditions present.",
        "principles": [
            "Compare motion before, during, and after the interaction.",
            "Name the specific change: start, stop, faster, slower, or changed direction.",
            "Do not assume the most visible push or pull is the only interaction affecting the result.",
        ],
        "relationships": ["This lesson connects Group 9 motion descriptions to cause, chronology, collision observations, and revisable system models."],
        "examples": ["A cue pushes a resting ball so it starts moving; when that ball contacts another ball, both balls' motions may change."],
        "counterexamples": ["Saying a force made something move does not fully describe whether it started, sped up, slowed, stopped, or turned."],
        "limits": ["F1 observations do not yet calculate net force, momentum, impulse, energy transfer, acceleration, or collision outcomes."],
        "vocabulary": [
            "at rest: not changing position relative to the stated reference",
            "start: change from rest to motion",
            "stop: change from motion to rest relative to the reference",
            "turn: change the direction of motion",
        ],
        "near_concept_distinctions": ["Speed change alters how quickly position changes; direction change alters where the motion is headed; either can occur without the other."],
        "scope_of_application": "Use to describe observable motion changes associated with elementary pushes, pulls, and contacts. Preserve other interactions and measurement limits.",
        "unresolved_questions": ["Which part of the motion changed, and which other forces or conditions could also have contributed?"],
        "explanation": "Force effects become clearer when we name the exact before-and-after motion. An object may begin moving, come to rest, change speed, or turn, and more than one interaction can contribute.",
        "application": "A bicycle brake produces contact interactions that slow the wheel. The slowing is the motion change; a full explanation would also include the rider, tire, road, and other forces.",
        "analogies": ["A force can edit different parts of a motion description: whether it moves, how fast it moves, or which way it moves."],
        "questions": ["Was the object initially at rest or moving, and exactly what changed after the force acted?"],
        "comparisons": ["Starting and stopping change the rest/motion state; speeding and slowing change rate; turning changes direction."],
        "participation": "The ball was already moving, so the racquet did not simply make it move. The contact changed its direction and may also have changed its speed.",
        "correction_response": "If I describe the wrong kind of motion change or assign it to one unsupported cause, I would return to the before-and-after observations and revise the causal claim.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ELA-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_pushes_pulls"],
        "source_refs": FORCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_surface_shape_motion_effects_v1",
        "title": "Surface and object properties affect a force's motion result",
        "domain": "curriculum.f1.pushes_pulls_forces",
        "material": "The same bounded push or pull can produce different motion when the object's shape, mass, contact area, or surface changes. Friction is a contact interaction that resists relative motion between touching surfaces and commonly contributes to slowing.",
        "principles": [
            "Change one relevant feature at a time when testing shape or surface effects.",
            "Describe the observed distance, speed, or stopping behavior before explaining it with friction.",
            "A rougher surface often increases resistance in an elementary comparison, but surface behavior depends on the materials and conditions.",
        ],
        "relationships": ["This applies material properties, fair comparison, measurement, friction, and force effects to a shared physical system."],
        "examples": ["The same block may travel less far across a rug than across a smooth floor after comparable pushes because the surface interaction differs."],
        "counterexamples": ["Rough always means more friction is too broad; lubrication, deformation, rolling, material pairing, and scale can change the result."],
        "limits": ["This is an experiential friction foundation, not a coefficient model; drag, rolling resistance, deformation, and detailed contact mechanics remain later topics."],
        "vocabulary": [
            "friction: a contact interaction that resists relative motion between touching surfaces",
            "surface: the outer boundary where an object can contact its surroundings",
            "resistance: opposition to a particular change or motion",
            "contact area: the region over which surfaces touch",
        ],
        "near_concept_distinctions": ["Friction is an interaction between surfaces; roughness is one surface property that can influence but does not alone determine friction."],
        "scope_of_application": "Use for bounded observations comparing the same object and force procedure across surfaces or shapes. Hold universal friction claims and precise calculations for later instruction.",
        "unresolved_questions": ["Did the surface, shape, mass, contact area, or force procedure change enough to explain the result?"],
        "explanation": "A push does not act in isolation. The object and surrounding surfaces are part of the system, so changing their properties can change how far or fast the object moves and how quickly it slows.",
        "application": "A wheeled cart rolls differently on tile and deep carpet. A fair test would use the same cart, load, direction, and push procedure before attributing the difference to the surface interaction.",
        "analogies": ["The route matters as well as the traveler: the same effort produces different progress on pavement, sand, or mud."],
        "questions": ["What stayed the same, which object or surface property changed, and what motion difference was measured?"],
        "comparisons": ["Force describes the push or pull; friction describes one resisting contact interaction within the system."],
        "participation": "The block stopped sooner on the rug under the same procedure. That supports a surface effect here; I would avoid claiming every rough material behaves identically.",
        "correction_response": "If an uncontrolled shape, mass, or push difference explains the result, I would narrow the surface claim and repeat the test with matched conditions.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_pushes_pulls"],
        "source_refs": FORCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_gravity_magnetism_noncontact_v1",
        "title": "Gravity and magnetism show that forces can act without contact",
        "domain": "curriculum.f1.pushes_pulls_forces",
        "material": "Gravity and magnetic force are examples of noncontact interactions. Near Earth's surface, gravity pulls objects toward Earth. Magnets can attract certain materials and can attract or repel other magnets depending on their relative poles and arrangement.",
        "principles": [
            "Not seeing contact does not mean no interaction exists, but the force type still needs evidence.",
            "Gravity is attractive in this foundation; magnetic interactions can attract or repel.",
            "Not every metal or object responds to an ordinary magnet in the same way.",
        ],
        "relationships": ["Noncontact forces expand the push/pull model while connecting materials, evidence, invisible causes, and later field models."],
        "examples": ["A released ball accelerates toward Earth without a hand pulling it; two bar magnets may move together or apart without touching first."],
        "counterexamples": ["A magnet not attracting an aluminum object does not show that aluminum is not a metal; magnetic response and material category are different properties."],
        "limits": ["F1 does not explain gravitational or magnetic fields, orbital motion, microgravity, electromagnetism, magnetic domains, or quantitative force laws."],
        "vocabulary": [
            "gravity: the attractive interaction between masses, described near Earth as a pull toward Earth",
            "magnet: an object that produces magnetic interactions",
            "attract: act so objects tend to move toward one another",
            "repel: act so objects tend to move away from one another",
        ],
        "near_concept_distinctions": ["Invisible describes lack of direct sight; noncontact describes an interaction that does not require the objects to touch."],
        "scope_of_application": "Use gravity and ordinary magnets as bounded examples of noncontact force. Do not infer magnetism for every unexplained motion or generalize magnetic attraction to all metals.",
        "unresolved_questions": ["Which noncontact interaction is proposed, and what observation would distinguish it from airflow, vibration, contact, or another cause?"],
        "explanation": "Forces do not always need visible touching. Falling and magnetic motion provide observable effects of interactions across a distance, but the kind of force and the materials involved still matter.",
        "application": "A compass needle turns near a magnet without contact. That is evidence of a magnetic interaction in the setup, not evidence that every nearby object is magnetic.",
        "analogies": ["A noncontact force is known through its effects much like wind can be inferred from moving leaves, while the proposed cause still needs a fitting test."],
        "questions": ["What moved without contact, and what controlled comparison identifies gravity or magnetism as the best-supported cause?"],
        "comparisons": ["Gravity provides an attractive interaction between masses; magnets can produce both attraction and repulsion in bounded arrangements."],
        "participation": "The paper clip moved toward the nearby magnet before touching it, which supports a magnetic pull. I would test nonmagnetic objects too rather than treat every material as magnetically attracted.",
        "correction_response": "If another cause fits the motion or the material does not respond as predicted, I would revise the force classification and preserve only the observed movement.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_pushes_pulls"],
        "source_refs": FORCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_force_motion_design_iteration_v1",
        "title": "Force and motion knowledge can guide a tested design",
        "domain": "curriculum.f1.pushes_pulls_forces",
        "material": "An elementary force-and-motion design begins with a desired motion, selects a way to push or pull, predicts the result, tests it safely, and revises the design from observed evidence. Success is judged against the stated goal and constraints rather than appearance alone.",
        "principles": [
            "State the desired start, stop, speed, direction, or path before designing.",
            "Use material, shape, surface, force direction, and relative strength as testable design choices.",
            "Treat an unexpected result as information for revision rather than personal failure.",
        ],
        "relationships": ["This integrates algorithms, material suitability, models, predictions, fair testing, force effects, metacognitive reopening, and graceful correction."],
        "examples": ["A miniature course can be designed so a gentle push moves a ball around a barrier and stops near a target, then revised after measured trials."],
        "counterexamples": ["Changing the ball, surface, slope, obstacle, and push at once makes it difficult to know which revision improved the result."],
        "limits": ["Safety-critical devices, powered machinery, structural loads, human testing, and precise performance require qualified standards and later engineering knowledge."],
        "vocabulary": [
            "design: a plan for meeting a stated need or goal under constraints",
            "criterion: a feature used to judge whether a design meets its goal",
            "trial: one bounded implementation or test under stated conditions",
            "iteration: a revised attempt informed by evidence from an earlier attempt",
        ],
        "near_concept_distinctions": ["A prediction states the expected motion; a design arranges components and interactions to pursue that motion; a test supplies evidence about the fit."],
        "scope_of_application": "Use for safe elementary planning and synthetic or ordinary-object trials. Escalate any hazardous, embodied, or safety-critical design to appropriate expertise and safeguards.",
        "unresolved_questions": ["Which single revision is most likely to improve the named criterion, and what observation would show whether it did?"],
        "explanation": "Understanding pushes and pulls becomes useful when it helps us deliberately shape motion. A good design makes the goal visible, changes bounded features, checks the outcome, and learns from mismatch.",
        "application": "To keep a cabinet door from slamming, a model can test resistance and closing speed with safe lightweight parts. A real installation still needs appropriate hardware guidance and safety checks.",
        "analogies": ["Design iteration is like steering: each observation shows whether the next bounded adjustment should continue, turn, or stop."],
        "questions": ["What motion do we want, which force interaction could produce it, and what result would make us revise the design?"],
        "comparisons": ["A demonstration shows an effect; a design uses understood effects to meet a criterion under constraints."],
        "participation": "The ball overshot the target, so I would keep the course layout and test a gentler push before changing several features at once. The mismatch tells us where to revise.",
        "correction_response": "If a trial contradicts the prediction, I would record the result, inspect the assumptions and conditions, and change the smallest relevant part before retesting.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "ENG-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_k_pushes_pulls"],
        "source_refs": FORCE_REFS,
    },
)
