from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_materials_change_motion_v1"
GROUP_KEY = "f1_materials_change_motion_group_9"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
SCIENCE_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_science_literacy",
    "sha256:5afe8cbcbba843083bc063247db128e71188d78eb86844f5b2b20d4a0774449a",
    "https://www.coreknowledge.org/wp-content/uploads/2024/08/CKSci_G1U7_ScienceForEveryone_Unit_Materials_W1.zip",
    "license:CC-BY-NC-SA-4.0",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["SCI-0", "SCI-1", "MATH-1", "ELA-1", "ELA-2", "ENG-1", "HIST-1", "RES-1", "LOGIC-1"],
    "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_science_literacy"],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_objects_materials_properties_v1",
        "title": "Objects are made from materials with observable properties",
        "domain": "curriculum.f1.materials_change_motion",
        "material": "An object is a particular thing, while a material is matter used to make all or part of an object. Materials can be described by observable or measurable properties such as hardness, flexibility, texture, shape behavior, length, or mass.",
        "principles": [
            "Name the object separately from the material or materials used to make it.",
            "Describe a property through an observation, comparison, or named measurement rather than an unsupported label.",
            "One object may contain several materials, and one material may be used in many kinds of objects.",
        ],
        "relationships": ["This distinction extends observation versus interpretation and supports comparison, measurement, classification, and design."],
        "examples": ["A drinking cup is an object; it might be made from glass, metal, paper, or plastic, each with properties relevant to its use."],
        "counterexamples": ["Calling every rigid object metal confuses an observed property with the material's identity."],
        "limits": ["A visible property may not identify a material uniquely, and hidden composition may require an appropriate test or source."],
        "vocabulary": [
            "object: a particular thing that can be observed or used",
            "material: matter used to make all or part of an object",
            "property: a feature that can be described, compared, or measured",
            "texture: how a surface feels or appears at a chosen scale",
        ],
        "near_concept_distinctions": ["An object has a particular form and purpose; a material is what some or all of that object is made from."],
        "scope_of_application": "Use for elementary description, sorting, comparison, and design questions. Do not infer exact composition or safety from appearance alone.",
        "unresolved_questions": ["Which property is directly observable, and which test would distinguish materials that look alike?"],
        "explanation": "Keeping the thing separate from what it is made of makes descriptions clearer. We can then compare the relevant properties of its materials without assuming one surface feature tells us the whole composition.",
        "application": "A raincoat is an object assembled from fabric, coatings, thread, and fasteners. Its outer material can be compared for flexibility and resistance to water without assuming every part has the same properties.",
        "analogies": ["An object is like a built structure, while its materials are the bricks, wood, glass, or metal selected to form it."],
        "questions": ["What is the object, what materials can we supportably identify, and which properties did we observe?"],
        "comparisons": ["Object names identify particular things or kinds of things; material names identify what those things are made from."],
        "participation": "The bottle is the object, and the clear wall appears to be one of its materials. I can describe the wall as rigid and transparent, but I would check a label or test before naming the exact material.",
        "correction_response": "If I mistake a property for a material or treat the whole object as one substance, I would separate the object, its parts, the observations, and the still-uncertain composition.",
        "families": ["SCI-0", "SCI-1", "ELA-1", "ELA-2"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_science_literacy"],
        "source_refs": SCIENCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_property_comparison_measurement_v1",
        "title": "Material properties need a shared basis for comparison",
        "domain": "curriculum.f1.materials_change_motion",
        "material": "Properties become useful evidence when the compared feature and basis are clear. Everyday descriptions such as harder, softer, more flexible, heavier, longer, or more absorbent refer to a relationship between named cases or to a measurement made under stated conditions.",
        "principles": [
            "Compare the same property in both cases.",
            "Use a shared observation, procedure, unit, or scale when the claim depends on degree.",
            "Keep relevant conditions visible because a material can behave differently when its thickness, shape, temperature, or treatment changes.",
        ],
        "relationships": ["Property comparison applies the existing fair-comparison and measurement foundations to physical materials."],
        "examples": ["To compare how flexible two strips are, use strips of similar length and thickness and bend them with the same bounded procedure."],
        "counterexamples": ["A thick cardboard panel and a thin paper strip do not isolate material flexibility if their shapes and thicknesses also differ."],
        "limits": ["Some properties require instruments, safe procedures, or specialist knowledge; one simple classroom comparison does not establish performance in every condition."],
        "vocabulary": [
            "rigid: resistant to bending under the stated conditions",
            "flexible: able to bend without immediately breaking under the stated conditions",
            "absorbent: able to take in a liquid under the stated conditions",
            "comparison basis: the shared property, method, unit, or reference used to compare cases",
        ],
        "near_concept_distinctions": ["A qualitative comparison uses descriptive relations such as more flexible; a quantitative comparison uses a named number, unit, or scale."],
        "scope_of_application": "Use to make bounded elementary material comparisons. Name the cases, property, procedure, and any condition likely to affect the result.",
        "unresolved_questions": ["Would the comparison remain the same if thickness, temperature, shape, or exposure changed?"],
        "explanation": "A property word is not enough by itself. A useful comparison says what feature is being compared, how it was checked, and which surrounding conditions might also explain the difference.",
        "application": "If two cloths are being considered for cleanup, equal-sized samples can receive equal amounts of water before their absorption is compared. That result is bounded to those samples and conditions.",
        "analogies": ["Comparing properties without a shared basis is like measuring one table in inches and another by footsteps without explaining the conversion."],
        "questions": ["Which property are we comparing, and did both materials receive the same relevant test?"],
        "comparisons": ["A description names a feature; a fair comparison makes a bounded claim about how that feature relates across cases."],
        "participation": "This sample bent farther in the same test, so it was more flexible under these conditions. I would not generalize that result to every thickness or temperature yet.",
        "correction_response": "If the comparison changed more than the intended property, I would narrow the claim and repeat it with a shared basis rather than defend the first result.",
        "families": ["SCI-0", "SCI-1", "MATH-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_science_literacy"],
        "source_refs": SCIENCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_solids_liquids_shape_behavior_v1",
        "title": "Solids and liquids differ in how they hold shape",
        "domain": "curriculum.f1.materials_change_motion",
        "material": "A solid generally keeps its own shape under ordinary conditions, although it may bend, stretch, break, or be reshaped. A liquid flows and takes the shape of the part of its container that it occupies while keeping a quantity of material.",
        "principles": [
            "Classify by observed shape behavior under stated conditions, not by whether something feels hard, soft, wet, or dry.",
            "Soft and flexible materials can still be solids.",
            "Changing container shape changes a liquid's form without automatically changing how much liquid is present.",
        ],
        "relationships": ["Shape behavior connects material properties to geometry, measurement, containers, change, and later study of states of matter."],
        "examples": ["Fabric and clay are solids even though one folds and the other can be molded; water is a liquid because it flows and takes its container's shape."],
        "counterexamples": ["Softness does not make fabric a liquid, and pouring many small solid grains does not by itself establish that each grain is liquid."],
        "limits": ["This F1 distinction describes ordinary observable behavior; gases, mixtures, very slow flow, melting, freezing, and microscopic explanations require later teaching."],
        "vocabulary": [
            "solid: matter that generally keeps its own shape under stated ordinary conditions",
            "liquid: matter that flows and takes the shape of its container under stated ordinary conditions",
            "container: an object that holds or bounds material",
            "flow: continuous movement in which parts of a material change position relative to one another",
        ],
        "near_concept_distinctions": ["State describes characteristic physical behavior; texture describes a surface property and does not decide the state by itself."],
        "scope_of_application": "Use for bounded everyday classification under ordinary conditions. Hold unusual substances, phase changes, and microscopic mechanisms for better-fitting evidence.",
        "unresolved_questions": ["Is the observed behavior stable over time and conditions, or is the material changing state or behaving as a mixture?"],
        "explanation": "The useful difference is how the material behaves. A solid can be soft or bendable and still keep a form, while a liquid flows into the available shape of its container.",
        "application": "Modeling clay can be pressed into a new form but remains a solid piece; paint can flow across a tray and match the tray's surface until drying changes the material present.",
        "analogies": ["A solid carries a shape of its own, while a liquid borrows the available shape of its container."],
        "questions": ["Does the sample keep a form, flow into a container, or change while we observe it?"],
        "comparisons": ["Solidity is not the same as hardness, and liquidity is not the same as wetness."],
        "participation": "The rubber band is flexible, but it is still a solid because it remains one shaped piece. The water flows and takes the cup's shape, so it behaves as a liquid here.",
        "correction_response": "If I classify by a misleading surface word such as soft or wet, I would return to the observed shape behavior and state the conditions and unresolved cases.",
        "families": ["SCI-0", "SCI-1", "ELA-1", "MATH-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_science_literacy"],
        "source_refs": SCIENCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_material_suitability_design_v1",
        "title": "A useful material fits the purpose and constraints",
        "domain": "curriculum.f1.materials_change_motion",
        "material": "Material selection connects a desired function to relevant properties and constraints. A material that is useful for one part or purpose may be unsuitable for another, so there is not always one universally best material.",
        "principles": [
            "State the purpose or problem before judging a material choice.",
            "Connect each important requirement to an observed or supported property.",
            "Compare tradeoffs such as stiffness and flexibility, strength and weight, durability and ease of shaping, or performance and available resources.",
        ],
        "relationships": ["Material suitability integrates properties, fair comparison, algorithms, models, engineering constraints, and evidence-based explanation."],
        "examples": ["Sturdy cardboard may support a model's base while flexible wire may work better for a narrow curved connector."],
        "counterexamples": ["A material described as strong is not automatically best if the task also requires transparency, low mass, flexibility, or safe handling."],
        "limits": ["Real design decisions may require safety standards, cost, environmental effects, manufacturing knowledge, and tests beyond an F1 comparison."],
        "vocabulary": [
            "function: what an object or part is intended to do",
            "requirement: a condition a solution needs to meet",
            "constraint: a limit on possible solutions",
            "tradeoff: a choice in which improving one relevant feature may reduce another",
        ],
        "near_concept_distinctions": ["A property describes supported behavior; suitability judges whether that behavior fits a named purpose and conditions."],
        "scope_of_application": "Use for elementary design explanations and material comparisons. Treat safety-critical and specialist choices as requiring appropriate standards and evidence.",
        "unresolved_questions": ["Which requirement matters most here, and what test would show whether the material meets it?"],
        "explanation": "Materials are selected for jobs, not ranked in isolation. The choice becomes explainable when the job, relevant properties, constraints, and tradeoffs are all visible.",
        "application": "A reusable bag needs to carry a load, bend for storage, and survive repeated use. A rigid sheet might be sturdy but fail the storage requirement, while a fabric should still be tested for load and durability.",
        "analogies": ["Choosing a material is like choosing a tool: the best choice depends on the job rather than one feature being best everywhere."],
        "questions": ["What must this part do, which property supports that function, and what tradeoff remains?"],
        "comparisons": ["A property claim describes a material; a suitability claim connects that property to a purpose and constraints."],
        "participation": "Cardboard fits the base because it holds its shape, but it would be awkward for the flexible connector. I would choose by each part's job rather than use one material everywhere.",
        "correction_response": "If a requirement changes or testing contradicts the expected property, I would revise the selection while preserving the still-valid observations and constraints.",
        "families": ["SCI-0", "SCI-1", "ENG-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_science_literacy"],
        "source_refs": SCIENCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_change_stability_over_time_v1",
        "title": "Change and stability require comparison over time",
        "domain": "curriculum.f1.materials_change_motion",
        "material": "Something changes when a selected observable property or relationship differs between observations over time. Something is stable when the relevant feature remains sufficiently alike across the stated interval and scale.",
        "principles": [
            "Name what was observed before and after and which feature is being compared.",
            "Separate a change in the object or system from a change in viewpoint, instrument, label, or surrounding condition.",
            "Stable means sufficiently unchanged for the stated feature, interval, and purpose, not incapable of ever changing.",
        ],
        "relationships": ["Change and stability build on chronology, measurement, observation, systems, and revisable explanations."],
        "examples": ["A wet painted surface becoming dry is a supported change when its observed behavior differs later; the table beneath it may remain stable for the feature being tracked."],
        "counterexamples": ["Seeing an object from another angle does not by itself prove that the object changed."],
        "limits": ["Slow, small, hidden, reversible, or measurement-sensitive changes may not be detected by a brief ordinary observation."],
        "vocabulary": [
            "change: a supported difference in a selected feature or relationship over time",
            "stable: sufficiently unchanged in the selected feature across a stated interval and scale",
            "interval: the span between observations",
            "baseline: an earlier observation or reference used for comparison",
        ],
        "near_concept_distinctions": ["Change describes a difference over time; cause explains what helped produce that difference and needs additional evidence."],
        "scope_of_application": "Use for elementary observations of objects and systems over time. State the feature, interval, comparison basis, and detection limits before explaining a cause.",
        "unresolved_questions": ["Did the system change, or did the observation conditions or viewpoint change?"],
        "explanation": "Change is a relationship between observations, not merely a feeling that something looks different. We identify the feature and time interval, compare it consistently, and keep the cause separate until evidence supports it.",
        "application": "A puddle is smaller one hour later when its boundary is measured from the same marked points. That supports a size change; evaporation is a possible explanation to connect with weather and other evidence.",
        "analogies": ["A before-and-after comparison is like two frames of a film: their difference can reveal change, while the missing frames may still hide the cause."],
        "questions": ["What feature changed, over what interval, and what remained stable enough to make the comparison meaningful?"],
        "comparisons": ["Chronology establishes before and after; change identifies a supported difference; causation explains why it occurred."],
        "participation": "The mark is lower than it was an hour ago, so the measured level changed. I would keep the cause provisional until we check leaks, evaporation, and the observation conditions.",
        "correction_response": "If the apparent change came from a shifted viewpoint or inconsistent measure, I would withdraw the change claim and repeat the observation from a stable reference.",
        "families": ["SCI-0", "SCI-1", "MATH-1", "HIST-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_science_literacy"],
        "source_refs": SCIENCE_REFS,
    },
    {
        "concept_key": "curriculum_f1_motion_position_speed_v1",
        "title": "Motion is described through changing position and speed",
        "domain": "curriculum.f1.materials_change_motion",
        "material": "Motion is a change in position relative to a stated reference over time. Speed describes how quickly position changes; at F1 it can be compared as faster or slower when distance, time, and observation conditions provide a fair basis.",
        "principles": [
            "Name the reference used to describe position and motion.",
            "Use observations at more than one time to support that position changed.",
            "Compare speed fairly by keeping distance or time clear rather than judging from appearance alone.",
        ],
        "relationships": ["Motion connects spatial position, chronology, elapsed time, distance measurement, change, and fair comparison."],
        "examples": ["Two carts traveling the same marked distance can be compared by the time each takes; the cart using less time is faster in that trial."],
        "counterexamples": ["An object appearing smaller does not prove it moved away if the observer, camera zoom, or object size changed."],
        "limits": ["Relative motion depends on the chosen reference; changing direction, uneven speed, acceleration, force, and precise rate calculations require later instruction."],
        "vocabulary": [
            "position: location described relative to a reference",
            "motion: change in position relative to a reference over time",
            "speed: how quickly position changes",
            "reference: a stated object, point, or frame used to describe position or motion",
        ],
        "near_concept_distinctions": ["Position describes where something is relative to a reference; motion describes a change in that relationship; speed describes how quickly it changes."],
        "scope_of_application": "Use for elementary descriptions and fair faster/slower comparisons. Preserve the chosen reference and hold force, acceleration, and complex trajectories for later teaching.",
        "unresolved_questions": ["Which reference, distance, and time interval make this motion claim checkable?"],
        "explanation": "We can tell that something moved only relative to a reference and across time. Saying it was faster also needs a shared basis, such as covering the same distance in less time.",
        "application": "A cloud changes position relative to a building between two timed photographs. Comparing its speed with another cloud requires the photographs to represent a suitable shared distance, time, and viewpoint.",
        "analogies": ["A reference is the fixed grid behind an animation: without it, the changing location is harder to describe consistently."],
        "questions": ["Relative to what did the position change, and what shared distance or time supports the speed comparison?"],
        "comparisons": ["Change is the broad idea of becoming different; motion is specifically a change in position; speed describes the rate of that positional change."],
        "participation": "The ball moved from the line toward the wall relative to the floor marks. It reached the same finish line sooner than the other ball, so it was faster in this trial.",
        "correction_response": "If I omit the reference or compare different distances and times, I would narrow the claim and repeat the comparison with the missing basis made explicit.",
        "families": ["SCI-0", "SCI-1", "MATH-1", "ELA-1", "RES-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_science_literacy"],
        "source_refs": SCIENCE_REFS,
    },
)
