from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_simple_machines_v1"
GROUP_KEY = "f1_simple_machines_group_12"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
MACHINE_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_simple_machines",
    "sha256:0af5b29eeeaee370eaec9a7e468200448243068466f354216cf50bf58a8d6792",
    "https://www.coreknowledge.org/wp-content/uploads/2020/08/CKSci_G1U4_Simple-Machines_W2.zip",
    "license:CC-BY-NC-SA-4.0",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ELA-1", "ELA-2", "ENG-1", "RES-1", "LOGIC-1"],
    "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_simple_machines"],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_machine_task_force_tradeoff_v1",
        "title": "A machine changes how forces are applied to help perform a task",
        "domain": "curriculum.f1.simple_machines",
        "material": "A machine is a human-designed arrangement used to help perform a task. A simple machine can change the direction of a force or trade a smaller force across a longer distance for a larger force across a shorter distance. It does not create energy or make every part of a task smaller.",
        "principles": [
            "Name the task, input action, machine arrangement, and resulting output action.",
            "Describe what became easier: required force, direction, control, distance, or access.",
            "Compare the same task with and without the machine before making a benefit claim.",
        ],
        "relationships": ["This applies Groups 9-11 material, motion, force, distance, fair-test, and design foundations to human-made systems."],
        "examples": ["A ramp can let a person raise a load with a smaller push while moving it over a longer path."],
        "counterexamples": ["Calling a machine easier does not mean it removes all effort, shortens every distance, creates energy, or is safest for every user and setting."],
        "limits": ["F1 does not calculate work, mechanical advantage, energy, power, efficiency, torque, stress, or machine ratings."],
        "vocabulary": [
            "machine: a designed arrangement that helps perform a task",
            "task: the intended change or outcome",
            "input: the action or resource supplied to a system",
            "output: the resulting action or change produced by the system",
        ],
        "near_concept_distinctions": ["Every tool can help with a task, but not every tool is classified as a simple machine; classification depends on the mechanism, not usefulness alone."],
        "scope_of_application": "Use to describe safe ordinary mechanisms and qualitative force-direction or force-distance tradeoffs. Do not authorize powered equipment, lifting people, structural loads, or safety-critical operation.",
        "unresolved_questions": ["What task is being performed, what force or motion enters the arrangement, and what changes at the output?"],
        "explanation": "A machine helps by reorganizing an interaction. It may let us push instead of lift, use a smaller force over a longer path, or control motion more effectively, but the benefit has a tradeoff and context.",
        "application": "A jar lid increases the effective turning radius available to the hand. Describing the input turn and the lid's resulting turn is more informative than saying the lid works by magic.",
        "analogies": ["A machine is like a route planner for force: it can change the path or direction without creating the traveler."],
        "questions": ["What became easier, what tradeoff appeared, and under which matched conditions?"],
        "comparisons": ["Everyday effort describes how demanding a task feels; scientific work has a later quantitative definition and should not be casually treated as disappearing."],
        "participation": "The device reduced the force needed in this comparison, but the input moved farther. I would call that a useful tradeoff for the stated task, not free energy.",
        "correction_response": "If I claim a machine reduces everything at once, I would identify the changed force, distance, direction, control, and losses separately and narrow the claim.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ENG-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_simple_machines"],
        "source_refs": MACHINE_REFS,
    },
    {
        "concept_key": "curriculum_f1_inclined_plane_ramp_v1",
        "title": "An inclined plane trades a longer path for a smaller required force",
        "domain": "curriculum.f1.simple_machines",
        "material": "An inclined plane is a sloped surface connecting different heights. Under matched conditions, moving a load along a longer, gentler ramp can require less force than lifting it directly, while friction, surface, slope, load, and travel distance still affect the result.",
        "principles": [
            "Compare the same load and height when investigating different ramps.",
            "Measure or describe both required force and path distance rather than observing only arrival at the top.",
            "Include friction, stability, accessibility, and safe slope in the system description.",
        ],
        "relationships": ["Ramps connect spatial geometry, length, gravity, surface friction, force strength, accessibility, and fair comparison."],
        "examples": ["A long loading ramp can allow a cart to reach a platform with less applied force than a direct vertical lift, although it travels farther."],
        "counterexamples": ["A steeper or rougher ramp is not automatically easier merely because it is still a ramp."],
        "limits": ["F1 does not calculate ramp angle, ideal mechanical advantage, friction coefficients, load ratings, or accessibility-code compliance."],
        "vocabulary": [
            "inclined plane: a sloped surface used to connect different heights",
            "slope: how steeply a surface rises or falls over distance",
            "load: the object or material being moved or supported",
            "tradeoff: gaining one useful property while accepting a cost or change elsewhere",
        ],
        "near_concept_distinctions": ["A ramp changes the path to a height; a wedge is a moving or applied inclined shape used to separate, cut, or hold materials."],
        "scope_of_application": "Use for lightweight models, ordinary access reasoning, and qualitative comparisons. Real ramps carrying people, vehicles, or heavy loads require applicable codes, ratings, and qualified design.",
        "unresolved_questions": ["Were load, height, surface, and procedure matched, and how did both force and distance change?"],
        "explanation": "A ramp spreads a height change across a path. A gentler path can lower the force needed at one moment, but it increases travel distance and remains affected by friction and stability.",
        "application": "A movable cart may be easier to guide up a suitable ramp than to lift onto a step. The design must still fit the user, load, surface, available space, and safety requirements.",
        "analogies": ["A ramp turns one large step into many smaller rises spread across distance."],
        "questions": ["How high must the load move, how long is the path, and what other conditions change the required force?"],
        "comparisons": ["Direct lifting uses a shorter vertical path; a ramp uses a longer sloped path that may require a smaller applied force."],
        "participation": "The gentler ramp required less pull for the same model load and height, but the load traveled farther. That is the supported tradeoff in this test.",
        "correction_response": "If the ramp performs worse, I would inspect slope, friction, load stability, and measurement before treating the inclined-plane relationship as disproven.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ENG-1", "RES-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_simple_machines"],
        "source_refs": MACHINE_REFS,
    },
    {
        "concept_key": "curriculum_f1_wheel_axle_gears_rotation_v1",
        "title": "Wheels, axles, and gears connect rotation and motion",
        "domain": "curriculum.f1.simple_machines",
        "material": "A wheel and axle are connected rotating parts: when one turns, the other turns with it. Wheels can reduce sliding resistance for transport, while wheel-and-axle arrangements and meshing gears can transmit rotation, change turning direction, or trade turning force and speed under bounded conditions.",
        "principles": [
            "Identify which part is the wheel, axle, or gear and how the parts are connected.",
            "Observe the direction and amount of rotation at input and output before explaining the benefit.",
            "Distinguish rolling contact from an axle arrangement and from gears meshing by teeth.",
        ],
        "relationships": ["This connects circular geometry, relative motion, friction, force, components, input/output, and simple system models."],
        "examples": ["Turning a doorknob rotates its axle; meshed gears rotate together, with adjacent gears turning in opposite directions."],
        "counterexamples": ["A round object is not automatically a functional wheel and axle; it must participate in the relevant connected rotation and task."],
        "limits": ["F1 does not calculate gear ratios, angular velocity, torque, bearing friction, tooth geometry, drivetrain loads, or failure modes."],
        "vocabulary": [
            "wheel: a circular component that rotates around a center",
            "axle: a central rod or shaft connected to rotation",
            "gear: a toothed rotating component that meshes with another gear",
            "rotation: turning around an axis or center",
        ],
        "near_concept_distinctions": ["A wheel can roll across a surface; an axle is the shaft involved in its rotation; a gear transmits rotation through meshing teeth."],
        "scope_of_application": "Use for safe, exposed, lightweight models and ordinary mechanism identification. Guarded machinery, vehicles, powered drivetrains, and load-bearing systems require qualified procedures and must not be operated from this knowledge alone.",
        "unresolved_questions": ["Which component receives the input turn, how are the parts coupled, and what motion appears at the output?"],
        "explanation": "Connected rotating parts let motion be carried and reshaped through a device. Their usefulness depends on where the force enters, how the parts touch or join, and what output the task requires.",
        "application": "A hand-crank spool uses a wheel-like handle and axle to wind a line. A safe model can show the motion path without implying that a real hoist is rated for lifting a person.",
        "analogies": ["Connected rotating parts pass motion like linked conversational turns, but each component can change the direction or scale of the next turn."],
        "questions": ["What turns first, what turns with it, and does the connection use a shaft, surface contact, or gear teeth?"],
        "comparisons": ["Rolling can reduce sliding friction; a wheel and axle couples rotations; gears transfer rotation through teeth."],
        "participation": "The handle and shaft rotate together, so this is a wheel-and-axle arrangement. I would inspect the rest of the mechanism before claiming how much force it changes.",
        "correction_response": "If the output turns differently than expected, I would trace every connection, contact direction, slipping point, and fixed component before revising the model.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ENG-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_simple_machines"],
        "source_refs": MACHINE_REFS,
    },
    {
        "concept_key": "curriculum_f1_lever_fulcrum_arms_v1",
        "title": "A lever turns around a fulcrum to relate input and load motion",
        "domain": "curriculum.f1.simple_machines",
        "material": "A lever is a relatively rigid bar or arm that turns around a support point or region called a fulcrum. The locations of the input force, fulcrum, and load affect the directions and relative distances and forces in the motion.",
        "principles": [
            "Identify the lever, fulcrum, input location, and load before predicting motion.",
            "Use relative position and distance from the fulcrum rather than assuming every lever behaves like a seesaw.",
            "Keep hands and bodies away from pinch, snap, launch, and falling-load paths.",
        ],
        "relationships": ["Levers integrate reference points, balance, rotation, force direction, distance, prediction, and safe mechanical design."],
        "examples": ["Pressing one side of a seesaw down raises the other side around the fulcrum; a bottle opener uses another arrangement of fulcrum, input, and load."],
        "counterexamples": ["The fulcrum is not always centered, and the input and load are not always on opposite sides."],
        "limits": ["F1 does not classify all lever classes, calculate moments or torque, model flexible members, or rate tools and structures."],
        "vocabulary": [
            "lever: a bar or arm that turns around a support to help perform a task",
            "fulcrum: the support point or region around which a lever turns",
            "lever arm: a section or distance associated with the lever and fulcrum arrangement",
            "load: the object or resistance the lever is intended to move or affect",
        ],
        "near_concept_distinctions": ["A lever is the moving bar or arm; the fulcrum is the support around which it turns; the load is what the system acts on."],
        "scope_of_application": "Use for safe lightweight models and ordinary mechanism recognition. Do not pry live electrical equipment, launch objects, lift people, or exceed a tool or structure rating.",
        "unresolved_questions": ["Where are the input, fulcrum, and load, and which direction should each part move?"],
        "explanation": "A lever relates motions around a support. Changing where the input, load, or fulcrum sits changes the distance each part travels and the force relationship.",
        "application": "A claw hammer can act as a lever while removing a nail, but the material, tool condition, fulcrum surface, and flying or pinching hazards still matter.",
        "analogies": ["The fulcrum is the pivot in an argument: moving the supporting point changes how the same inputs balance and affect the result."],
        "questions": ["What acts as the lever and fulcrum, where is force applied, and where could a pinch or launch path appear?"],
        "comparisons": ["A ramp spreads motion along a slope; a lever turns around a fulcrum."],
        "participation": "The bar rotates around this support, the input moves down, and the load rises. I would call it a lever model and keep the claim qualitative until distances and forces are measured.",
        "correction_response": "If I identify the wrong fulcrum or predict the wrong direction, I would redraw the actual contact points and trace rotation from the input before trying again.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ENG-1", "RES-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_simple_machines"],
        "source_refs": MACHINE_REFS,
    },
    {
        "concept_key": "curriculum_f1_pulley_wedge_screw_force_direction_v1",
        "title": "Pulleys, wedges, and screws redirect force through different shapes",
        "domain": "curriculum.f1.simple_machines",
        "material": "A fixed pulley can redirect a pull across a grooved wheel and line. A wedge uses sloping surfaces to redirect an applied force outward, while a screw is an inclined shape wrapped around a cylinder that relates turning motion to motion along its length. Each mechanism must be identified by its arrangement and task, not its name alone.",
        "principles": [
            "Trace the input force and output motion separately for each mechanism.",
            "Distinguish a single fixed pulley's direction change from multi-pulley force tradeoffs.",
            "Treat cutting, splitting, fastening, lifting, and tension as hazard-bearing actions requiring suitable tools and supervision.",
        ],
        "relationships": ["These mechanisms connect force direction, inclined shapes, rotation, lines, material separation, fastening, and system components."],
        "examples": ["A flagpole pulley lets a downward pull raise a flag; a doorstop wedge redirects a push against the floor and door; turning a screw advances it along its length."],
        "counterexamples": ["One fixed pulley does not automatically reduce the ideal input-force magnitude; its main elementary benefit may be changing pull direction."],
        "limits": ["F1 does not calculate pulley ratios, line tension, thread pitch, cutting pressure, fastener strength, or safe working loads."],
        "vocabulary": [
            "pulley: a grooved wheel used with a line to redirect or arrange force and motion",
            "wedge: a sloping shape that redirects an applied force to separate, cut, lift, or hold",
            "screw: an inclined form wrapped around a cylinder that connects turning and lengthwise motion",
            "line: rope, cord, cable, or similar flexible element in a bounded mechanism description",
        ],
        "near_concept_distinctions": ["A pulley works with a flexible line around a wheel; a wedge acts through sloping faces; a screw relates rotation to travel along its axis."],
        "scope_of_application": "Use for diagrams, synthetic cases, and safe ordinary examples. Rigging, climbing, elevators, cranes, blades, fasteners, pressure systems, and overhead loads require qualified standards and procedures.",
        "unresolved_questions": ["Which shape and connection redirect the input, and what output motion or force is supported by observation?"],
        "explanation": "These machines use different geometries to redirect an input. Their shared label does not make them interchangeable, so the physical arrangement and task must stay visible.",
        "application": "Pulling down on a fixed clothesline pulley may move another section upward. That direction change can improve access even when it does not supply a large force advantage.",
        "analogies": ["A pulley routes a pull, a wedge spreads a push, and a screw turns a rotation into forward or backward travel."],
        "questions": ["Is this mechanism routing a line, spreading material with a slope, or advancing through rotation?"],
        "comparisons": ["A fixed pulley primarily changes direction; a pulley system may also trade force and distance; those claims should not be collapsed."],
        "participation": "This single fixed pulley lets the user pull downward while the load side moves upward. I would not claim a force reduction without measuring or identifying a multi-pulley arrangement.",
        "correction_response": "If I assign the wrong benefit, I would trace the line or surfaces, count moving supports where relevant, and separate direction change from force change.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ENG-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_simple_machines"],
        "source_refs": MACHINE_REFS,
    },
    {
        "concept_key": "curriculum_f1_compound_machine_design_system_v1",
        "title": "Compound machines combine mechanisms into a tested system",
        "domain": "curriculum.f1.simple_machines",
        "material": "A compound machine combines two or more simple-machine mechanisms in one device or task system. Understanding it requires tracing components, connections, inputs, outputs, constraints, and failure points, then testing whether the arrangement meets the stated need safely.",
        "principles": [
            "Decompose the device into supported mechanisms without assuming every shaped part is load-bearing or functionally active.",
            "Trace the full path from input through components to output.",
            "Compare designs against explicit criteria and constraints, changing one relevant feature at a time where possible.",
        ],
        "relationships": ["This integrates algorithms, components, material suitability, force, motion, models, communication, iteration, graceful correction, and task-specific judgment."],
        "examples": ["A shovel can combine a lever-like handle arrangement with a wedge-shaped edge; scissors combine lever action with wedge-like cutting edges."],
        "counterexamples": ["Finding two possible simple-machine shapes in a device does not prove both perform the proposed function in the actual operating arrangement."],
        "limits": ["F1 decomposition is qualitative and cannot certify load capacity, ergonomics, durability, maintainability, electrical safety, or real-world compliance."],
        "vocabulary": [
            "compound machine: a device combining two or more simple-machine mechanisms",
            "component: a part that participates in a larger system",
            "constraint: a limit or condition a design must respect",
            "failure point: a place or condition where a system may stop meeting its requirement",
        ],
        "near_concept_distinctions": ["A component is a part of a system; a mechanism is an arrangement that produces a relationship of motion or force; a device can contain both active and structural parts."],
        "scope_of_application": "Use for safe diagrams, ordinary-object explanation, and lightweight synthetic design. No authorization is granted to construct, modify, or operate hazardous or safety-critical machinery.",
        "unresolved_questions": ["Which components actively transmit force or motion, which are structural, and what evidence shows the complete system meets its criterion?"],
        "explanation": "A complex-looking tool becomes understandable when its parts and interactions are traced. The names of simple machines help describe mechanisms, while testing shows whether the combined system actually serves the task.",
        "application": "To compare two lightweight grabber designs, identify their lever-like joints, trace hand input to jaw output, test the same objects, and record reach, grip, control, and failure without treating one attractive appearance as proof.",
        "analogies": ["A compound machine is like a multi-step explanation: each part contributes, but the whole succeeds only when the connections preserve the intended result."],
        "questions": ["What enters the system, which components transform it, what comes out, and where might the chain fail?"],
        "comparisons": ["A simple machine names one foundational mechanism; a compound machine combines mechanisms and therefore introduces more interactions and failure points."],
        "participation": "I can trace the hand force through the handles and pivot to the jaws, then test whether the object is held. The mechanism description and the performance evidence answer different parts of the question.",
        "correction_response": "If testing contradicts the mechanism model, I would preserve the observed input and output, reopen the component roles, and revise the smallest unsupported connection.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ELA-1", "ENG-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_simple_machines"],
        "source_refs": MACHINE_REFS,
    },
)
