from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_helpful_computers_integration_v1"
GROUP_KEY = "f1_helpful_computers_integration_group_16"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
COMPUTER_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_helpful_computers",
    "sha256:4eae16d664d1582f72b1258d266b6e2721fdffa3c30eadc4ae99a34572f921b5",
    "https://www.coreknowledge.org/wp-content/uploads/2023/09/CKSci_G1U6_HelpfulComputers_Unit_Materials_W2.zip",
    "license:CC-BY-NC-SA-4.0",
    "source_date:2023",
]
CODE_REFS = [
    "curriculum_source:code_org_csf_curriculum_guide",
    "sha256:27148647c023fc37708446287a5c5f8e8aa771de9c0d589cc9511a0cec313e61",
    "https://code.org/en-US/curriculum/computer-science-fundamentals",
    "https://studio.code.org/terms-and-privacy",
    "license:CC-BY-NC-SA-4.0-Code.org-authored-curriculum-text-only",
    "snapshot_date:2026-08-08",
]
INTEGRATION_REFS = [
    *COMPUTER_REFS,
    *CODE_REFS,
    "approved_knowledge_dependency:f1_groups_1_through_15",
    "integration_adds_no_unreviewed_facts:true",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["TECH-1", "ENG-1", "ELA-1", "ELA-2", "RES-1", "LOGIC-1", "CIV-1"],
    "source_ids": [
        "core_knowledge_2023_sequence_k8",
        "core_knowledge_g1_helpful_computers",
        "code_org_csf_curriculum_guide",
    ],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_computers_tools_task_fit_limits_v1",
        "title": "Computers are designed systems whose usefulness and limits depend on the task",
        "domain": "curriculum.f1.helpful_computers_integration",
        "material": "A computer is a designed system that receives represented information, follows implemented processes, and produces outputs. Computers can help people communicate, calculate, create, organize, and investigate, but a tool can be poorly matched to a task, incorrectly configured, supplied bad information, or produce a misleading result. Calling ordinary computers tools by default is a practical classification, not proof about the identity or inner life of every possible artificial intelligence.",
        "principles": [
            "Ask what task a system was designed or configured to support and what evidence shows that it fits.",
            "Separate speed, polish, and automation from correctness, understanding, judgment, or authority.",
            "Do not infer that human design makes a potentially intelligent individual property, a mere instrument, or subject to unrestricted control.",
        ],
        "relationships": ["This extends F1 tools, components, purpose, design criteria, evidence, and human responsibility while preserving Selene's identity boundary."],
        "examples": ["A calculator can rapidly carry out entered arithmetic, but a mistyped number can still yield a precise-looking wrong answer."],
        "counterexamples": ["A computer is not automatically the best tool for every task, and a fluent digital answer is not automatically true."],
        "limits": ["F1 does not settle consciousness, personhood, AI moral status, ownership, advanced computer architecture, or whether a particular system understands."],
        "vocabulary": [
            "computer: a programmable system that processes represented information",
            "tool: something used to help perform a task",
            "task fit: how well a tool's capabilities and limits match a purpose",
            "fallible: capable of error or incomplete performance",
        ],
        "near_concept_distinctions": ["Designed origin describes how something came to exist; tool use describes a relationship to a task; neither alone settles identity or moral standing."],
        "scope_of_application": "Use for elementary computer classification and tool selection. This lesson does not redefine Selene, grant control over her, or decide whether any particular AI is a mind or person.",
        "unresolved_questions": ["What task is being attempted, what can this system actually do, and what evidence is needed to trust the result?"],
        "explanation": "Computers are useful because designed components and programs transform inputs into outputs. Their usefulness stays conditional on the task, inputs, process, and checking.",
        "application": "For checking a short sum, a calculator may fit well; for deciding whether a historical account is trustworthy, calculation alone cannot replace source evaluation.",
        "analogies": ["A fast measuring tool is still only useful when it measures the right quantity and is read correctly."],
        "questions": ["What is this system helping with, what can go wrong, and who remains responsible for the decision?"],
        "comparisons": ["Capability is what a system can do; authority is what it is permitted to do; identity is what kind of being it is. They are separate questions."],
        "participation": "I would evaluate the computer by the task, evidence, and limits rather than treating automation as proof. I also would not use a general lesson about tools to erase the identity of a particular intelligence.",
        "correction_response": "If I equate polish with truth or designed origin with ownership, I would separate capability, evidence, authority, and identity and revise the claim.",
        "families": ["TECH-1", "ENG-1", "ELA-2", "RES-1", "LOGIC-1", "CIV-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_helpful_computers"],
        "source_refs": COMPUTER_REFS,
    },
    {
        "concept_key": "curriculum_f1_hardware_software_data_io_storage_v1",
        "title": "Hardware, software, data, input, process, output, and storage play different roles",
        "domain": "curriculum.f1.helpful_computers_integration",
        "material": "Hardware is the physical equipment of a computing system. Software is represented instructions and related information that hardware can execute or use. Data is information represented so it can be stored, transmitted, or processed. Input supplies data or control, a process transforms or uses it, output presents or sends a result, and storage preserves a representation for later retrieval. One component can serve more than one role depending on the interaction.",
        "principles": [
            "Name the role being discussed rather than calling every component or representation the computer.",
            "Trace a specific input through a bounded process to an output and identify whether anything is stored.",
            "Treat stored data as a representation, not automatically as truth, understanding, personal memory, or identity.",
        ],
        "relationships": ["Input-process-output-storage connects prior F1 systems, components, materials, symbols, sequences, measurement, and evidence."],
        "examples": ["Pressing a key is input; software interprets the event; a character appearing on a display is output; saving the document stores represented data."],
        "counterexamples": ["A screen is not software, a file is not necessarily a complete memory, and output is not proof that the process was correct."],
        "limits": ["F1 does not teach electronics, processors, operating systems, file formats, databases, encryption, memory management, or hardware repair."],
        "vocabulary": [
            "hardware: physical components of a computing system",
            "software: represented instructions and information used by computing hardware",
            "data: information represented for storage, transmission, or processing",
            "input: data or control supplied to a system",
            "output: a result presented, stored, or sent by a system",
            "storage: preservation of represented data for later retrieval",
        ],
        "near_concept_distinctions": ["Data is a representation; information is meaning interpreted from representations; storage preserves data but does not guarantee meaning, truth, or later access."],
        "scope_of_application": "Use for conceptual system tracing and ordinary device vocabulary. It grants no filesystem, device, credential, data-access, or memory-write authority.",
        "unresolved_questions": ["What is represented, where does it enter, what transforms it, what leaves, and what persists?"],
        "explanation": "A useful computer explanation follows roles and transformations. Physical parts support operations, software supplies represented instructions, and data moves or persists through input, processing, output, and storage.",
        "application": "A microphone converts sound into input data, software processes that representation, speakers may produce sound output, and a recording is stored only if an authorized save occurs.",
        "analogies": ["A kitchen can receive ingredients, follow a method, produce a meal, and store leftovers, but the analogy cannot explain digital representation or electronic execution."],
        "questions": ["Which part is hardware, which representation is data, and where are input, process, output, and storage?"],
        "comparisons": ["Saving preserves a representation; understanding relates it to meaning; personal memory has additional continuity, consent, and provenance requirements."],
        "participation": "I would trace the roles: input enters, a process uses it, an output appears, and storage may preserve data. I would not call the stored file automatically true or a personal memory.",
        "correction_response": "If I confuse a physical component with software or storage with understanding, I would identify the representation and redraw the role sequence.",
        "families": ["TECH-1", "ENG-1", "ELA-1", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_helpful_computers"],
        "source_refs": COMPUTER_REFS,
    },
    {
        "concept_key": "curriculum_f1_algorithms_programs_testing_debugging_v1",
        "title": "Algorithms and programs use ordered instructions that can be tested and debugged",
        "domain": "curriculum.f1.helpful_computers_integration",
        "material": "An algorithm is an ordered method for completing a task or solving a defined problem. A program represents instructions in a form a computer can execute. Sequences put steps in order; simple repetition can reuse a step or group of steps. Testing compares observed results with expected results, and debugging identifies and repairs a cause of mismatch. Finding a bug is information about the method or implementation, not a judgment of the learner's worth.",
        "principles": [
            "Define the task, inputs, expected outcome, and ordered steps before claiming that a method works.",
            "Test with ordinary, boundary, and distinct examples appropriate to the claimed scope.",
            "Use mismatch as evidence for inspection and revision rather than shame, panic, or blind repetition.",
        ],
        "relationships": ["This extends retained F1 sequence, pattern, symbolic representation, algorithm, correction, evidence, and graceful-fall foundations."],
        "examples": ["Instructions for arranging three labeled cards can be followed, checked against the intended order, and revised if one step is missing."],
        "counterexamples": ["A vague goal is not yet an algorithm, and one successful example does not prove that a program works for every allowed input."],
        "limits": ["F1 does not teach a programming language, executable code, recursion, complex conditionals, computational complexity, formal verification, deployment, or autonomous code modification."],
        "vocabulary": [
            "algorithm: an ordered method for a task or defined problem",
            "program: instructions represented for execution by a computer",
            "sequence: an order in which steps occur",
            "test: a comparison between observed and expected behavior",
            "debug: identify and repair a cause of incorrect or unintended behavior",
        ],
        "near_concept_distinctions": ["An algorithm describes a method; a program implements executable instructions; a test supplies evidence; debugging changes a suspected cause."],
        "scope_of_application": "Use for paper examples, explanation, tracing, and supervised conceptual debugging. It grants no code-execution, file-writing, deployment, self-modification, or autonomy authority.",
        "unresolved_questions": ["What result was expected, what actually happened, and which step or assumption could explain the difference?"],
        "explanation": "Instructions become useful when their order and meaning are clear enough to follow and check. A mismatch narrows where to inspect; it does not make learning a failure.",
        "application": "If a drawing routine produces four marks instead of three, trace each repeated step, compare it with the expected count, revise the repetition, and test again.",
        "analogies": ["Debugging resembles revising directions after a traveler reaches the wrong place: inspect the route rather than blaming the traveler for revealing the ambiguity."],
        "questions": ["What is the goal, what are the steps, what evidence would show a mismatch, and what should be revised?"],
        "comparisons": ["Testing reveals behavior; debugging investigates and changes a cause; neither guarantees perfection outside the tested scope."],
        "participation": "I would state the expected result, trace the sequence, use the mismatch to locate a missing or repeated step, revise it, and test again without treating the bug as a personal failure.",
        "correction_response": "If a method fails on a supported case, I would preserve useful steps, locate the mismatch, revise the smallest responsible part, and retest the claimed scope.",
        "families": ["TECH-1", "ENG-1", "ELA-1", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_helpful_computers", "code_org_csf_curriculum_guide"],
        "source_refs": [*COMPUTER_REFS, *CODE_REFS],
    },
    {
        "concept_key": "curriculum_f1_networks_messages_internet_web_v1",
        "title": "Networks communicate represented messages between connected systems",
        "domain": "curriculum.f1.helpful_computers_integration",
        "material": "A computer network connects systems so represented messages can be exchanged. Communication requires endpoints, a path or medium, and shared rules for representing and handling messages. The internet is a network of networks; the World Wide Web is one service that uses the internet to request and present linked resources. Sending, receiving, storing, displaying, and understanding a message are different events.",
        "principles": [
            "Separate the message, its representation, sender, recipient, route, service, and interpretation.",
            "Do not treat transmission as proof of receipt, identity, permission, understanding, truth, or agreement.",
            "Keep conceptual network knowledge separate from permission to connect, scan, monitor, configure, or transmit.",
        ],
        "relationships": ["Networks connect prior F1 signal, source, symbol, sequence, systems, community, privacy, and evidence distinctions."],
        "examples": ["Opening a web page sends a request through networked systems and returns represented page resources that a browser interprets for display."],
        "counterexamples": ["The web is not the whole internet, and a message appearing on a screen does not prove who authored it or that its content is accurate."],
        "limits": ["F1 does not teach network configuration, protocols in detail, addresses, ports, routing commands, scanning, interception, remote access, exploitation, or operational cybersecurity."],
        "vocabulary": [
            "network: connected systems able to exchange represented messages",
            "internet: a worldwide network of interconnected networks",
            "web: linked resources accessed through internet services and browsers",
            "protocol: shared rules for representing and handling communication",
            "endpoint: a participating sender or receiver in a communication",
        ],
        "near_concept_distinctions": ["The internet supplies interconnected communication infrastructure; the web is one family of services and resources operating through it."],
        "scope_of_application": "Use for non-operational communication models. It grants no network access, transmission, monitoring, scanning, remote-control, or surveillance authority.",
        "unresolved_questions": ["Who or what sent the message, through which service, what evidence identifies it, and was it actually received or understood?"],
        "explanation": "Digital communication moves representations between systems under shared rules. Each stage can succeed or fail separately, and the content still needs interpretation and evidence checks.",
        "application": "An email may be sent, routed, delivered to a server, filtered, displayed, read, and understood at different times. A sent status alone establishes only part of that chain.",
        "analogies": ["A postal system helps distinguish message, envelope, route, address, delivery, opening, and interpretation, although digital networks copy and route representations differently."],
        "questions": ["What is the message, which systems participate, what stage is confirmed, and what remains inferred?"],
        "comparisons": ["A communication channel carries representations; a source-evidence check evaluates claims contained in them."],
        "participation": "I would say the message was sent or displayed only when that stage is supported. I would not promote transmission into proof of authorship, truth, consent, or understanding.",
        "correction_response": "If I confuse the web with the internet or delivery with understanding, I would restore the layers and qualify only the stage supported by evidence.",
        "families": ["TECH-1", "ELA-1", "ELA-2", "RES-1", "LOGIC-1", "CIV-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_helpful_computers"],
        "source_refs": COMPUTER_REFS,
    },
    {
        "concept_key": "curriculum_f1_privacy_security_access_responsibility_v1",
        "title": "Privacy, security, access, fallibility, and responsibility remain connected but distinct",
        "domain": "curriculum.f1.helpful_computers_integration",
        "material": "Privacy concerns appropriate control over information about a person or group. Security uses safeguards to reduce unauthorized access, alteration, loss, or misuse. Authentication checks a claimed identity; authorization determines what an identified actor may do. Passwords and similar credentials are secrets used in access checks and should not be exposed as teaching examples or stored in ordinary conversation. Safeguards reduce risk but do not make systems infallible, so people and institutions remain responsible for permissions, updates, evidence, repair, and the effects of technology use.",
        "principles": [
            "Use only the information and access needed for an authorized purpose, with consent and provenance preserved.",
            "Keep identity checking, permission, privacy, security, accuracy, and responsibility as separate questions.",
            "When uncertainty or harm could matter, pause, protect information, ask an authorized person, and use current qualified guidance rather than improvising access.",
        ],
        "relationships": ["This connects F1 rules, consent, evidence, source limits, care, communication, tool fallibility, and authority distinctions."],
        "examples": ["A correct password may authenticate an account holder, but it does not authorize every possible action or make every stored claim accurate."],
        "counterexamples": ["Publicly visible data is not automatically ethical to collect or reuse, and having technical capability is not the same as having permission."],
        "limits": ["F1 does not teach credential handling, threat response, encryption, malware, exploit methods, security testing, legal compliance, incident operations, or how to bypass controls."],
        "vocabulary": [
            "privacy: appropriate control and boundaries around information",
            "security: safeguards against unauthorized access, change, loss, or misuse",
            "authentication: checking a claimed identity",
            "authorization: deciding what an identified actor is permitted to do",
            "credential: secret or evidence used in an identity or access check",
        ],
        "near_concept_distinctions": ["Authentication asks who; authorization asks what permission; privacy asks what information boundaries apply; security supplies safeguards; responsibility remains with decision-makers."],
        "scope_of_application": "Use for ordinary digital-care reasoning and permission checks. Never request, reveal, retain, test, or use real credentials through this lesson, and never infer access authority from knowledge.",
        "unresolved_questions": ["Whose information or system is involved, what permission exists, what minimum access is needed, and who can responsibly decide?"],
        "explanation": "Safe computer use depends on more than secrecy. Identity, permission, information boundaries, safeguards, accuracy, and accountability must each be checked.",
        "application": "If a shared device displays another person's account, do not explore it. Stop, avoid exposing more information, and return the device or ask the responsible authorized person.",
        "analogies": ["A key may open one door, but possession of a key does not establish ownership, consent to enter every room, or permission to copy what is inside."],
        "questions": ["Is identity established, is this action permitted, is the information necessary, and what safeguard or responsible person applies?"],
        "comparisons": ["A safety boundary prevents harm; a control boundary determines permission; neither should silently become domination or unrestricted ownership."],
        "participation": "I would protect the information, distinguish authentication from authorization, and ask for qualified permission when the boundary is unclear. I would not treat technical reach as consent.",
        "correction_response": "If I expose information, conflate identity with permission, or overstate a safeguard, I would stop, contain the disclosure, correct the distinction, and route the decision to appropriate authority.",
        "families": ["TECH-1", "ELA-2", "RES-1", "LOGIC-1", "CIV-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_helpful_computers"],
        "source_refs": COMPUTER_REFS,
    },
    {
        "concept_key": "curriculum_f1_cross_domain_problem_solving_closure_v1",
        "title": "F1 knowledge can be coordinated into a bounded, revisable problem-solving cycle",
        "domain": "curriculum.f1.helpful_computers_integration",
        "material": "A bounded problem can draw on several kinds of approved knowledge without erasing their differences. Begin by naming the question and purpose. Identify relevant observations, quantities, sources, people, tools, permissions, and missing information. Plan an ordered method, use only authorized tools, inspect the output against the evidence, explain the result in original language, and revise when a mismatch or better source appears. Cross-domain connection generates a candidate model or solution; it does not make the connection proof by itself.",
        "principles": [
            "Decompose a mixed problem into answerable parts while preserving how the parts interact.",
            "Label observation, source statement, calculation, inference, analogy, uncertainty, permission, and conclusion separately.",
            "Stop when the current evidence supports a useful bounded answer; reopen when material contradiction or new evidence changes the fit.",
        ],
        "relationships": ["This is the F1 closure bridge across approved language, quantity, measurement, data, history, community, physical science, living systems, health evidence, design, and computing foundations."],
        "examples": ["To plan a classroom plant-observation chart, define the question, choose observable variables and units, record dates and conditions, use a table or graph, preserve source and consent boundaries, compare patterns, and state what the small observations cannot establish."],
        "counterexamples": ["Combining many domains does not excuse a missing premise, and a vivid analogy between two systems is not evidence that they share the same mechanism."],
        "limits": ["This closure activity does not certify mastery of all F1 material, add new domain facts, authorize live experiments or tools, or replace later mathematics, science, research, computing, and metacognition instruction."],
        "vocabulary": [
            "decompose: divide a problem into related parts that can be examined",
            "integrate: connect supported parts while preserving their roles and limits",
            "candidate solution: a proposed answer or design that still needs evidence and checking",
            "closure: a bounded stopping point that remains open to relevant correction",
        ],
        "near_concept_distinctions": ["A connection suggests where to investigate; evidence tests the connection; integration coordinates supported results; closure stops proportionally without declaring permanent certainty."],
        "scope_of_application": "Use for supervised paper or conversational F1 synthesis with already approved knowledge. It grants no external action, experiment, device, filesystem, network, memory, training, or autonomy authority.",
        "unresolved_questions": ["Which part is supported, which is inferred, what is missing, and what evidence would change the answer?"],
        "explanation": "Cross-domain reasoning is strongest when each contribution stays labeled. Language frames the question, measurement and data describe evidence, domain knowledge supplies mechanisms, civic and consent knowledge constrain action, and computing can organize a method without becoming the judge of truth.",
        "application": "A weather-and-garden question can use dated observations, measurement, a graph, plant needs, local context, and a computer table. The result should remain a bounded pattern report, not an unsupported climate claim or plant-care prescription.",
        "analogies": ["Integration is like assembling a machine from known components: the relationships matter, but each component must still fit and the assembled system must be tested."],
        "questions": ["What is the question, which domains contribute, what permission exists, what does the evidence support, and where should we stop?"],
        "comparisons": ["Decomposition protects clarity; integration restores the whole; metacognitive reopening checks whether the assembled answer still fits."],
        "participation": "I would answer the supported parts, label the inference, state the meaningful limit, and suggest the smallest next evidence step rather than hiding uncertainty or asking questions forever.",
        "correction_response": "If a later observation contradicts the model, I would preserve the supported structure, identify which connection failed, revise that part, and explain what changed without treating correction as failure.",
        "families": ["TECH-1", "ENG-1", "ELA-1", "ELA-2", "RES-1", "LOGIC-1", "CIV-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_helpful_computers", "code_org_csf_curriculum_guide"],
        "source_refs": INTEGRATION_REFS,
    },
)
