from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_operations_data_measurement_time_v1"
GROUP_KEY = "f1_operations_measurement_group_3"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
OPERATIONS_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_math_unit1",
    "sha256:b12ffcd8c14e3e20e6259d86df0238291d4f23b4b635e901360e612b34e26f73",
    "https://www.coreknowledge.org/wp-content/uploads/2023/08/CKMath_G1U1_AddingSubtractingAndWorkingWithData_Unit_Materials_W2.zip",
]
MEASUREMENT_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_math_unit6",
    "sha256:44bfe742360db51c924e1cefccafd93cc6be90cdcded974c0bc9f5e925756eba",
    "https://www.coreknowledge.org/wp-content/uploads/2023/08/CKMath_G1U6_LengthMeasurementsWithin120Units_Unit_Materials_W2.zip",
]
TIME_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_math_unit7",
    "sha256:17a99668e71a9094d1b30acf6a069edc8316003357c555d400c766bb78d90a8a",
    "https://www.coreknowledge.org/wp-content/uploads/2023/08/CKMath_G1U7_GeometryAndTime_Unit_Materials_W2.zip",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["MATH-1", "MATH-2", "ELA-1", "SCI-0"],
    "source_ids": [
        "core_knowledge_2023_sequence_k8",
        "core_knowledge_g1_math_unit1",
        "core_knowledge_g1_math_unit6",
        "core_knowledge_g1_math_unit7",
    ],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_addition_relationship_v1",
        "title": "Addition describes composing quantities",
        "domain": "curriculum.f1.operations",
        "material": "Addition relates quantities by composing parts, joining an added amount to a starting amount, or counting forward to determine a total.",
        "principles": [
            "An addition expression identifies addends and their total.",
            "The same total can be decomposed into different pairs or groups of addends.",
            "Changing the order of two addends does not change their sum, though the story context may emphasize different roles.",
        ],
        "relationships": ["Addition builds on cardinality and grouping and supports subtraction, place value, measurement, and data totals."],
        "examples": ["A tray with four red parts and three blue parts contains seven parts in all."],
        "counterexamples": ["Placing two labels beside one another does not add their values unless they represent quantities being composed."],
        "limits": ["Addition combines quantities measured on compatible bases; units or categories may need conversion or separation first."],
        "vocabulary": [
            "addition: an operation relating combined quantities to a total",
            "addend: a quantity being added",
            "sum: the total related to the addends",
            "compose: form a whole from parts",
        ],
        "near_concept_distinctions": ["Counting identifies how many are present; addition relates two or more quantities to a total."],
        "scope_of_application": "Use when quantities are joined, composed, accumulated, or represented as parts of one total. Confirm compatible units and avoid combining unrelated categories without explanation.",
        "unresolved_questions": ["What quantities are the parts, and what total do they compose?"],
        "explanation": "Addition expresses a part-to-whole relationship. It can describe joining an amount to what was already present or combining several known parts into one total.",
        "application": "If a review queue has six existing items and receives three new distinct items, the queue total becomes nine, assuming none were duplicates or removed.",
        "analogy": ["It is like pouring compatible measured portions into one container and tracking the resulting total."],
        "questions": ["Which quantities are being combined, and do they share the same unit or category?"],
        "comparisons": ["Addition composes parts into a total; counting can verify the resulting collection."],
        "participation": "There were six items and three were added, so the new total is nine. That assumes all three are new members of the same queue.",
        "correction_response": "If one addend used a different unit or included duplicates, I would repair the quantities before recomputing the sum.",
        "families": ["MATH-1", "MATH-2", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit1"],
        "source_refs": OPERATIONS_REFS,
    },
    {
        "concept_key": "curriculum_f1_subtraction_relationship_v1",
        "title": "Subtraction describes removal, missing parts, or difference",
        "domain": "curriculum.f1.operations",
        "material": "Subtraction relates a starting or larger quantity to a removed part, a remaining part, a missing part, or the difference between two quantities.",
        "principles": [
            "A subtraction relationship can describe taking away, finding what remains, finding a missing addend, or comparing quantities.",
            "The order of the quantities matters in subtraction.",
            "A difference describes how far apart two comparable quantities are, not necessarily a physical removal.",
        ],
        "relationships": ["Subtraction is related to addition through part-whole structure and supports comparison, change, and error checking."],
        "examples": ["If nine seats exist and six are occupied, three seats remain available."],
        "counterexamples": ["The difference between nine and six does not imply that three objects were physically removed."],
        "limits": ["The elementary whole-number interpretation does not by itself cover signed direction, rates, or incompatible units."],
        "vocabulary": [
            "subtraction: an operation relating a whole or starting quantity to a removed, remaining, missing, or compared part",
            "difference: the amount separating two comparable quantities",
            "remainder: what remains after a bounded removal in the stated context",
            "missing part: an unknown quantity needed to complete a known relationship",
        ],
        "near_concept_distinctions": ["Removal is one subtraction story; comparison finds a difference without requiring anything to be taken away."],
        "scope_of_application": "Use for removal, remaining quantity, missing parts, and additive comparison on compatible quantities. State which role each number plays.",
        "unresolved_questions": ["Are we finding what remains, what was removed, the missing part, or the difference?"],
        "explanation": "Subtraction is broader than taking away. It can locate a remainder, identify an unknown part of a whole, or measure the gap between two comparable amounts.",
        "application": "If one report lists twelve verified records and another lists eight, the difference is four even though no record was necessarily deleted.",
        "analogy": ["It is like measuring the gap between two marks on a scale: the gap exists even when neither mark moves."],
        "questions": ["What does the result represent in this story: remaining, missing, removed, or difference?"],
        "comparisons": ["Taking away changes a collection; comparing can use subtraction while leaving both collections unchanged."],
        "participation": "Twelve minus eight is four, so the reports differ by four records. That comparison alone does not tell us why they differ.",
        "correction_response": "If I assigned the numbers to the wrong roles, I would reconstruct the story relationship before recalculating.",
        "families": ["MATH-1", "MATH-2", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit1"],
        "source_refs": OPERATIONS_REFS,
    },
    {
        "concept_key": "curriculum_f1_equality_inverse_operations_v1",
        "title": "Equality and inverse operations preserve a relationship",
        "domain": "curriculum.f1.operations",
        "material": "An equation states that two expressions have equal value, and addition and subtraction can undo or verify one another within a shared part-whole relationship.",
        "principles": [
            "The equals sign states equal value rather than announcing that an answer comes next.",
            "If two parts compose a whole, subtracting either part from the whole yields the other part.",
            "An inverse-operation check can reveal an arithmetic or role-assignment error.",
        ],
        "relationships": ["Equality connects representations, unknowns, addition, subtraction, and later algebraic reasoning."],
        "examples": ["Because five plus three equals eight, eight minus three equals five and eight minus five equals three."],
        "counterexamples": ["The expression 4 + 2 = 6 + 1 is false even though both sides contain valid calculations."],
        "limits": ["Inverse checks confirm a numeric relationship but do not prove that the original quantities or model fit the real situation."],
        "vocabulary": [
            "equation: a statement that two expressions have equal value",
            "equals sign: notation recording equality",
            "inverse operations: operations that undo corresponding effects under stated conditions",
            "unknown: a quantity whose value is not yet specified",
        ],
        "near_concept_distinctions": ["An expression represents a value or operation; an equation asserts a relationship between expressions."],
        "scope_of_application": "Use for elementary whole-number part-whole relationships, missing quantities, and arithmetic checks. Verify that the mathematical model also matches the situation.",
        "unresolved_questions": ["Do both sides represent the same value and the same intended quantity relationship?"],
        "explanation": "Equality means balance between two values. Addition builds a whole from parts, while subtraction can recover a part, so each operation can check the other inside the same relationship.",
        "application": "If a count rises from seven to eleven after four additions, subtracting four from eleven should recover seven; if it does not, the record or arithmetic needs inspection.",
        "analogy": ["An equation is like a balanced scale: the forms may differ while the represented amounts remain equal."],
        "questions": ["What value must the unknown have to keep both sides equal?"],
        "comparisons": ["The equals sign records a relationship; an answer arrow would instead describe a one-way procedure."],
        "participation": "Eleven minus four returns seven, so the arithmetic is internally consistent. We still need to confirm that four genuinely new items were added.",
        "correction_response": "If the inverse check fails, I would inspect both the calculation and the way the story quantities were assigned.",
        "families": ["MATH-1", "MATH-2", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit1"],
        "source_refs": OPERATIONS_REFS,
    },
    {
        "concept_key": "curriculum_f1_categorical_data_v1",
        "title": "Categorical data organizes counts by defined groups",
        "domain": "curriculum.f1.data",
        "material": "Categorical data places observations or items into defined groups and represents each group's count with marks, drawings, numbers, tables, or simple graphs so comparisons can be made.",
        "principles": [
            "Categories need clear membership rules.",
            "Each included observation should be recorded consistently.",
            "A representation must preserve the underlying counts and label its categories.",
            "Questions about most, least, same, and total depend on the represented data rather than visual decoration.",
        ],
        "relationships": ["Categorical data combines classification, counting, comparison, addition, source boundaries, and representation."],
        "examples": ["A tally table can count red, blue, and green objects and show which category contains the most."],
        "counterexamples": ["A taller decorative icon can make a category look larger even when it represents the same count."],
        "limits": ["Categories may overlap or omit relevant detail; the representation answers only questions supported by its collection and classification method."],
        "vocabulary": [
            "category: a defined group used to classify observations",
            "categorical data: observations recorded by category",
            "tally: a repeated mark used to record counts",
            "table: an arrangement of labeled values in rows or columns",
            "graph: a visual representation of data relationships",
        ],
        "near_concept_distinctions": ["A category label identifies a class; a count states how many recorded items belong to it."],
        "scope_of_application": "Use for bounded discrete observations assigned to defined categories. Record overlaps, missing data, and collection limits when they matter.",
        "unresolved_questions": ["Could an item belong to more than one category, and how was that handled?"],
        "explanation": "Categorical data becomes useful when the grouping rules and counts are clear. Tables or simple graphs then make comparisons visible without changing the underlying observations.",
        "application": "A bug report can classify issues as display, calculation, or network-related, count each category, and still note that mixed-cause reports may need more than one label.",
        "analogy": ["It resembles sorting mail into labeled trays and then counting each tray, provided the sorting rule is consistent."],
        "questions": ["How were categories defined, and does each mark correspond to one recorded observation?"],
        "comparisons": ["A table emphasizes labeled values; a simple graph emphasizes visual comparison of those same values."],
        "participation": "The display category has the highest count, but several reports have mixed causes. I would preserve that classification limit rather than claiming every report fits one cause cleanly.",
        "correction_response": "If category rules changed or an item was double-counted unexpectedly, I would recode the affected observations and rebuild the totals.",
        "families": ["MATH-1", "MATH-2", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit1"],
        "source_refs": OPERATIONS_REFS,
    },
    {
        "concept_key": "curriculum_f1_length_attribute_comparison_v1",
        "title": "Length is an attribute compared from aligned references",
        "domain": "curriculum.f1.measurement",
        "material": "Length describes extent along a chosen direction, and direct comparison is reliable when objects are aligned to the same starting reference rather than judged only by their displaced endpoints or overall appearance.",
        "principles": [
            "Name the attribute being compared, such as length rather than area or mass.",
            "Align endpoints or use a common reference for direct length comparison.",
            "An intermediate object can support indirect comparison when two objects cannot be placed together.",
        ],
        "relationships": ["Length comparison builds on observation and fair comparison and prepares unit-based measurement."],
        "examples": ["Two pencils can be compared by placing one end of each at the same line and observing which extends farther."],
        "counterexamples": ["A pencil shifted farther to the right can appear to end later while still being shorter."],
        "limits": ["Curved paths, changing objects, and different measurement directions require a method suited to that shape and attribute."],
        "vocabulary": [
            "length: extent along a chosen direction or path",
            "endpoint: a boundary used to mark the start or end of a length",
            "direct comparison: comparing objects together on one reference",
            "indirect comparison: comparing through a shared intermediate reference",
        ],
        "near_concept_distinctions": ["Length concerns one-dimensional extent; size can refer informally to area, volume, mass, or several attributes."],
        "scope_of_application": "Use aligned references for straight-object comparisons and a shared intermediary when direct placement is impractical. Choose an appropriate path method for curves.",
        "unresolved_questions": ["Are the same attribute, direction, and starting reference being compared?"],
        "explanation": "Length comparison needs a common baseline. Once the starts are aligned, the farther endpoint indicates greater length; without alignment, position can masquerade as length.",
        "application": "To compare two progress bars placed at different screen coordinates, compare their filled widths from each bar's own aligned start rather than their absolute rightmost pixels.",
        "analogy": ["It is like starting runners at one line before comparing how far they travel."],
        "questions": ["What is the shared starting reference for this comparison?"],
        "comparisons": ["Direct comparison places objects together; indirect comparison transfers each length through one common reference."],
        "participation": "The second bar ends farther right, but it also starts farther right. I would compare each filled width from its own start before deciding which is longer.",
        "correction_response": "If the references were misaligned, I would repeat the comparison from a shared baseline and revise the result.",
        "families": ["MATH-1", "MATH-2", "SCI-0", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit6"],
        "source_refs": MEASUREMENT_REFS,
    },
    {
        "concept_key": "curriculum_f1_unit_iteration_measurement_v1",
        "title": "Measurement repeats a named unit without gaps or overlaps",
        "domain": "curriculum.f1.measurement",
        "material": "A length measurement states how many equal copies of a named unit span the chosen length when the units are placed end to end without gaps or overlaps.",
        "principles": [
            "The unit must remain the same size throughout the measurement.",
            "Units begin at the chosen start and are iterated without gaps or overlaps.",
            "The numerical result is incomplete without the unit.",
            "Smaller units produce larger counts for the same length.",
        ],
        "relationships": ["Unit iteration connects counting, equal groups, fair comparison, precision, and communication."],
        "examples": ["A shelf spanning eight equal tiles is eight tile-lengths long when the tiles touch edge to edge."],
        "counterexamples": ["Eight mixed-size blocks do not define one repeatable length unit."],
        "limits": ["Measurement accuracy is bounded by unit size, alignment, instrument quality, and the definition of the endpoints."],
        "vocabulary": [
            "unit: an agreed quantity used as one measurement step",
            "iterate: repeat a unit successively",
            "measurement: a number together with a unit and method",
            "gap: unmeasured space between successive units",
            "overlap: space counted by more than one unit placement",
        ],
        "near_concept_distinctions": ["A count tells how many discrete items; a length measurement counts how many equal unit intervals span an extent."],
        "scope_of_application": "Use equal named units and explicit endpoints for length. Different attributes such as mass, duration, and capacity require their own units and instruments.",
        "unresolved_questions": ["What unit and endpoint convention produced this measurement?"],
        "explanation": "Measuring length means laying one stable unit repeatedly across an extent and counting the placements. The count gains meaning only together with the unit and method.",
        "application": "A timeline bar reported as 30 is ambiguous until its unit is named; thirty seconds and thirty minutes describe very different durations even though the numeral matches.",
        "analogy": ["It is like paving a path with identical tiles: missing space and double-covered space both distort the total."],
        "questions": ["Are the units equal, aligned, gap-free, and explicitly named?"],
        "comparisons": ["Eight centimeters and eight inches share a count but not a length because the units differ."],
        "participation": "The result is fourteen units, but I need the unit name and endpoint rule before treating that as a communicable length measurement.",
        "correction_response": "If units varied, overlapped, or left gaps, I would repeat the measurement with one stable unit and revise the value.",
        "families": ["MATH-1", "MATH-2", "SCI-0", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit6"],
        "source_refs": MEASUREMENT_REFS,
    },
    {
        "concept_key": "curriculum_f1_time_order_duration_v1",
        "title": "Time can describe order, duration, or a position in a schedule",
        "domain": "curriculum.f1.time",
        "material": "Temporal language distinguishes the order of events, the duration between boundaries, and a clock or calendar position used to coordinate when something occurs.",
        "principles": [
            "Before and after describe order, while duration describes elapsed extent.",
            "A time of day locates an event in a daily cycle but does not by itself state how long it lasts.",
            "Durations require a start, an end, and a named time unit.",
        ],
        "relationships": ["Time language connects sequence, measurement, planning, causality, and historical chronology."],
        "examples": ["A meeting begins at 2:00 and ends at 2:30, so 2:00 is a clock time and thirty minutes is its duration."],
        "counterexamples": ["An event happening after another does not prove that the earlier event caused it."],
        "limits": ["Clock conventions, time zones, calendars, and irregular schedules require explicit context beyond elementary daily time."],
        "vocabulary": [
            "order: the before-and-after relationship among events",
            "duration: elapsed time between boundaries",
            "time of day: a position in a daily clock cycle",
            "interval: the bounded extent between two points",
        ],
        "near_concept_distinctions": ["Sequence states which event comes first; duration states how much time passes."],
        "scope_of_application": "Use for ordinary event order, schedules, and bounded durations. Name time zone, date, and calendar when coordination can otherwise be ambiguous.",
        "unresolved_questions": ["Are we asking when the event occurs, how long it lasts, or what happened before it?"],
        "explanation": "Time questions have different targets. A clock position says when, ordering language says which came first, and duration measures the interval from start to finish.",
        "application": "A software job starting at 10:15 and finishing at 10:45 has a thirty-minute duration; its later finish does not reveal why another job failed afterward.",
        "analogy": ["A route has both landmarks and distances: clock times are landmarks, while durations are distances along the timeline."],
        "questions": ["Do you need the start time, event order, or elapsed duration?"],
        "comparisons": ["At 3:00 identifies a schedule position; for three hours identifies an extent of time."],
        "participation": "The event happened at 4:00 and lasted half an hour. Those answer different questions, so I would keep the clock time separate from the duration.",
        "correction_response": "If I confused schedule time with elapsed duration, I would restore the start and end boundaries and recalculate the interval.",
        "families": ["MATH-1", "MATH-2", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit7"],
        "source_refs": TIME_REFS,
    },
    {
        "concept_key": "curriculum_f1_clock_hours_half_hours_v1",
        "title": "Clocks represent hours and half-hours within repeating cycles",
        "domain": "curriculum.f1.time",
        "material": "An analog clock represents repeating hours and minutes with hands moving around a shared dial; at the hour the minute hand points to twelve, and at the half-hour it points to six after thirty minutes have elapsed.",
        "principles": [
            "The shorter hand primarily indicates the hour region and the longer hand indicates minutes.",
            "One full hour contains sixty minutes and one half-hour contains thirty minutes.",
            "At a half-hour the hour hand lies between consecutive hour marks rather than staying exactly on the earlier mark.",
            "A clock reading may need morning/evening or date context to identify one unique moment.",
        ],
        "relationships": ["Clock reading combines cyclic representation, fractions of an hour, counting by intervals, and schedule language."],
        "examples": ["At 7:30, the minute hand points to six and the hour hand has moved halfway from seven toward eight."],
        "counterexamples": ["A minute hand on six does not mean six minutes; on a standard dial it represents thirty minutes past the hour."],
        "limits": ["This foundation covers standard twelve-hour analog clocks at hours and half-hours, not every clock format, time zone, or precision level."],
        "vocabulary": [
            "hour: a duration of sixty minutes",
            "minute: one sixtieth of an hour",
            "half-hour: a duration of thirty minutes",
            "analog clock: a cyclic dial representing time with moving hands",
            "digital time: a numeral-based clock representation",
        ],
        "near_concept_distinctions": ["The numeral six labels an hour position, while the minute hand at that position represents thirty elapsed minutes."],
        "scope_of_application": "Use for standard hour and half-hour readings and translations between simple analog and digital forms. Ask for AM/PM, date, or time zone when needed.",
        "unresolved_questions": ["Does the schedule require morning/evening or time-zone context?"],
        "explanation": "The clock dial is a repeating representation. The long hand tracks progress through sixty minutes, while the short hand moves between hour labels as that progress accumulates.",
        "application": "If a maintenance window begins at 6:00 and ends when the minute hand reaches six, the window has lasted thirty minutes and the clock reads 6:30.",
        "analogy": ["It is like two runners circling one track at different speeds: the faster hand completes a circuit while the slower hand advances one hour."],
        "questions": ["What do the hour and minute hands each indicate, and is morning/evening context needed?"],
        "comparisons": ["6:00 names the start of the hour; 6:30 marks thirty minutes of progress toward 7:00."],
        "participation": "The long hand at six means thirty minutes past, and the short hand between six and seven makes the reading 6:30 rather than 7:30.",
        "correction_response": "If I read the dial numeral as a minute count, I would translate the hand position through the clock's five-minute intervals and correct the time.",
        "families": ["MATH-1", "MATH-2", "ELA-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit7"],
        "source_refs": TIME_REFS,
    },
)
