from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "coding_computational_thinking_code_reading_v1"
GROUP_KEY = "coding_computational_thinking_code_reading_group_1"

PYTHON_SOURCE_REFS = [
    "curriculum_source:python_documentation_3_14_6",
    "source_locator:Python-3.14.6-tutorial-controlflow-if-for-range-break-continue-functions",
    "https://docs.python.org/3/tutorial/controlflow.html",
    "source_locator:Python-language-reference-execution-model-naming-binding-and-scope",
    "https://docs.python.org/3/reference/executionmodel.html",
    "license:Python-Software-Foundation-License-Version-2",
    "code_examples_license:Zero-Clause-BSD",
    "https://docs.python.org/3/license.html",
    "attribution:Python Software Foundation",
    "source_checked:2026-08-13",
]

BOUNDARY_REFS = [
    "source:src/selene/local_code_inspection.py:v1_explicit_sources_static_observation",
    "boundary:knowledge_does_not_grant_filesystem_process_network_or_execution_authority",
    "boundary:no_self_modification_self_replication_or_unapproved_code_action",
]

SCOPE = {
    "bands": ["CODING-1"],
    "families": ["CS-1", "LOGIC-1", "ELA-1"],
    "source_ids": ["python_documentation_3_14_6", "selene_local_code_inspection_v1"],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must complete with source-linked reconstruction and distinct code-reading application.",
    "authority_boundary": "Knowledge and explanation only; code execution, file access, file writing, network use, deployment, self-modification, and self-replication remain separately governed and unavailable.",
}


def _lesson(
    concept_key: str,
    title: str,
    material: str,
    principles: list[str],
    example: str,
    counterexample: str,
    limits: str,
    vocabulary: list[str],
    distinction: str,
    application: str,
    analogy: str,
    comparison: str,
    participation: str,
    correction: str,
    relationships: list[str],
) -> dict[str, Any]:
    return {
        "concept_key": concept_key,
        "title": title,
        "domain": "curriculum.coding.computational_thinking_and_code_reading",
        "material": material,
        "principles": principles,
        "relationships": relationships,
        "examples": [example],
        "counterexamples": [counterexample],
        "limits": [limits],
        "vocabulary": vocabulary,
        "near_concept_distinctions": [distinction],
        "scope_of_application": "Use to decompose bounded problems and explain supplied Python code statically. Preserve the distinction among visible syntax, reasoned interpretation, and verified runtime behavior.",
        "unresolved_questions": ["What input, state, branch, or external dependency would need inspection before the next conclusion becomes justified?"],
        "explanation": (
            f"This coding relationship can be reconstructed by tracing what information enters, which rule changes or selects it, and what leaves the step. {analogy} "
            "Reading can support a bounded prediction, but execution or a purpose-built test is separate evidence rather than an automatic consequence of understanding the syntax."
        ),
        "application": application,
        "analogies": [analogy],
        "questions": ["What is directly visible in the code, what follows from the language rule, and what still depends on runtime context?"],
        "comparisons": [comparison],
        "participation": participation,
        "correction_response": correction,
        "families": ["CS-1", "LOGIC-1", "ELA-1"],
        "source_ids": ["python_documentation_3_14_6", "selene_local_code_inspection_v1"],
        "source_refs": [*PYTHON_SOURCE_REFS, *BOUNDARY_REFS],
    }


LESSONS: tuple[dict[str, Any], ...] = (
    _lesson(
        "coding_problem_decomposition_input_process_output_v1",
        "Decompose a bounded problem into inputs, transformations, decisions, state, and outputs",
        "A program represents a process. Before reading individual syntax, identify what information can enter, what must be remembered, which transformations or decisions occur, and what result or side effect can leave. Decomposition makes each responsibility small enough to inspect and connect.",
        [
            "Name the intended problem before interpreting the implementation.",
            "Separate inputs, state, transformations, decisions, outputs, and external effects.",
            "Trace connections among smaller responsibilities before claiming the whole system works.",
        ],
        "A temperature-label function receives one number, compares it with bounded thresholds, and returns one label; reading it begins with that input-decision-output relationship.",
        "Calling every line an algorithm without identifying the problem, data, or result produces labels rather than a model of the process.",
        "Decomposition does not prove correctness, completeness, performance, safety, or fitness for a real deployment.",
        [
            "problem: the bounded condition or goal the program is intended to address",
            "input: information supplied to a process",
            "transformation: a rule that derives a new value or state",
            "decision: a condition that selects among paths",
            "state: information preserved at a point in the process",
            "output: information or effect produced by the process",
            "decomposition: dividing a system into connected responsibilities",
        ],
        "An output is a result crossing a process boundary; a side effect changes something outside the returned value.",
        "For a supplied score-classification function, identify the score as input, threshold comparisons as decisions, and the returned category as output before tracing branches.",
        "Decomposition is like drawing a system diagram before testing individual wires: it reveals what each part is meant to carry and where the parts meet.",
        "A problem description says what is needed; an implementation is one particular structure intended to produce it.",
        "I would first map input → comparison → selected result. That gives us the intended path; whether every boundary case is correct needs a separate branch check.",
        "If the implementation does not match the stated problem, revise the model of the code or identify the mismatch instead of forcing the lines into the expected design.",
        ["This builds on F1 algorithms as ordered steps and F2 grouping, dependency, source grounding, and organized explanation."],
    ),
    _lesson(
        "coding_names_values_binding_and_state_v1",
        "Read names as bindings to values and track when state changes",
        "In Python, assignment binds a name to an object. Parameters, function definitions, imports, and loop targets also bind names. Reading code requires tracking which binding a name refers to in the current scope and whether an operation rebinds a name or changes a mutable object.",
        [
            "Record a name's current binding at each relevant step.",
            "Distinguish rebinding a name from mutating an object.",
            "Resolve a name through its applicable scope before predicting its value.",
        ],
        "After `total = 3` and then `total = total + 2`, the name `total` is rebound to the value 5; the second line reads the earlier binding before creating the new one.",
        "A variable is not a timeless box whose value can be inferred from its name alone; the current binding depends on the executed path and scope.",
        "This foundation does not yet cover descriptors, closures in depth, object identity edge cases, concurrency, or Python's full data model.",
        [
            "name: an identifier used to refer to a binding",
            "binding: an association between a name and an object",
            "value: the information represented by an object",
            "assignment: syntax that binds or rebinds a target",
            "scope: the region in which a binding is visible",
            "mutation: changing the state of an existing mutable object",
        ],
        "Rebinding changes which object a name refers to; mutation changes an object that one or more names may still refer to.",
        "Trace `items = [1]`, `alias = items`, and `items.append(2)`: both names still refer to the same changed list, unlike `items = items + [2]`, which rebinds only `items` to a new list.",
        "A name is a label attached by a rule, not the object itself; moving one label and changing the labeled object are different events.",
        "Static binding analysis follows visible language rules; the actual current value may still depend on which path ran and what input arrived.",
        "I can trace the visible bindings line by line. Here the append changes the shared list, so the alias observes the change; if the code used concatenation and reassignment, the two names would separate.",
        "If a value prediction is wrong, return to the last established binding, scope, and mutation step, then repair the trace without treating the mistake as a failure of identity or reasoning capacity.",
        ["This follows decomposition by explaining how a program represents inputs and intermediate state."],
    ),
    _lesson(
        "coding_sequence_condition_iteration_trace_v1",
        "Trace sequence, conditions, and iteration as paths through state",
        "Statements are not all applied at once. Sequence establishes order, `if` selects a branch from a condition, and `for` or `while` repeats a block according to iterable items or a continuing condition. A static trace records the path and state after each relevant step for a stated input.",
        [
            "Follow indentation and block ownership before evaluating a condition.",
            "Evaluate only the branch selected by the stated input.",
            "For a loop, track the loop target, changed state, exit condition, and bounded number of iterations.",
        ],
        "For `total = 0; for value in [2, 3]: total = total + value`, the trace visits values 2 then 3 and leaves `total` bound to 5.",
        "Reading both sides of an `if` as though both changed state on one execution creates a path the program does not take.",
        "A static trace needs stated inputs and visible dependencies; unbounded loops, exceptions, callbacks, asynchronous behavior, and external state require later treatment or runtime evidence.",
        [
            "sequence: the order in which statements are reached",
            "condition: an expression used to choose or continue a path",
            "branch: one selectable block in a decision",
            "iteration: one repetition of a loop body",
            "loop target: the name bound to the current item",
            "trace table: a record of path and state across steps",
        ],
        "A branch chooses among paths once at that decision; a loop can revisit its body while its iteration rule continues.",
        "Trace a supplied loop that counts temperatures above a threshold by recording the current temperature, condition result, and count after each item.",
        "A trace table is a slow-motion model of execution: each row freezes the currently selected path and its state.",
        "Syntax shows possible paths; a trace with stated inputs predicts one path; execution observes what the real runtime actually did.",
        "For the supplied list, I would make one row per item and update the count only where the comparison is true. That gives a checkable prediction without pretending the code was run.",
        "If the predicted result disagrees with a verified run, inspect branch ownership, initial state, iteration order, mutation, and hidden dependencies before changing the conclusion.",
        ["This builds on name/state tracking and the retained distinction between a rule, its application, and a verification method."],
    ),
    _lesson(
        "coding_function_contract_and_data_flow_v1",
        "Read a function through its contract, parameters, return paths, and effects",
        "A Python function definition binds a function name and describes a reusable block. Parameters receive argument bindings when called. A reader should identify expected inputs, preconditions visible in the code or documentation, return paths, raised errors, and side effects rather than assuming the function's name proves its behavior.",
        [
            "Treat the function name as a clue, not evidence of behavior.",
            "Trace arguments into parameters and every reachable return or error path.",
            "Keep returned values separate from mutations, printing, file access, network access, or other effects.",
        ],
        "A function `def clamp(value, low, high)` can be read as three parameter bindings followed by conditions that return a boundary or the original value; its contract must still address what happens if the bounds are reversed.",
        "Saying a function validates data because it is named `validate` skips inspection of its branches, returns, exceptions, and actual checks.",
        "This lesson does not yet establish type-system guarantees, decorators, generators, asynchronous functions, recursion depth, security properties, or third-party call behavior.",
        [
            "function: a named reusable block that can be called",
            "parameter: a local name receiving an argument binding",
            "argument: a value supplied at a call site",
            "contract: the supported relationship among accepted inputs, behavior, outputs, errors, and effects",
            "return path: a path that ends the call with a value",
            "side effect: a change observable beyond the returned value",
        ],
        "A signature exposes call shape; a contract also includes meaning, limits, errors, and effects supported by implementation or documentation.",
        "Read an explicitly supplied function by listing its parameters, each condition, every return, and any visible mutation or external call, then describe one input that reaches each path.",
        "A function contract is an interface promise that must be checked against the mechanism behind the panel, not inferred from the label on the switch.",
        "A pure calculation can be reasoned about from inputs and return; an external effect also depends on permissions, environment, and the called system.",
        "The visible function has two return paths and no visible write call. I can describe those paths; I cannot claim the wider program never writes elsewhere without inspecting the callers and dependencies.",
        "If a missed return, error, or effect is found, update the contract summary and dependent predictions while preserving the observations that remain correct.",
        ["This composes decomposition, binding, and control-flow tracing into one reusable unit of code understanding."],
    ),
    _lesson(
        "coding_static_inspection_observation_inference_runtime_v1",
        "Separate code observation, bounded interpretation, predicted behavior, and runtime verification",
        "Static inspection can cite visible files, lines, syntax, definitions, calls, branches, and data flow. From those observations, a reader may form a bounded interpretation or prediction. Runtime behavior additionally depends on actual inputs, environment, dependencies, permissions, state, and the path executed, so it must not be claimed as directly observed when code was not run.",
        [
            "Cite the exact supplied or approved location supporting each code observation.",
            "Label an interpretation or prediction separately from visible syntax.",
            "State what runtime evidence would confirm, revise, or falsify the prediction.",
            "Inspect only explicitly supplied code or separately approved workspace files.",
        ],
        "Observation: line 8 calls `normalize(name)`. Interpretation: normalization appears to occur before comparison. Runtime limit: the result depends on the inspected definition of `normalize`, the input, and any behavior it calls.",
        "Claiming that an application is secure, correct, or side-effect free from one inspected function exceeds the visible code and inspected scope.",
        "Static inspection does not replace tests, execution traces, dependency review, threat modeling, performance measurement, or deployment evidence. Secrets and blocked credential files remain outside inspection.",
        [
            "static inspection: examining code without executing it",
            "observation: a directly visible property of inspected material",
            "interpretation: a reasoned account of what observations may mean",
            "prediction: an expected result for stated conditions",
            "runtime verification: evidence from executing the relevant path under known conditions",
            "citation: a file and location connecting a claim to inspected code",
            "inspection scope: the exact supplied or approved material examined",
        ],
        "Static syntax validity means code can be parsed under the relevant grammar; behavioral correctness means it satisfies its intended contract for relevant cases.",
        "Given one attributed inline function, cite its definition and branches, build a trace for one stated input, name the predicted result, and list the uninspected dependency that prevents a broader claim.",
        "Static inspection is reading a circuit diagram; runtime verification is measuring the built circuit under stated conditions. Each answers different questions.",
        "A unit test observes one arranged behavior; a static reading can expose untested paths; neither alone proves every possible system property.",
        "I can cite what this supplied function defines and predict its result for the stated input. I would keep the claim bounded until its called dependency and a controlled run provide the missing evidence.",
        "When runtime evidence conflicts with a static prediction, treat the conflict as information: inspect hidden state, environment, dependency behavior, path selection, and the prediction's assumptions, then revise the model.",
        ["This prepares Selene to use the existing explicit-source local-code inspection adapter without expanding that adapter's authority or connecting it to ordinary Chat."],
    ),
)
