from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_light_sound_v1"
GROUP_KEY = "f1_light_sound_group_11"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
LIGHT_SOUND_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_light_sound",
    "sha256:2e2c486366244c72cde4c651fa9f99ecd6bbe3058558efaaad8821137db9663a",
    "https://www.coreknowledge.org/wp-content/uploads/2020/06/CKSci_G1U3_Exploring-Light-and-Sound.zip",
    "license:CC-BY-NC-SA-4.0",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ELA-1", "ELA-2", "ENG-1", "RES-1", "LOGIC-1"],
    "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_light_sound"],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_sound_vibration_cause_effect_v1",
        "title": "Vibrating matter can make sound, and sound can make matter vibrate",
        "domain": "curriculum.f1.light_sound",
        "material": "A vibration is repeated back-and-forth motion. Vibrating matter can produce sound, and sound reaching other matter can make that matter vibrate. These paired observations support a cause-and-effect relationship without requiring a complete wave model at this stage.",
        "principles": [
            "Look for or safely feel repeated back-and-forth motion when investigating a sound source.",
            "Test both directions of the relationship: vibration can make sound, and sound can cause vibration.",
            "Separate what was observed from a later explanation of how sound travels.",
        ],
        "relationships": ["This extends Group 10 motion and force observations into repeated motion, causal testing, and communication."],
        "examples": ["Plucking a stretched rubber band makes it vibrate and produces sound; a sufficiently strong nearby sound can make lightweight material on a stretched surface move."],
        "counterexamples": ["Hearing a sound without seeing its source move does not show that vibration is absent; the motion may be too small, fast, hidden, or distant to observe directly."],
        "limits": ["This F1 concept does not yet explain wave speed, frequency, wavelength, energy transfer, pressure, resonance, or the biology of hearing."],
        "vocabulary": [
            "vibration: repeated back-and-forth motion",
            "sound: an observable phenomenon associated here with vibrating matter",
            "sound source: the object or system producing the sound",
            "cause and effect: a relationship in which one event or interaction contributes to another",
        ],
        "near_concept_distinctions": ["A vibration is motion of matter; a sound is not simply the visible motion itself, even though the two are causally related."],
        "scope_of_application": "Use for safe elementary observations of sound sources and responsive materials. Do not claim that an unobserved vibration has been directly seen or that one demonstration supplies a complete theory of sound.",
        "unresolved_questions": ["Which object vibrated, what produced that vibration, and what observation links it to the sound?"],
        "explanation": "Sound and vibration are connected in both directions. Moving material can produce a sound, and arriving sound can move other material, even when the movement is difficult to see.",
        "application": "If a speaker plays while a nearby paper strip trembles, the speaker and the paper provide two observable parts of the relationship. A controlled comparison with the speaker silent helps test the cause.",
        "analogies": ["A vibration is like a tiny repeated push-pull motion; its effects can reach another material even when the original motion is hard to see."],
        "questions": ["What is vibrating, what sound is observed, and what comparison would test the connection?"],
        "comparisons": ["Vibration describes repeated motion; loud and soft describe perceived or measured sound level, not whether vibration exists at all."],
        "participation": "The rubber band moved back and forth when plucked, and a sound occurred at the same time. That supports the vibration-sound relationship in this setup without yet explaining every detail of transmission.",
        "correction_response": "If a second test does not reproduce the motion or sound, I would inspect the setup, measurement limits, and competing causes rather than force the expected result.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_light_sound"],
        "source_refs": LIGHT_SOUND_REFS,
    },
    {
        "concept_key": "curriculum_f1_sound_patterns_safe_comparison_v1",
        "title": "Sounds can be observed and compared without confusing their qualities",
        "domain": "curriculum.f1.light_sound",
        "material": "Sounds can differ in qualities such as loudness, duration, and higher or lower tone. A fair elementary comparison changes one relevant feature at a time and uses comfortable sound levels; louder does not mean higher, better, more important, or more correct.",
        "principles": [
            "Describe the sound quality being compared instead of relying only on a general word such as different.",
            "Keep the source, distance, surroundings, and procedure matched when one sound feature is the focus.",
            "Protect hearing: never increase loudness merely to make a result easier to notice.",
        ],
        "relationships": ["Sound comparison applies Group 9 pattern finding and Group 10 fair testing while preparing later measurement and musical concepts."],
        "examples": ["Two taps on the same object can be compared as softer and louder while the object and listening distance remain the same."],
        "counterexamples": ["A high whistle can be quiet and a low drum can be loud, so high and loud are not interchangeable descriptions."],
        "limits": ["F1 comparisons remain qualitative; decibels, frequency, pitch perception, timbre, hearing thresholds, and acoustic measurement require later instruction and suitable tools."],
        "vocabulary": [
            "loudness: how loud or soft a sound is perceived or measured to be",
            "duration: how long a sound lasts",
            "high or low tone: an elementary comparison of pitch without a frequency calculation",
            "pattern: a regularity or relationship noticed across observations",
        ],
        "near_concept_distinctions": ["Loudness concerns sound level; high or low tone concerns pitch; neither by itself identifies the source or meaning."],
        "scope_of_application": "Use for comfortable, bounded comparisons of ordinary sounds. Do not diagnose hearing, expose anyone to painfully loud sound, or infer precise acoustic quantities without measurement.",
        "unresolved_questions": ["Which sound quality changed, which conditions stayed matched, and was the observation safe and repeatable?"],
        "explanation": "Sound has more than one describable quality. Naming the quality and matching the other conditions prevents one difference from being mistaken for another.",
        "application": "A doorbell signal might need to be audible from another room, but increasing loudness without limit is not a good design. Distance, repetition, duration, and visual signals may also be tested safely.",
        "analogies": ["Sound qualities are like separate sliders: changing one slider does not guarantee that the others changed."],
        "questions": ["Are we comparing loudness, duration, or higher and lower tone, and how can we do it without uncomfortable exposure?"],
        "comparisons": ["A louder sound is not necessarily higher in pitch; a longer sound is not necessarily louder."],
        "participation": "The second tap sounded louder from the same distance, while its tone seemed similar. I would call that a loudness comparison, not a pitch measurement.",
        "correction_response": "If I confuse loudness with pitch or use unmatched distances, I would rename the observed feature, narrow the claim, and repeat only if a safe comparison is still needed.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "ELA-1", "RES-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_light_sound"],
        "source_refs": LIGHT_SOUND_REFS,
    },
    {
        "concept_key": "curriculum_f1_light_sources_illumination_visibility_v1",
        "title": "Light sources give off light; other objects are seen when illuminated",
        "domain": "curriculum.f1.light_sound",
        "material": "A light source gives off its own light. An object that is not a light source becomes visible when enough light from a source reaches it and then reaches an observer. Darkness is an absence or shortage of visible light in the situation, not a substance covering the object.",
        "principles": [
            "Distinguish an object that gives off light from an object made visible by light.",
            "Compare visibility with and without illumination while keeping the object and viewing position sufficiently alike.",
            "Use safe ordinary light sources; never stare at the Sun, lasers, or painfully bright lamps.",
        ],
        "relationships": ["Illumination connects source, path, object, observer, and evidence in a simple system model."],
        "examples": ["A lamp is a light source; a book beside it does not make its own light but becomes visible when the lamp illuminates it."],
        "counterexamples": ["The Moon appearing bright does not make it an ordinary light source like the Sun; it is mainly visible because it reflects sunlight."],
        "limits": ["F1 does not yet calculate light intensity or speed, explain photons or electromagnetic waves, or fully model reflection and vision."],
        "vocabulary": [
            "light source: an object or system that gives off light",
            "illuminate: shine light on something so it can be seen",
            "visible: able to be seen under the present conditions",
            "darkness: a condition with little or no visible light",
        ],
        "near_concept_distinctions": ["Giving off light and reflecting light can both make an object look bright, but they are different roles in the light path."],
        "scope_of_application": "Use to reason about ordinary visibility and light sources. Preserve the observer and conditions, and defer advanced optics, vision biology, and hazardous sources.",
        "unresolved_questions": ["What is the light source, what is being illuminated, and how does the available light reach the observer?"],
        "explanation": "Seeing an ordinary object depends on light. Some things produce light, while many other things are visible because source light reaches them and is redirected toward our eyes or a sensor.",
        "application": "A reflective road sign is easy to see in headlights but is not thereby producing the headlight beam. The vehicle supplies the illumination and the sign redirects some light toward the observer.",
        "analogies": ["A light source supplies the message carrier; an illuminated object redirects some of it so an observer can receive information about the object."],
        "questions": ["Does this object make light, or is another source making it visible?"],
        "comparisons": ["A luminous source gives off light; an illuminated nonluminous object is seen because light reaches it from elsewhere."],
        "participation": "The toy disappeared from view when the box had no useful illumination and became visible when light entered. The toy did not stop existing; the viewing conditions changed.",
        "correction_response": "If I label every bright-looking object a source, I would trace the light path and separate emitted light from reflected illumination.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_light_sound"],
        "source_refs": LIGHT_SOUND_REFS,
    },
    {
        "concept_key": "curriculum_f1_light_materials_transmit_block_reflect_v1",
        "title": "Materials can transmit, block, or redirect different amounts of light",
        "domain": "curriculum.f1.light_sound",
        "material": "When light meets a material, some may pass through, some may be blocked or absorbed, and some may be redirected or reflected. Transparent, translucent, and opaque are useful relative descriptions of how materials transmit visible light under stated conditions.",
        "principles": [
            "Compare materials with the same safe light source, distance, background, and observation method.",
            "Treat transparent, translucent, and opaque as descriptions of behavior under conditions, not as complete identities of a substance.",
            "A reflected image is evidence of redirected light; it does not mean light passed straight through the material.",
        ],
        "relationships": ["This joins Group 9 material properties with illumination, fair comparison, classification, and evidence-based revision."],
        "examples": ["Clear glass may transmit much visible light, waxed paper may transmit some while scattering it, cardboard may block nearly all, and a mirror may redirect enough light to form an image."],
        "counterexamples": ["Transparent does not mean invisible or that every kind of radiation passes through; the word is relative to the light and conditions being discussed."],
        "limits": ["F1 does not yet quantify absorption, transmission, reflection, refraction, color spectra, polarization, or wavelength-dependent behavior."],
        "vocabulary": [
            "transparent: allowing enough visible light through for objects beyond to be seen clearly under stated conditions",
            "translucent: allowing some visible light through without a clear view through the material",
            "opaque: allowing little or no visible light through under stated conditions",
            "reflect: redirect light from a surface",
        ],
        "near_concept_distinctions": ["Transmission sends light through a material; reflection redirects light from it; blocking describes light that does not continue through the tested path."],
        "scope_of_application": "Use for qualitative visible-light tests with ordinary materials. Avoid universal labels when thickness, surface, color, or the kind of light could change the result.",
        "unresolved_questions": ["How much light passed through, what was redirected, and which material or condition produced the difference?"],
        "explanation": "Materials do not all interact with light the same way. A controlled observation can distinguish light passing through, being blocked, or being redirected without pretending the categories explain every optical detail.",
        "application": "A lampshade needs to transmit and scatter enough light for gentle illumination while hiding the bare bulb. Clear window glass serves a different purpose because a view through it matters.",
        "analogies": ["Materials act like different gates and turners for light: some let much through, some let a blurred amount through, some block it, and some send it another way."],
        "questions": ["Did the light pass through, become reduced, or redirect, and were the comparison conditions matched?"],
        "comparisons": ["Transparent, translucent, and opaque compare transmission; reflective describes redirection and can coexist with one of those behaviors."],
        "participation": "The waxed paper let light through but blurred the object behind it, so translucent fits this setup better than transparent. I would keep the claim tied to visible light and this thickness.",
        "correction_response": "If a material behaves differently when its thickness or light source changes, I would revise the classification to include those conditions rather than treat the earlier observation as a failure.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_light_sound"],
        "source_refs": LIGHT_SOUND_REFS,
    },
    {
        "concept_key": "curriculum_f1_shadows_blocked_light_model_v1",
        "title": "A shadow is a region receiving less light because an object blocks a path",
        "domain": "curriculum.f1.light_sound",
        "material": "A shadow forms where an object blocks some light from reaching a surface or region. The shadow is a darker region caused by reduced illumination, not a separate object or substance. Its position and shape depend on the arrangement of source, blocker, and receiving surface.",
        "principles": [
            "Identify the light source, the blocking object, and the region or surface receiving less light.",
            "Move one part of the arrangement at a time when investigating shadow changes.",
            "Use shadows as evidence about a light path while recognizing that soft edges and multiple sources can complicate the pattern.",
        ],
        "relationships": ["Shadow reasoning applies position, relative arrangement, material opacity, models, prediction, and controlled change."],
        "examples": ["A hand between a flashlight and a wall blocks some light, producing a darker hand-shaped region on the wall."],
        "counterexamples": ["A dark mark painted on a wall is not a shadow because moving the light or blocker does not create its darkness in the same way."],
        "limits": ["F1 does not yet model ray geometry, umbra and penumbra, eclipses, diffraction, or quantitative shadow size."],
        "vocabulary": [
            "shadow: a region receiving less light because an object blocks part of the light path",
            "blocker: the object interrupting part of a light path",
            "arrangement: the relative positions of parts in a system",
            "prediction: a stated expected observation based on a model or pattern",
        ],
        "near_concept_distinctions": ["A shadow is a lighting condition in a region; a dark object or painted shape is material located there."],
        "scope_of_application": "Use for ordinary safe light-source, blocker, and surface arrangements. Keep conclusions qualitative when source size, multiple lights, transparency, or three-dimensional geometry matter.",
        "unresolved_questions": ["Which source is blocked, which object blocks it, and where should the darker region appear if one part moves?"],
        "explanation": "A shadow records an interrupted light path. Thinking in terms of source, blocker, and receiving region explains why shadows move or change when the arrangement changes.",
        "application": "A tree shades part of a bench because it blocks some sunlight. As the source direction relative to the tree and bench changes through the day, the shadow location also changes.",
        "analogies": ["A shadow is like a delivery gap: the receiving area gets less light because something interrupts part of the route."],
        "questions": ["Where is the source, what blocks it, where is the shadow, and what should change if one part moves?"],
        "comparisons": ["An opaque blocker often creates a darker shadow than a translucent blocker because less light continues through it under matched conditions."],
        "participation": "The darker region moved when the flashlight moved, which fits a shadow model based on the changing source-blocker-wall arrangement.",
        "correction_response": "If the predicted shadow does not appear, I would inspect alignment, surrounding light, material transmission, and the receiving surface before revising the model.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "MATH-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_light_sound"],
        "source_refs": LIGHT_SOUND_REFS,
    },
    {
        "concept_key": "curriculum_f1_light_sound_communication_design_v1",
        "title": "Light and sound patterns can communicate information across distance",
        "domain": "curriculum.f1.light_sound",
        "material": "People can use agreed patterns of light or sound as signals that carry information across a distance. A communication design identifies the message, sender, signal, receiver, environment, and success criterion, then tests whether the intended information can be detected and distinguished safely.",
        "principles": [
            "Agree on what a signal means before treating detection as successful communication.",
            "Test whether the intended receiver can distinguish the signal under the actual distance and environmental conditions.",
            "Choose safe brightness and loudness and consider accessibility, privacy, ambiguity, and alternate channels.",
        ],
        "relationships": ["This integrates light, sound, patterns, symbols, algorithms, evidence, collaboration, and bounded engineering iteration."],
        "examples": ["A repeating flashlight pattern can signal begin to a distant teammate when both people know the code and can see it safely."],
        "counterexamples": ["A light flashing where nobody knows its meaning is detectable activity, but it has not necessarily communicated the intended information."],
        "limits": ["F1 does not explain radio, fiber optics, digital encoding, bandwidth, encryption, networking, electronics, or safety-critical signaling standards."],
        "vocabulary": [
            "signal: an observable pattern used to convey information",
            "sender: the person or system producing a signal",
            "receiver: the person or system intended to detect and interpret a signal",
            "code: an agreed mapping between patterns and meanings",
        ],
        "near_concept_distinctions": ["Detection means noticing a signal; interpretation assigns meaning; successful communication requires the intended information to reach and be understood by the receiver."],
        "scope_of_application": "Use for safe elementary signal design and synthetic or ordinary-object trials. Escalate emergency, medical, navigation, electrical, surveillance, or security-critical communications to appropriate standards and expertise.",
        "unresolved_questions": ["What message must cross what distance, who must receive it, and what evidence will show that it was understood rather than merely noticed?"],
        "explanation": "Light and sound become communication tools when their patterns have shared meaning and reach an intended receiver. A good design tests the whole path and revises from evidence.",
        "application": "A classroom team can compare a soft chime and a safe flashlight pattern for signaling a turn across a room, checking detectability, clarity, accessibility, and disruption before choosing.",
        "analogies": ["A signal is a carrier and a code is the shared key: noticing the carrier is not enough if the receiver cannot interpret the key."],
        "questions": ["What does the signal mean, can the receiver safely distinguish it here, and what would count as successful understanding?"],
        "comparisons": ["Light may work where quiet matters and sightlines exist; sound may work without a sightline but can disturb others or be inaccessible in different ways."],
        "participation": "The back-row receiver detected three flashes and correctly interpreted the agreed message twice. That supports the design under this room's conditions, not in every environment.",
        "correction_response": "If the receiver misses or misreads the signal, I would treat that as design evidence, inspect distance and ambiguity, and revise the smallest relevant feature without increasing sensory risk.",
        "families": ["SCI-0", "SCI-1", "SCI-2", "ELA-1", "ENG-1", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_light_sound"],
        "source_refs": LIGHT_SOUND_REFS,
    },
)
