from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_history_evidence_foundations_v1"
GROUP_KEY = "f1_history_evidence_group_8"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
HISTORY_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_civics",
    "sha256:ea24fedc236ef8d3ef6b6491cfbd847f16f5adee0487dbecad030d6fec5f4f99",
    "https://www.coreknowledge.org/wp-content/uploads/2023/12/CKHG_G1U10_LessonsInCivics_Web_W1.zip",
    "license:CC-BY-NC-SA-4.0",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["HIST-1", "ELA-1", "ELA-2", "SCI-0", "RES-1", "CULT-1", "LOGIC-1"],
    "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_chronology_relationships_v1",
        "title": "Chronology orders events without proving why they happened",
        "domain": "curriculum.f1.history_evidence",
        "material": "Chronology places events in time using relations such as before, after, during, past, present, and future. Order is necessary for explaining change, but an earlier event is not automatically the cause of a later one.",
        "principles": [
            "Dates and sequence organize when events occurred.",
            "Duration describes how long something continued or the interval between events.",
            "Earlier than does not by itself mean caused.",
        ],
        "relationships": ["Chronology builds on sequence and time measurement and supports cause, continuity, change, and source comparison."],
        "examples": ["A storm began before the power failed; the order is established, while evidence is still needed to show whether the storm caused the failure."],
        "counterexamples": ["Two events occurring one after another does not prove that the first produced the second."],
        "limits": ["Dates can be approximate, calendars differ, sources may conflict, and some processes overlap rather than forming one simple line."],
        "vocabulary": [
            "chronology: the time order of events",
            "duration: how long an event or condition continues",
            "interval: the time between events",
            "sequence: an ordered relationship among events or steps",
        ],
        "near_concept_distinctions": ["Chronology answers when and in what order; causation asks why one condition helped produce another."],
        "scope_of_application": "Use to order events and establish temporal constraints before proposing causes. Preserve approximate dates, overlap, and source disagreement.",
        "unresolved_questions": ["Which dates are directly supported, and what additional evidence would connect the sequence to a cause?"],
        "explanation": "History needs a time structure because causes cannot follow their effects and change requires a before-and-after comparison. But order alone is only one condition for a causal explanation.",
        "application": "A project log can show that errors increased after an update. That chronology identifies where to investigate, but configuration, traffic, or another change may still explain the errors.",
        "analogies": ["Chronology is the frame of a film; it puts scenes in order without automatically explaining every character's motive."],
        "questions": ["What happened first, what overlapped, and which causal link still needs evidence?"],
        "comparisons": ["A timeline organizes events; an explanation connects selected events through supported mechanisms or conditions."],
        "participation": "The timeline shows the policy changed before the outcome, so it is relevant. I would not call it the cause until we compare other conditions and evidence.",
        "correction_response": "If I confuse sequence with cause, I would preserve the supported order, withdraw the unsupported causal claim, and identify what evidence is missing.",
        "families": ["HIST-1", "ELA-1", "SCI-0", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": HISTORY_REFS,
    },
    {
        "concept_key": "curriculum_f1_maps_selective_models_v1",
        "title": "Maps are selective models of place and relationship",
        "domain": "curriculum.f1.history_evidence",
        "material": "A map represents selected locations, directions, distances, boundaries, or features using a scale and symbols. It is made for a purpose and leaves most details out.",
        "principles": [
            "Map symbols and labels stand for selected features rather than reproducing the place itself.",
            "Direction, location, distance, and boundary are different spatial relationships.",
            "A map's purpose, date, scale, and maker affect what it can support.",
        ],
        "relationships": ["Maps connect spatial reference, geometry, models, chronology, community scale, travel, and historical change."],
        "examples": ["A road map can support a route comparison while omitting vegetation, building interiors, and temporary road closures."],
        "counterexamples": ["A large shape on a map is not necessarily physically large if the map is schematic or uses a different scale."],
        "limits": ["Maps may be outdated, distorted, incomplete, disputed, or designed for a purpose that does not fit the current question."],
        "vocabulary": [
            "map: a selective spatial representation",
            "legend: an explanation of map symbols",
            "scale: the relationship between represented and actual distance or size",
            "boundary: a line or region used to distinguish areas",
        ],
        "near_concept_distinctions": ["A place is the actual setting; a map is one representation of selected relationships within or among places."],
        "scope_of_application": "Use a map only for relationships its symbols, scale, date, and purpose support. Verify changing or disputed features from appropriate current sources.",
        "unresolved_questions": ["Who made this map, when, for what purpose, and which omitted feature could change the answer?"],
        "explanation": "A useful map reduces a complicated place to the relationships needed for a task. The reduction makes reasoning possible, while the omitted details and chosen boundaries limit the conclusion.",
        "application": "A historical map can show where a settlement was represented at one time, but a current route requires a current road source rather than assuming nothing changed.",
        "analogies": ["A map is like a diagram of a machine: it highlights relevant relationships rather than copying every physical detail."],
        "questions": ["What relationship does this map actually show, and is its date and scale suitable for the question?"],
        "comparisons": ["A map locates selected spatial relationships; a photograph records visible features from one viewpoint."],
        "participation": "This map supports the relative locations, but it is old and does not establish the present boundary. I would keep the historical claim and verify the current one separately.",
        "correction_response": "If I treat a map as the territory or overlook its date and scale, I would narrow the claim to what the representation supports and seek a better-fitting source.",
        "families": ["HIST-1", "ELA-2", "SCI-0", "CULT-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": HISTORY_REFS,
    },
    {
        "concept_key": "curriculum_f1_historical_sources_traces_v1",
        "title": "Sources are surviving traces used to study the past",
        "domain": "curriculum.f1.history_evidence",
        "material": "Artifacts, photographs, documents, stories, recordings, buildings, and records can provide evidence about the past. A source is a surviving trace or account, not the past itself.",
        "principles": [
            "Identify what kind of source it is, who made or preserved it, and when.",
            "A source directly supports some observations while other conclusions require inference.",
            "What survives can be incomplete and can overrepresent people or institutions with more power to create and preserve records.",
        ],
        "relationships": ["Historical sources extend provenance, observation-versus-interpretation, personal accounts, material evidence, and correction."],
        "examples": ["A dated shop receipt directly records listed goods and prices in that transaction; it does not by itself show what every household bought."],
        "counterexamples": ["An old-looking object without provenance is not reliable evidence for a precise place, owner, or date."],
        "limits": ["Sources may be damaged, staged, copied, translated, misdated, biased, forged, or separated from their original context."],
        "vocabulary": [
            "source: material or testimony used as evidence",
            "artifact: an object made, modified, or used by people",
            "record: preserved information about an event, decision, person, or process",
            "provenance: the documented origin and custody of a source",
        ],
        "near_concept_distinctions": ["A source is evidence available for study; an interpretation is a conclusion drawn from one or more sources."],
        "scope_of_application": "Use sources to make bounded claims about the past while preserving origin, date, context, and uncertainty. Do not generalize one trace to an entire population without support.",
        "unresolved_questions": ["What does this source directly establish, what context is missing, and what may not have survived?"],
        "explanation": "The past cannot be replayed in full, so historical understanding is reconstructed from traces. Provenance and context help show what each trace can support and where its silence matters.",
        "application": "A maintenance log can establish that a repair was recorded on a date. Whether the repair was effective requires inspection, later records, or other evidence.",
        "analogies": ["Historical sources are pieces of a damaged mosaic: each piece is real evidence, but the missing pieces constrain the picture."],
        "questions": ["What is this source, where did it come from, and which claim can it support directly?"],
        "comparisons": ["An artifact can preserve material evidence; a written account can preserve a person's report or purpose; neither automatically supplies the whole event."],
        "participation": "The record supports that this transaction was documented. I would not extend it to everyone's experience without a broader and more representative source set.",
        "correction_response": "If provenance or context changes, I would revise the claims that depend on it while preserving observations the source still supports.",
        "families": ["HIST-1", "ELA-2", "RES-1", "CULT-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": HISTORY_REFS,
    },
    {
        "concept_key": "curriculum_f1_source_statement_inference_v1",
        "title": "A source statement and an inference are different claims",
        "domain": "curriculum.f1.history_evidence",
        "material": "A source statement reports what a source says or visibly contains. An inference connects that evidence to a further conclusion. Both can be useful, but they should not be presented as the same kind of support.",
        "principles": [
            "Quote or paraphrase a source accurately before extending it.",
            "Label an inference and name the evidence and assumptions connecting it to the conclusion.",
            "A plausible inference remains revisable when another explanation fits the evidence.",
        ],
        "relationships": ["This distinction applies observation-versus-interpretation to documents, testimony, research, and historical explanation."],
        "examples": ["A letter says a journey was difficult; concluding that weather caused the difficulty requires additional wording or evidence."],
        "counterexamples": ["Adding 'the source proves' does not convert an unstated interpretation into a direct source statement."],
        "limits": ["Translation, missing context, irony, genre, and ambiguous wording can make even a source statement uncertain."],
        "vocabulary": [
            "source statement: a bounded report of what a source says or contains",
            "inference: a conclusion drawn from evidence and connecting assumptions",
            "paraphrase: a new wording that preserves the source's supported meaning",
            "assumption: a premise used in connecting evidence to a conclusion",
        ],
        "near_concept_distinctions": ["Attribution identifies whose statement is being reported; agreement is a separate judgment about whether that statement is correct."],
        "scope_of_application": "Use whenever answering from documents, accounts, datasets, or cited research. Preserve attribution and mark conclusions that go beyond the source's explicit content.",
        "unresolved_questions": ["Which part is directly in the source, and which premise carries the inference beyond it?"],
        "explanation": "Separating report from inference lets another reader inspect the same evidence without being forced to accept the interpretation. It also makes corrections local rather than discarding the whole source.",
        "application": "If a test log records three failures after noon, the count and timing are source statements. Calling heat the cause is an inference needing temperature or comparison evidence.",
        "analogies": ["The source is the set of puzzle pieces on the table; the inference is one proposed way they fit."],
        "questions": ["Can I point to the source for this wording, or am I making a supported but revisable inference?"],
        "comparisons": ["A source statement preserves attributed content; an inference explains or extends it through reasoning."],
        "participation": "The account explicitly reports a shortage. My best inference is that disrupted transport contributed, but the source does not say that directly.",
        "correction_response": "If I mistake an inference for a source statement, I would restore the attribution boundary and revise only the unsupported extension.",
        "families": ["HIST-1", "ELA-1", "ELA-2", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": HISTORY_REFS,
    },
    {
        "concept_key": "curriculum_f1_differing_accounts_perspective_v1",
        "title": "Different accounts can preserve different access and perspectives",
        "domain": "curriculum.f1.history_evidence",
        "material": "People can describe the same event differently because they observed different parts, remembered differently, used different categories, had different purposes, or interpreted the event from different positions.",
        "principles": [
            "Difference between accounts is a reason to compare evidence, not proof that every account is false.",
            "Perspective affects access and interpretation without making truth only a matter of preference.",
            "Agreement among accounts is stronger when they are genuinely independent and fit other evidence.",
        ],
        "relationships": ["Differing accounts connect source provenance, uncertainty, community perspective, corroboration, and respectful disagreement."],
        "examples": ["A participant near a doorway and a participant across the room may accurately report different parts of one interruption."],
        "counterexamples": ["Two incompatible claims do not become equally supported merely because each reflects a perspective."],
        "limits": ["Memory, incentives, coercion, translation, missing access, and later retelling can alter an account; perspective alone does not diagnose motive or dishonesty."],
        "vocabulary": [
            "account: a description or report of an event",
            "perspective: the position, access, background, and interpretive frame from which something is considered",
            "corroboration: support from another source or independent evidence",
            "disagreement: a difference in report, interpretation, judgment, or preference",
        ],
        "near_concept_distinctions": ["Perspective explains a possible source of difference; bias is a systematic influence that must be supported rather than assumed."],
        "scope_of_application": "Use to compare accounts by access, timing, purpose, detail, independence, and fit with other evidence. Do not flatten supported and unsupported accounts into equal truth.",
        "unresolved_questions": ["What could each source observe, where do they agree, and which external evidence can distinguish the conflicting parts?"],
        "explanation": "No observer occupies every position. Comparing access and independent evidence can combine partial accounts, locate genuine conflict, and preserve uncertainty without abandoning the possibility of a best-supported account.",
        "application": "Two users can report that an app failed differently because one lost network access and the other encountered a local crash. Logs may show whether these were distinct failures rather than one dishonest report.",
        "analogies": ["Accounts are like views of one object from different sides: several views add information, but a blocked or distorted view still needs checking."],
        "questions": ["What could each person know from their position, and what evidence would test the disputed detail?"],
        "comparisons": ["Perspective shapes what is accessible; corroboration checks a claim against additional evidence."],
        "participation": "The accounts disagree about the cause but agree on the time and visible result. I would preserve that agreement and use independent evidence to test the causal claims.",
        "correction_response": "If I dismiss an account merely for differing or accept all accounts equally, I would compare access, support, independence, and the exact point of conflict.",
        "families": ["HIST-1", "ELA-2", "RES-1", "CULT-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": HISTORY_REFS,
    },
    {
        "concept_key": "curriculum_f1_historical_why_multiple_causes_v1",
        "title": "Historical why questions can involve several causes and consequences",
        "domain": "curriculum.f1.history_evidence",
        "material": "A historical explanation may distinguish long-term conditions, contributing causes, a nearer trigger, decisions, mechanisms, and consequences. One simple cause is often insufficient, and later importance depends on supported connections rather than resemblance alone.",
        "principles": [
            "Ask what made an event possible, what pushed it toward occurring, and what immediately changed.",
            "Separate a cause from a consequence and an intended result from an unintended one.",
            "Use the past to inform the present by comparing both similarities and material differences.",
        ],
        "relationships": ["Multi-cause explanation integrates chronology, source evidence, systems, models, rule purposes, and correction."],
        "examples": ["A bridge closure may involve long-term deterioration, delayed maintenance, heavy rainfall, and a final inspection finding; the closure itself then has intended safety effects and unintended travel effects."],
        "counterexamples": ["Naming the event immediately before a crisis does not establish that it was the only cause."],
        "limits": ["Causes may be disputed, evidence may be missing, participants may have different motives, and present-day analogies can mislead when context differs."],
        "vocabulary": [
            "condition: a circumstance that shapes what is possible",
            "contributing cause: a factor that helps produce an outcome",
            "trigger: a nearer event that helps initiate a change",
            "consequence: an outcome following from an event or decision",
        ],
        "near_concept_distinctions": ["A reason can describe a participant's stated motive; a cause describes a factor in producing the event; importance describes why understanding it matters for another question."],
        "scope_of_application": "Use for bounded historical and systems explanations. Attribute motives, compare alternative causal structures, and state what evidence would revise the explanation.",
        "unresolved_questions": ["Which condition, trigger, decision, or mechanism is supported, and what alternative explanation still fits?"],
        "explanation": "Events emerge from systems already in motion. Separating background conditions, nearer triggers, choices, and consequences produces an explanation that can be tested and revised instead of turning history into a memorized date or one inevitable story.",
        "application": "To explain a project delay, distinguish the existing staffing constraint, a supplier failure, the decision not to use a backup, and the later effects rather than calling the final missed delivery the sole cause.",
        "analogies": ["A historical event can be like a fire: dry material, heat, oxygen, and an ignition source play different causal roles, while the damage is a consequence."],
        "questions": ["What conditions accumulated, what changed nearest the event, and which consequences followed?"],
        "comparisons": ["Chronology orders events; causal explanation connects conditions and mechanisms; significance explains why the supported pattern matters."],
        "participation": "The immediate trigger matters, but it acted within older conditions. I would explain both and avoid claiming the present case is identical merely because one feature resembles the past.",
        "correction_response": "If new evidence weakens one cause, I would revise its role while preserving other supported conditions and consequences rather than replacing the whole history with another single cause.",
        "families": ["HIST-1", "ELA-2", "SCI-0", "RES-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_civics"],
        "source_refs": HISTORY_REFS,
    },
)
