from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f2_factors_multiples_operation_order_v1"
GROUP_KEY = "f2_factors_multiples_operation_order_group_5"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
    "source_locator:Grade 3-5 Mathematics factors multiples primes divisibility and numerical expressions sequence",
    "license:Core-Knowledge-artifact-notice-controls",
]

SCOPE = {
    "bands": ["F2"],
    "families": ["MATH-1", "MATH-2", "ELA-1", "LOGIC-1"],
    "source_ids": ["core_knowledge_2023_sequence_k8"],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}


def _lesson(
    concept_key: str,
    title: str,
    material: str,
    principles: list[str],
    example: str,
    counterexample: str,
    limits: str,
    vocabulary: list[str],
    distinction: str,
    application: str,
    analogy: str,
    comparison: str,
    participation: str,
    correction: str,
) -> dict[str, Any]:
    return {
        "concept_key": concept_key,
        "title": title,
        "domain": "curriculum.f2.factors_multiples_operation_order",
        "material": material,
        "principles": principles,
        "relationships": ["This extends retained F1 equal-group, array, sharing, equality, and F2 whole-number operation relationships."],
        "examples": [example],
        "counterexamples": [counterexample],
        "limits": [limits],
        "vocabulary": vocabulary,
        "near_concept_distinctions": [distinction],
        "scope_of_application": "Use for nonnegative whole-number factor relationships and numerical expressions. Preserve grouping and verify through multiplication, division, or an equivalent representation.",
        "unresolved_questions": ["Which representation or inverse relationship would most clearly expose a mistake here?"],
        "explanation": (
            f"This relationship can be reconstructed as follows: {analogy} "
            "A conclusion is accepted only when an equivalent grouping, product, quotient, or recomputed expression preserves the same quantity."
        ),
        "application": application,
        "analogies": [analogy],
        "questions": ["What relationship determines the result, and how can it be checked without merely repeating the same steps?"],
        "comparisons": [comparison],
        "participation": participation,
        "correction_response": correction,
        "families": ["MATH-1", "MATH-2", "ELA-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8"],
        "source_refs": SEQUENCE_REFS,
    }


LESSONS: tuple[dict[str, Any], ...] = (
    _lesson(
        "curriculum_f2_factor_multiple_relationships_v1",
        "Factors and multiples describe one multiplication relationship from different directions",
        "When two whole numbers multiply to make a product, each is a factor of that product and the product is a multiple of each factor. Factor pairs can be found systematically by testing divisors only until pairs begin to repeat. Multiplication and exact division verify the relationship.",
        ["Connect every factor claim to an exact whole-number product.", "List factor pairs systematically without duplicating reversed pairs.", "Verify a factor with division that leaves no remainder."],
        "For 24, the factor pairs are 1×24, 2×12, 3×8, and 4×6; therefore 24 is a multiple of every number in those pairs.",
        "Six is not a factor of 25 because 25 ÷ 6 leaves a remainder, even though six is near one quarter of 25.",
        "This lesson concerns positive whole-number factors; zero, negative factors, fractions, and algebraic factors need later treatment.",
        ["factor: a whole number that divides another exactly", "multiple: a product of a number and a whole number", "factor pair: two factors whose product is the target", "divisible: producing a whole-number quotient with no remainder"],
        "A factor is a component of a product relationship; a multiple is a result generated by that relationship.",
        "To arrange 36 objects into equal rectangular rows, use its factor pairs to identify every possible whole-number row-by-column arrangement.",
        "Factor pairs are the possible whole rectangular dimensions for one fixed collection of tiles.",
        "Factors of one number form a bounded list; positive multiples of a nonzero number continue without end.",
        "Thirty-six can form 1×36, 2×18, 3×12, 4×9, and 6×6 arrays; reversed orientations do not create new factor pairs.",
        "If a proposed factor leaves a remainder, I would remove it from the factor list and use the remainder as evidence for the correction.",
    ),
    _lesson(
        "curriculum_f2_prime_composite_classification_v1",
        "Prime and composite classify positive whole numbers by their factor structure",
        "A prime number greater than one has exactly two positive factors: one and itself. A composite number greater than one has more than two positive factors and can be represented by a nontrivial factor pair. One is neither prime nor composite because it has only one positive factor.",
        ["Find or rule out nontrivial factor pairs before classifying.", "Keep one outside both prime and composite categories.", "Treat classification as a claim supported by factor evidence."],
        "29 is prime because no whole-number divisor from 2 through 5 divides it exactly; 30 is composite because 5×6=30.",
        "Calling 1 prime because it is divisible by itself ignores that a prime must have two distinct positive factors.",
        "This is elementary classification, not prime factorization proofs, negative primes, or advanced number theory.",
        ["prime: a whole number greater than one with exactly two positive factors", "composite: a whole number greater than one with more than two positive factors", "nontrivial factor: a factor other than one or the number itself", "classification: grouping by a stated defining property"],
        "Odd does not mean prime: 9 is odd but composite because 3×3=9.",
        "To decide whether 37 can be arranged as a nontrivial rectangle, test possible small side lengths; none divide exactly, so it is prime.",
        "A prime-sized tile collection makes only a one-by-itself rectangle; a composite collection makes at least one additional rectangle.",
        "Prime/composite describes factor count; even/odd describes divisibility by two.",
        "Thirty-seven has only 1×37, while 39 has 3×13, so their nearby values do not imply the same classification.",
        "If a new factor pair is found, I would revise a prime claim to composite without treating the earlier claim as a personal failure.",
    ),
    _lesson(
        "curriculum_f2_divisibility_patterns_reasoning_v1",
        "Divisibility patterns are place-value shortcuts that still require a valid relationship",
        "Base-ten place value creates useful divisibility tests. A number is divisible by 2 when its ones digit is even, by 5 when its ones digit is 0 or 5, and by 10 when its ones digit is 0. Divisibility by 3 follows when the sum of the digits is divisible by 3. These are justified shortcuts for exact division, not guesses about magnitude.",
        ["Apply a rule only to the divisor it actually tests.", "Connect the shortcut to base-ten place value or verify it with exact division.", "A failed test rules out divisibility but does not make the number mathematically defective."],
        "4,572 is divisible by 2 because its last digit is even and by 3 because 4+5+7+2=18, which is divisible by 3.",
        "A final digit of 5 proves divisibility by 5, not divisibility by every odd number.",
        "Only selected elementary base-ten tests are taught here; other bases and more advanced divisibility rules require separate justification.",
        ["divisibility test: a justified shortcut for deciding exact divisibility", "digit sum: the sum of a number's base-ten digits", "remainder: what remains after forming complete equal groups", "base ten: a place-value system built from powers of ten"],
        "A divisibility test predicts whether the remainder is zero; it does not replace understanding what division means.",
        "Determine whether 7,245 can be split equally among five groups: its final digit is 5, and exact division confirms 7,245 ÷ 5 = 1,449.",
        "A divisibility rule is a reliable inspection window into the same grouping relationship that long division checks directly.",
        "Divisibility by 2 reads the ones place; divisibility by 3 combines all digits through a place-value invariant.",
        "The shortcuts say 4,572 is divisible by both 2 and 3, so it is divisible by 6; division verifies a quotient of 762.",
        "If a shortcut and exact division disagree, I would inspect whether I used the correct rule and recompute rather than trust the shortcut blindly.",
    ),
    _lesson(
        "curriculum_f2_grouping_operation_order_v1",
        "Grouping and operation order preserve the intended structure of a numerical expression",
        "A numerical expression can encode several operations. Grouping symbols identify a quantity that must be formed as a unit first. Without additional grouping, multiplication and division are evaluated before addition and subtraction; operations at the same priority are evaluated from left to right. The convention prevents one written expression from silently receiving incompatible meanings.",
        ["Evaluate explicit grouping before outside operations.", "Respect operation priority without treating a mnemonic as the reason.", "Evaluate equal-priority operations from left to right and verify by rewriting intermediate quantities."],
        "3 + 4×5 equals 23 because the product 4×5 is formed first; (3+4)×5 equals 35 because the parentheses intentionally change the grouped quantity.",
        "Interpreting 20 ÷ 5 × 2 as 20 ÷ 10 ignores left-to-right evaluation of equal-priority division and multiplication; the value is 8.",
        "This lesson excludes exponents, variables, implicit multiplication, calculators with unusual entry conventions, and ambiguous informal notation.",
        ["numerical expression: numbers and operations representing a value", "grouping symbol: notation that marks a quantity to form first", "operation priority: the shared convention for interpreting ungrouped operations", "left to right: evaluation order among operations of equal priority"],
        "Operation order interprets one expression consistently; algebraic equivalence determines whether two expressions always share a value.",
        "Compare the cost expressions 2×(6+3) and 2×6+3: grouping shows the first buys two complete sets, while the second adds only one extra item.",
        "Grouping symbols are like packing several actions into one labeled box before using the box in a larger calculation.",
        "Parentheses can change the intended structure; decorative spacing cannot reliably do so.",
        "The expression 18-6÷3 is 16, while (18-6)÷3 is 4; naming the grouped units explains the difference.",
        "If two readings produce different values, I would return to the written grouping and priority conventions, then state any remaining ambiguity instead of hiding it.",
    ),
    _lesson(
        "curriculum_f2_multi_step_expression_model_verification_v1",
        "A multi-step expression should preserve the relationships in the situation it models",
        "Translating a situation into an expression requires identifying quantities, roles, and dependencies before calculating. Parentheses preserve a quantity that must be combined first. After evaluation, the result should be checked against the situation, an estimate, and an independently rewritten equivalent form. A correct calculation of the wrong expression is not a correct answer to the situation.",
        ["Name what every number and operation represents before evaluating.", "Use grouping to preserve dependent subrelationships.", "Check both the arithmetic and whether the expression models the stated situation."],
        "Three boxes each hold 8 red and 4 blue markers, so 3×(8+4)=36; 3×8+4=28 models a different situation.",
        "Obtaining 28 accurately from 3×8+4 does not answer the original all-three-boxes question because the blue markers were counted only once.",
        "This covers bounded whole-number situations with explicit quantities; uncertain data, rates, fractions, variables, and statistical models need later lessons.",
        ["model: a representation of relationships in a situation", "dependency: a quantity whose role depends on another grouping or action", "equivalent expression: a differently written expression with the same value", "reasonableness check: testing whether a result fits the situation and expected scale"],
        "Arithmetic verification checks the computation; model verification checks that the computation answers the intended question.",
        "Four tables each need 6 plates and 2 serving bowls: 4×(6+2)=32 items, which can also be checked as 4×6+4×2.",
        "An expression is a compact map: grouping preserves which quantities travel together through the situation.",
        "A computed answer can be numerically exact yet conceptually wrong if the model omitted or misgrouped a relationship.",
        "I would first explain why both item types repeat for every table, then evaluate 4×8 and verify it against the distributed form 24+8.",
        "If the arithmetic checks but the answer does not fit the situation, I would revise the model rather than defend the calculation.",
    ),
)
