from __future__ import annotations

from typing import Any


AUTHORIZATION_KEY = "f1_geometry_shares_algorithms_v1"
GROUP_KEY = "f1_geometry_shares_algorithms_group_4"

SEQUENCE_REFS = [
    "curriculum_source:core_knowledge_2023_sequence_k8",
    "sha256:c1c1788776b4e7ee064b7e26002945fa9ba13f111e324dc48ff6147886a530e5",
]
GEOMETRY_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:core_knowledge_g1_math_unit7",
    "sha256:17a99668e71a9094d1b30acf6a069edc8316003357c555d400c766bb78d90a8a",
    "https://www.coreknowledge.org/wp-content/uploads/2023/08/CKMath_G1U7_GeometryAndTime_Unit_Materials_W2.zip",
]
ALGORITHM_REFS = [
    *SEQUENCE_REFS,
    "curriculum_source:code_org_csf_curriculum_guide",
    "sha256:27148647c023fc37708446287a5c5f8e8aa771de9c0d589cc9511a0cec313e61",
    "https://code.org/en-US/curriculum/computer-science-fundamentals",
    "https://code.org/cs/about/code-org-free-curriculum-commitment",
]

SCOPE = {
    "bands": ["F1"],
    "families": ["MATH-1", "TECH-1", "ENG-1", "ELA-1", "LOGIC-1"],
    "source_ids": [
        "core_knowledge_2023_sequence_k8",
        "core_knowledge_g1_math_unit7",
        "code_org_csf_curriculum_guide",
    ],
    "knowledge_classes": ["public_academic_foundation"],
    "group_keys": [GROUP_KEY],
    "retention_rule": "Acquire, Integrate, and Express must all complete with sufficient source-linked comprehension evidence.",
}

LESSONS: tuple[dict[str, Any], ...] = (
    {
        "concept_key": "curriculum_f1_defining_shape_attributes_v1",
        "title": "Defining attributes classify shapes beyond surface appearance",
        "domain": "curriculum.f1.geometry",
        "material": "A shape belongs to a geometric category because of defining attributes such as its sides, corners, surfaces, or boundaries, not because of incidental features such as color, size, material, or orientation.",
        "principles": [
            "A defining attribute must remain relevant when the example is moved, resized, recolored, or made from another material.",
            "Category decisions should name the observed attribute that supports inclusion or exclusion.",
            "A familiar-looking object may only approximate a mathematical shape, so observation and interpretation remain distinct.",
        ],
        "relationships": ["Attribute-based classification connects geometry to observation, near-concept distinctions, evidence, and counterexamples."],
        "examples": ["A triangle remains a triangle when it is rotated because it still has three straight sides joined at three corners."],
        "counterexamples": ["A blue object is not a square merely because the classroom's example squares happened to be blue."],
        "limits": ["Elementary attribute descriptions do not replace later formal definitions, proofs, or analysis of curved and irregular boundaries."],
        "vocabulary": [
            "attribute: an observable or defined feature of an object",
            "defining attribute: a feature required for membership in a category",
            "non-defining attribute: a feature that may vary without changing category membership",
            "orientation: the direction in which an object is turned or positioned",
        ],
        "near_concept_distinctions": ["A defining attribute supports category membership; a common appearance is only a frequent presentation."],
        "scope_of_application": "Use for elementary shape classification by attributable geometric features. Preserve uncertainty when a drawing, image, or object does not reveal the required boundary clearly.",
        "unresolved_questions": ["Which visible attributes are necessary for the proposed category, and which merely happen to be present?"],
        "explanation": "Geometry classifies a shape by the structure it keeps when its presentation changes. Turning or recoloring a shape does not change how its sides and corners connect.",
        "application": "A diamond-shaped icon may be a rotated square if its four sides are equal and its corners have the required relationships; the screen angle alone does not create a new category.",
        "analogy": ["It resembles recognizing a tool by how its parts are arranged and function, not by the paint on its handle."],
        "questions": ["What attribute would still be present if this example were rotated, enlarged, or recolored?"],
        "comparisons": ["Color describes appearance; side and corner relationships can define a geometric category."],
        "participation": "It looks different because it is turned, but the defining side and corner relationships are unchanged, so it remains in the same shape category.",
        "correction_response": "If I classified it from color, orientation, or familiarity, I would return to the attributable sides, corners, surfaces, and boundaries and revise the category.",
        "families": ["MATH-1", "ELA-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit7"],
        "source_refs": GEOMETRY_REFS,
    },
    {
        "concept_key": "curriculum_f1_flat_solid_shapes_v1",
        "title": "Flat and solid shapes describe different spatial structures",
        "domain": "curriculum.f1.geometry",
        "material": "Flat shapes describe two-dimensional regions and boundaries, while solid shapes describe three-dimensional forms that occupy space; each kind needs attributes suited to its structure.",
        "principles": [
            "Flat shapes can be described with boundaries, straight or curved sides, and corners.",
            "Solid shapes can be described with surfaces, edges, corners, and how their parts meet.",
            "A picture of a solid shape is a flat representation of the solid rather than the physical solid itself.",
        ],
        "relationships": ["Distinguishing representation from represented object supports later measurement, modeling, diagrams, maps, and engineering drawings."],
        "examples": ["A drawn circle is flat, while a ball is a solid object whose surface can appear circular in a picture."],
        "counterexamples": ["A shaded drawing that appears deep does not acquire physical volume on the page."],
        "limits": ["Everyday objects may approximate several geometric forms and need not match an ideal mathematical solid exactly."],
        "vocabulary": [
            "two-dimensional: described across two independent spatial directions",
            "three-dimensional: described across three independent spatial directions",
            "flat shape: a two-dimensional region or boundary",
            "solid shape: a three-dimensional form that occupies space",
            "representation: one form used to depict or describe another object or relationship",
        ],
        "near_concept_distinctions": ["A drawing of a cube represents a solid form but remains a flat image."],
        "scope_of_application": "Use for elementary distinctions among flat figures, solid forms, and their visual representations. Treat ideal geometric descriptions and physical approximations separately.",
        "unresolved_questions": ["Are we discussing the represented solid, the flat drawing, or the physical object's approximate form?"],
        "explanation": "Flat and solid shapes answer different spatial questions. A flat diagram can communicate a solid object's structure, but the diagram and the object do not occupy space in the same way.",
        "application": "A floor plan is a flat representation of rooms in a building; it can show arrangement and dimensions without being the three-dimensional building.",
        "analogy": ["A map can represent a landscape without having the landscape's height, materials, or physical volume."],
        "questions": ["Which attributes belong to the representation, and which belong to the represented object?"],
        "comparisons": ["A rectangle has a flat boundary and region; a rectangular prism has surfaces and volume."],
        "participation": "The diagram is two-dimensional, while the object it depicts is three-dimensional. I can use the diagram as evidence about some relationships without treating it as the object itself.",
        "correction_response": "If I confused a flat representation with a solid object, I would name each separately and restate which attributes the representation actually preserves.",
        "families": ["MATH-1", "ELA-1", "ENG-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit7"],
        "source_refs": GEOMETRY_REFS,
    },
    {
        "concept_key": "curriculum_f1_nested_shape_categories_v1",
        "title": "One shape can belong to a broader and a narrower category",
        "domain": "curriculum.f1.geometry",
        "material": "Geometric categories can nest when every member of a narrower category also satisfies the defining attributes of a broader category, even though the reverse relationship does not hold.",
        "principles": [
            "Category membership follows defining attributes rather than a single preferred label.",
            "A square satisfies the elementary defining attributes of a rectangle and also adds equal side lengths.",
            "An example can be named at more than one valid level of specificity.",
        ],
        "relationships": ["Nested shape categories introduce subset reasoning, classification hierarchies, precise comparison, and later logical implication."],
        "examples": ["Every square is a rectangle under an attribute-based definition, but rectangles with unequal adjacent side lengths are not squares."],
        "counterexamples": ["Sharing one attribute, such as having four sides, does not make every four-sided shape a square."],
        "limits": ["This lesson establishes an elementary category relationship, not a complete hierarchy or formal geometric proof system."],
        "vocabulary": [
            "category: a group defined by shared criteria",
            "broader category: a category whose criteria include more possible members",
            "narrower category: a category adding criteria within a broader category",
            "subset: a group whose every member also belongs to another group",
        ],
        "near_concept_distinctions": ["Belonging to a broader category does not erase the more specific category; it records an additional true relationship."],
        "scope_of_application": "Use when category definitions genuinely nest. Verify that every member of the proposed narrower category meets every defining criterion of the broader one.",
        "unresolved_questions": ["Does the narrower definition guarantee all of the broader category's required attributes?"],
        "explanation": "Categories can overlap by containment rather than competition. Calling a square a rectangle records a broader truth while calling it a square preserves the more specific one.",
        "application": "A sedan is both a car and a vehicle. The broader label is accurate, while the narrower label communicates additional attributes.",
        "analogy": ["A chapter remains part of a book even when we name the chapter specifically."],
        "questions": ["Which requirements are shared, and what additional requirement creates the narrower category?"],
        "comparisons": ["All squares are rectangles under the stated definitions; not all rectangles are squares."],
        "participation": "Both labels can be true. The narrower category adds a requirement without losing membership in the broader one.",
        "correction_response": "If I treated related categories as mutually exclusive, I would compare their defining criteria and rebuild the inclusion relationship.",
        "families": ["MATH-1", "ELA-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit7"],
        "source_refs": GEOMETRY_REFS,
    },
    {
        "concept_key": "curriculum_f1_shape_composition_decomposition_v1",
        "title": "Shapes can be composed and decomposed while relationships stay traceable",
        "domain": "curriculum.f1.geometry",
        "material": "Smaller shapes can be arranged to compose a larger shape, and a larger shape can be decomposed into smaller parts; different valid arrangements may produce the same outer shape.",
        "principles": [
            "Composition forms a whole from parts whose placements and boundaries matter.",
            "Decomposition identifies parts within a whole without claiming that only one partition is possible.",
            "A valid composition must account for the intended region without unintended gaps or overlaps.",
        ],
        "relationships": ["Shape composition connects part-whole reasoning to addition, fractions, area, design, decomposition, and systems thinking."],
        "examples": ["Two congruent right triangles can be arranged along matching edges to form a rectangle."],
        "counterexamples": ["Pieces that extend outside the intended boundary or leave an uncovered gap do not exactly compose that target region."],
        "limits": ["Matching an outer boundary does not prove that two constructions have the same internal structure, material, strength, or purpose."],
        "vocabulary": [
            "compose: form a whole by arranging parts",
            "decompose: identify or separate a whole into parts",
            "composite shape: a shape constructed from smaller shapes",
            "boundary: the edge separating a region from what lies outside it",
        ],
        "near_concept_distinctions": ["Decomposing a shape reveals one possible part structure; it does not require physically breaking an object."],
        "scope_of_application": "Use for bounded flat or solid shape constructions whose parts, placements, and target boundary are specified. Preserve differences among equally shaped but structurally different constructions.",
        "unresolved_questions": ["Do the parts cover the intended whole exactly, and is this the only relevant decomposition?"],
        "explanation": "A whole shape can often be built in several ways. Tracking how the parts meet shows both what stays the same—the target boundary—and what can differ—the internal arrangement.",
        "application": "A dashboard panel can be divided into two smaller rectangles in several ways while keeping the same outer panel dimensions; the layouts may still support different content.",
        "analogy": ["The same melody duration can be composed from different note lengths even though the internal rhythm changes."],
        "questions": ["What remains invariant across the different compositions, and what changes?"],
        "comparisons": ["Composition reasons from parts toward a whole; decomposition reasons from a whole toward possible parts."],
        "participation": "Both arrangements make the same outer rectangle, but their internal boundaries differ. That means they share one geometric result without being identical constructions.",
        "correction_response": "If I overlooked a gap, overlap, or alternate decomposition, I would trace the boundaries again and revise the claimed relationship.",
        "families": ["MATH-1", "ENG-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit7"],
        "source_refs": GEOMETRY_REFS,
    },
    {
        "concept_key": "curriculum_f1_spatial_reference_relationships_v1",
        "title": "Spatial descriptions depend on a stated reference",
        "domain": "curriculum.f1.geometry",
        "material": "Words such as left, right, above, below, beside, inside, outside, nearer, and farther describe relationships relative to a chosen object, observer, direction, or boundary.",
        "principles": [
            "A spatial relation needs both the described item and its reference.",
            "Some relations change when the observer or orientation changes, while others remain stable under that change.",
            "Clear directions preserve order and state which frame of reference controls ambiguous terms.",
        ],
        "relationships": ["Reference-aware spatial language supports maps, diagrams, geometry, navigation, instructions, interfaces, and referent resolution in conversation."],
        "examples": ["A book may be left of a lamp from one viewing direction and right of it after the observer moves to the opposite side."],
        "counterexamples": ["Saying an object is 'over there' without a shared viewpoint or referent does not specify a reliable location."],
        "limits": ["Elementary relative-position terms do not replace coordinates, scale, orientation markers, or accessibility-aware directions when precision matters."],
        "vocabulary": [
            "spatial relation: a description of how positions or regions are connected",
            "reference: the object, origin, observer, or frame relative to which a relation is stated",
            "direction: an indicated course or orientation",
            "boundary: a limit distinguishing inside from outside",
        ],
        "near_concept_distinctions": ["Position locates something within a frame; direction describes an orientation or course from that frame."],
        "scope_of_application": "Use for ordinary spatial descriptions when the referent and viewpoint are explicit or shared. Request or supply a frame when the wording could reverse or drift.",
        "unresolved_questions": ["Relative to which object, orientation, or observer is this relation true?"],
        "explanation": "Spatial words do not float alone; they connect one place to a reference. Naming that reference keeps a useful description from changing meaning when the viewpoint changes.",
        "application": "In an interface, 'the button on the right' is stable only if the layout, reading direction, and referenced panel are clear; a label or container gives a better anchor.",
        "analogy": ["A pronoun needs an antecedent in language much as 'left of' needs a spatial referent."],
        "questions": ["What is the reference point, and would this description change from another viewpoint?"],
        "comparisons": ["Inside a boundary can remain stable as an observer moves; left and right may reverse with orientation."],
        "participation": "From the diagram's labeled top, the node is left of the hub. If we rotate the diagram, I would restate the orientation instead of assuming 'left' stayed absolute.",
        "correction_response": "If I used an unstated or wrong viewpoint, I would name the intended reference and reconstruct the spatial relation from it.",
        "families": ["MATH-1", "ELA-1", "TECH-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit7"],
        "source_refs": GEOMETRY_REFS,
    },
    {
        "concept_key": "curriculum_f1_equal_shares_whole_v1",
        "title": "Halves and fourths require equal shares of the same whole",
        "domain": "curriculum.f1.fractions",
        "material": "A whole partitioned into two equal shares has halves, and the same whole partitioned into four equal shares has fourths or quarters; the fraction name describes an equal part in relation to its specified whole.",
        "principles": [
            "The shares must be equal with respect to the relevant quantity, such as area for a flat region.",
            "A half or fourth is always a part of a stated whole rather than an absolute size.",
            "For the same whole, four equal shares are individually smaller than two equal shares.",
            "Different-looking partitions can still create equal shares if the relevant quantities are equal.",
        ],
        "relationships": ["Equal shares connect division, geometry, measurement, fairness language, ratios, and later fraction operations."],
        "examples": ["A rectangular region divided into four equal-area regions gives four fourths even when the cuts create different orientations."],
        "counterexamples": ["Two pieces are not halves merely because there are two of them; unequal pieces do not form equal halves."],
        "limits": ["Visual appearance alone may not establish equal area, mass, volume, value, or fairness; the relevant whole and measured attribute must be named."],
        "vocabulary": [
            "whole: the complete quantity selected as the reference",
            "equal share: one of several parts equal in the relevant measured quantity",
            "half: one of two equal shares of the same whole",
            "fourth: one of four equal shares of the same whole",
            "quarter: another name for one fourth",
        ],
        "near_concept_distinctions": ["Equal number of pieces does not guarantee equal shares; equality concerns the relevant quantity of each piece."],
        "scope_of_application": "Use for elementary partitions of one specified whole into two or four equal shares. Name the whole and the attribute being shared before comparing fraction sizes.",
        "unresolved_questions": ["What is the whole, and by what attribute have the shares been shown equal?"],
        "explanation": "Fraction words describe a relationship between a part and its whole. The number of parts is not enough: the shares must be equal, and comparisons require the same whole or an explicit measurement.",
        "application": "Half of a short timeline can represent less duration than a fourth of a much longer timeline, so the fraction name alone does not decide which absolute interval is larger.",
        "analogy": ["A percentage describes a share of a reference total; changing the reference can change the amount even when the named share stays the same."],
        "questions": ["Are the shares equal, and are we comparing parts of the same whole?"],
        "comparisons": ["For one fixed whole, a half is larger than a fourth; across different wholes, the absolute sizes require more information."],
        "participation": "There are four pieces, but they are not automatically fourths. I need evidence that the same whole was divided into four equal shares.",
        "correction_response": "If I counted unequal pieces or compared fractions from unstated wholes, I would identify the reference whole, measure the relevant attribute, and revise the claim.",
        "families": ["MATH-1", "ELA-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "core_knowledge_g1_math_unit7"],
        "source_refs": GEOMETRY_REFS,
    },
    {
        "concept_key": "curriculum_f1_ordered_algorithm_v1",
        "title": "An algorithm is a bounded ordered sequence for a task",
        "domain": "curriculum.f1.computing",
        "material": "An elementary algorithm is a finite sequence of sufficiently clear instructions intended to accomplish a stated task; changing, omitting, or ambiguously describing a required step can change the result.",
        "principles": [
            "The task or desired result must be stated before the instruction sequence can be judged.",
            "Each instruction needs enough precision for the intended interpreter and context.",
            "Order matters whenever an earlier step creates a condition needed by a later one.",
            "A written algorithm describes a process but does not grant authority to execute it.",
        ],
        "relationships": ["Algorithms connect ordinary sequencing language, goals, inputs, actions, outputs, constraints, and later programming."],
        "examples": ["To compare two versioned documents, first identify the versions, then compute the difference, then interpret the changed lines in context."],
        "counterexamples": ["'Make it work' states a goal but does not supply a finite, inspectable sequence of instructions."],
        "limits": ["A clear sequence can still pursue the wrong goal, rely on false assumptions, or require authority and resources it does not have."],
        "vocabulary": [
            "algorithm: a bounded ordered set of instructions intended to accomplish a task",
            "sequence: an ordering in which items or actions occur",
            "instruction: a description of an action or decision step",
            "task: the result or problem the sequence is intended to address",
            "trace: follow the steps while recording what happens",
        ],
        "near_concept_distinctions": ["A goal says what is wanted; an algorithm describes a bounded process intended to reach it."],
        "scope_of_application": "Use to describe or inspect bounded procedures. Keep execution, filesystem, tool, memory, and autonomy permissions separate from knowledge of the procedure.",
        "unresolved_questions": ["Is the task sufficiently defined, and can each step be interpreted under the stated conditions?"],
        "explanation": "An algorithm makes a process inspectable by placing clear steps in an order tied to a goal. Its quality depends on both the sequence and the conditions under which it is meant to work.",
        "application": "A source-review algorithm can identify a source, preserve its URL and license, verify a checksum, and only then prepare a review candidate; knowing those steps does not authorize importing anything.",
        "analogy": ["It is like a route description: the destination matters, and each turn depends on where the previous turn left you."],
        "questions": ["What is the task, what conditions does the sequence assume, and where would a changed order alter the outcome?"],
        "comparisons": ["A checklist may record independent items; an algorithm records steps whose order and state can affect the result."],
        "participation": "The intended result is clear, but the process skips the verification step. I would add that step before treating the sequence as reliable.",
        "correction_response": "If a trace shows that I omitted, reordered, or underspecified a required step, I would revise the sequence and trace it again from the stated starting conditions.",
        "families": ["TECH-1", "ENG-1", "ELA-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "code_org_csf_curriculum_guide"],
        "source_refs": ALGORITHM_REFS,
    },
    {
        "concept_key": "curriculum_f1_repetition_debugging_v1",
        "title": "Repeated steps can be expressed as a pattern and checked by tracing",
        "domain": "curriculum.f1.computing",
        "material": "When the same instruction or short sequence recurs under a clear stopping condition, it can be represented as a repeating pattern; tracing the pattern exposes whether the process reaches the intended result and where revision is needed.",
        "principles": [
            "A repeating pattern identifies what recurs and in what order.",
            "A bounded repetition needs a count, condition, or observable stopping point.",
            "Tracing compares expected and observed intermediate states rather than judging only the final appearance.",
            "Debugging revises the procedure or its assumptions; an unexpected result is information about the process, not personal failure.",
        ],
        "relationships": ["Repetition and tracing connect patterns, counting, prediction, algorithms, evidence, correction readiness, and graceful fall."],
        "examples": ["A layout procedure can repeat 'place one equal tile beside the last' until the stated boundary is reached, while a trace records each placement."],
        "counterexamples": ["Repeating forever without a count, condition, or externally defined stopping rule is not a bounded elementary procedure."],
        "limits": ["A repeated surface pattern does not by itself reveal its cause, and a successful trace on one input does not prove correctness for every input."],
        "vocabulary": [
            "repetition: carrying out an instruction or sequence again",
            "pattern: an identifiable regularity in arrangement or change",
            "stopping condition: the stated circumstance under which repetition ends",
            "debugging: locating and revising a mismatch between intended and observed process behavior",
            "intermediate state: a recorded condition between the start and final result",
        ],
        "near_concept_distinctions": ["A pattern describes regularity; an explanation of the pattern's cause requires additional evidence."],
        "scope_of_application": "Use for bounded repeated procedures and simple pattern descriptions. State the stopping condition and preserve uncertainty about generalization beyond the traced cases.",
        "unresolved_questions": ["What exactly repeats, what stops it, and which intermediate state first differs from expectation?"],
        "explanation": "Repetition compresses a recurring sequence, while tracing unfolds it again so each state can be checked. A mismatch points to a step, condition, or assumption that may need revision.",
        "application": "If a report generator processes one record and advances to the next until no reviewed records remain, a trace can reveal whether it skipped an item or failed to stop at the boundary.",
        "analogy": ["A musical refrain repeats a recognizable sequence, but a performance check still follows when and how often it returns."],
        "questions": ["What repeats, how is the next state produced, and what condition ends the repetition?"],
        "comparisons": ["Prediction states what should happen; tracing records what did happen at each bounded step."],
        "participation": "The repeated rule is plausible, but the trace diverges on the third step. I would inspect that transition and the stopping condition before trusting the final result.",
        "correction_response": "If the observed sequence differs from the expected one, I would treat the mismatch as diagnostic evidence, revise the responsible step or assumption, and rerun only the bounded trace needed.",
        "families": ["TECH-1", "ENG-1", "MATH-1", "LOGIC-1"],
        "source_ids": ["core_knowledge_2023_sequence_k8", "code_org_csf_curriculum_guide"],
        "source_refs": ALGORITHM_REFS,
    },
)
